### ISSUE TITLE
Issue with formatting

### ISSUE THREAD

**Issue by ricardas** [jmcnamara/libxlsxwriter#10]
This is snippet from my code:

lxw_format *format = workbook_add_format(workbook);

format_set_font_color(format, 0xff0000); // set red color
worksheet_write_string(worksheet, 0, 0, "Red", format); // write to cell
format_set_font_color(format, 0x00ff00); // set green color
worksheet_write_string(worksheet, 0, 1, "Green", format); // write to another cell

why both cells have green font color?

**Comment by jmcnamara** [comment]
That is the documented behavior. See the [Workong with Formats](http://libxlsxwriter.github.io/working_with_formats.html) section of the docs.

**Comment by ricardas** [comment]
Oh, i didn't notice that. All is clear now, thanks.
