### ISSUE TITLE
libxlsxreader

### ISSUE THREAD

**Issue by AlfonsoUceda** [jmcnamara/libxlsxwriter#105]
Hi @jmcnamara 

Thanks for your work, I open this issue to asking a question, is there a similar version like libxlsxwriter but for reading? libxlsxreader?

Thanks ;)

**Comment by jmcnamara** [comment]
> is there a similar version like libxlsxwriter but for reading

Not that I'm aware of. However, I've never really needed or looked for one either.

Sorry I can't be of more help.

**Comment by AlfonsoUceda** [comment]
@jmcnamara thank you ;)
