### ISSUE TITLE
Too many open files when adding lots of images

### ISSUE THREAD

**Issue by spulchtopek** [jmcnamara/libxlsxwriter#106]
I am trying to generate a spreadsheet that has one or more columns of icons in addition to columns of text and numbers. I tried using the `worksheet_insert_image()` function to insert the icons (PNG images) into the column cells for the appropriate row. 

It works fine as long as the number of total images is small. As soon as the number of images exceeds ~250, they are no longer added to the spreadsheet. I think is due to the number of open files limit in iOS. 

It looks like the library keeps all of the image files open instead of just opening them when needed.

**Comment by jmcnamara** [comment]
Thanks for the report.

That is a bug. It should be a relatively easy fix.

**Comment by jmcnamara** [comment]
Fixed in version 0.7.0 on master and in Cocoapods.
