### ISSUE TITLE
Compilation fails in Centos 6.2

### ISSUE THREAD

**Issue by ngiraldo** [jmcnamara/libxlsxwriter#11]
As described.

Please inform us in which versions of CentOS does the library work.

**Comment by jmcnamara** [comment]
Can you add a trace of the build failure.

**Comment by ngiraldo** [comment]
Hello, I'm not at the office until tomorrow.

I just remember that's not the library itself failing, but the minizip dependency, which in CentOS can be installed via yum.

**Comment by jmcnamara** [comment]
The [Getting Started](http://libxlsxwriter.github.io/getting_started.html) guide explains that zlib 1.2.8 is required. Did you install that? 

Snippet:

>**Install the dependencies**

>Zlib version 1.2.8 is the only (non-testing) dependency.

>The easiest way to install zlib is from the source code:

```
curl -O -L  http://zlib.net/zlib-1.2.8.tar.gz
tar zxf zlib-1.2.8.tar.gz
cd zlib-1.2.8

./configure
make

sudo make install
```

>On recent Debian Linux systems you can install the zlib development libraries using apt-get as follows:

```
sudo apt-get install -y zlib1g-dev
```
>However, you need to ensure that the version is 1.2.8 or you will get zlib related compilation issues.

**Comment by ngiraldo** [comment]
I have no problems with Ubuntu.

In CentOS I have zlib-devel-1.2.3-29.el6.x86_64.

Will update to 1.2.8.

**Comment by ngiraldo** [comment]
Sorry, the issue is that Centos 6 has painfully old libraries.

It works fine with the manual zlib install.
