### ISSUE TITLE
Wrong Styles in large Sheet file

### ISSUE THREAD

**Issue by mileder** [jmcnamara/libxlsxwriter#111]
after creating the large excel sheet (approx. 25.000 lines) the styles are not assigned / available.

In the XML file of sheet styles have negative id's: probably overflow somewhere

**Comment by jmcnamara** [comment]
Hi,

As you say it is probably an overflow issue. However the type should be int32_t so it should take several billion unique formats to overflow. 

Do you actually have so many unique formats that the default size would overflow?

The best thing would be to post a small working example that demonstrates the issue. 

John.

**Comment by mileder** [comment]
[11000000-0485-24C5-2017-070615061377.xlsx](https://github.com/jmcnamara/libxlsxwriter/files/1160133/11000000-0485-24C5-2017-070615061377.xlsx)

**Comment by mileder** [comment]
i send you an email with example file
