### ISSUE TITLE
Feature request: possibility to create xslx file in memory

### ISSUE THREAD

**Issue by mileder** [jmcnamara/libxlsxwriter#113]
the zlib allows operations only in memory. It would be great to have possibility to create the Excel file just in memory.

**Comment by jmcnamara** [comment]
It is a good idea and the Perl and Python versions of the library support it.

However, the internal plumbing of libxlsxwriter is based on `FILE*` pointers and functions so converting it over would be a bit messy. It is the sort of thing that would be more easily done in C++.

So unfortunately it is a "won't fix" for now.
