### ISSUE TITLE
Add support for floating-point number font size

### ISSUE THREAD

**Issue by ohmyarch** [jmcnamara/libxlsxwriter#114]
void format_set_font_size(lxw_format *format, uint16_t size)
->
void format_set_font_size(lxw_format *format, double size)

**Comment by jmcnamara** [comment]
Hi Michael,

Good point. I'll fix that.

John

**Comment by jmcnamara** [comment]
Fixed in version 0.7.2.

Thanks for the report.

**Comment by ohmyarch** [comment]
🎉👍
