### ISSUE TITLE
Question: Column Auto-Fit

### ISSUE THREAD

**Issue by petricf** [jmcnamara/libxlsxwriter#118]
I've read in the FAQ that this is not available here. But a hint for a workaround was given:
```
It is possible to simulate "AutoFit" by tracking the width of the data in the column as your write it.
```

I don't know how evaluate the data width on strings or numbers i intend to write. How to map it to a column width for use (for example) in function worksheet_set_column ?

Is there some sample code available ?

**Comment by jmcnamara** [comment]
> I don't know how evaluate the data width on strings or numbers i intend to write. How to map it to a column width for use (for example) in function worksheet_set_column ?

From the docs for [worksheet_set_column()](http://libxlsxwriter.github.io/worksheet_8h.html#a9656e4e05d3787eee6b3e4d8e82d9b7f):

>The width parameter sets the column width in the same units used by Excel which is: the number of characters in the default font. The default width is 8.43 in the default font of Calibri 11. The actual relationship between a string width and a column width in Excel is [complex](https://support.microsoft.com/en-us/help/214123/description-of-how-column-widths-are-determined-in-excel). See the following explanation of column widths from the Microsoft support documentation for more details.

What this means in practice is that in the default font the column width is approximately equal to the length of the string (unless the string is iiiiiiii or WWWWWWWW). To be sure you could multiply the strlen() by 1.1 or 1.2.
