### ISSUE TITLE
Use system minizip when possible

### ISSUE THREAD

**Issue by ohmyarch** [jmcnamara/libxlsxwriter#119]
When system-wide installed minizip can be found, use it instead of bundled one.

**Comment by jmcnamara** [comment]
Why do you want this feature?

**Comment by ohmyarch** [comment]
Why do you use system zlib?

**Comment by jmcnamara** [comment]
Because zlib is very common and available almost everywhere. Minizip isn't.

**Comment by ohmyarch** [comment]
I don't think so. Minizip is also a common package and can be installed via a single command in many cases, for example:
```zsh
 pacman -S minizip
```
```zsh
brew install minizip
```
I am not asking you to remove the bundled version. I just think that it's usually better to use the system library. Using system (shared) libraries can save disk space and memory. Besides, system libraries can be always up-to-date in some rolling release distro.

If you think it's unnecessary, just close this issue.

**Comment by jmcnamara** [comment]
Thanks for the explanation. When I started this project 3 years ago I didn't see many packaged versions of minizip. In general I would prefer not to have to bundle it. 

I'll add this feature to the Make build system. Adding it to the CMake system may take a bit longer.

**Comment by jmcnamara** [comment]
I've added this to the master branch for the Makefile build system. It can be invoked as follows:

    USE_STANDARD_TMPFILE=1 make

**Comment by jmcnamara** [comment]
@Alexhuszagh When you get a chance can you look at adding support for system minizip to the CMake system as well.

**Comment by jmcnamara** [comment]
@ohmyarch Did you get a change to try this?

**Comment by jmcnamara** [comment]
@Alexhuszagh, this is one you could have a look at as well. However, it isn't high priority so if you don't want to add it to the CMake build that is okay.

**Comment by Alexhuszagh** [comment]
@jmcnamara Sorry I just saw this. I should be able to get around to it next week.

**Comment by Alexhuszagh** [comment]
@jmcnamara This should be patched in my [downstream fork](https://github.com/Alexhuszagh/libxlsxwriter/tree/minizip). It relies on the changes made in #131, however, if need be, I can make the changes atop the current CMakeLists. If these changes are satisfactory, I will submit a PR.

**Comment by jmcnamara** [comment]
@ohmyarch can you try the fix on master for this. See also #133

**Comment by ohmyarch** [comment]
<pre>
ldd /usr/lib/libxlsxwriter.so

linux-vdso.so.1 (0x00007ffda713f000)
<b>libminizip.so.1 => /usr/lib/libminizip.so.1 (0x00007f14b3212000)</b>
libc.so.6 => /usr/lib/libc.so.6 (0x00007f14b2e5b000)
libz.so.1 => /usr/lib/libz.so.1 (0x00007f14b2c44000)
/usr/lib64/ld-linux-x86-64.so.2 (0x00007f14b365c000)
</pre>

It works. 🎉👍
