### ISSUE TITLE
Support for NaN, Inf, -Inf

### ISSUE THREAD

**Issue by jeroen** [jmcnamara/libxlsxwriter#122]
Would it be possible to add a line to the `worksheet_write_number` documentation if excel supports special values `NaN`, `Inf`, and `-Inf`. I just tried:

```c
assert_lxw(worksheet_write_number(sheet, x, y, INFINITY, NULL));
```

Which does not raise an error in lxw, however when I open the file in excel it gives an error that it is "damaged".

**Comment by jmcnamara** [comment]
Excel doesn't support `NaN`, `Inf` or `-Inf` as a value. It does support them as the result of a formula but not as a number.

I can add something to the docs to say Excel, and thus libxlsxwriter, doesn't support them but, for performance reasons, I won't add a check. The end user can do it in their application if they need it.

**Comment by jeroen** [comment]
OK thanks. I figured this from trying but wasn't sure. The weird thing is that if you insert `INFINITY` or `NAN`, excel first shows a warning that the document is damanged, but then does properly display `nan` or `inf` inside the cell, making it look as if it can be supported.

**Comment by jmcnamara** [comment]
> but then does properly display nan or inf inside the cell, making it look as if it can be supported.

Yes, but they are just converted to strings, right? As I said Excel doesn't support them as numbers.

You can handle the values as strings in your application in a similar way if you like.

Btw, what lib/application are you using libxlsxwriter in. I see that you have a very active GitHub timeline. :-)

**Comment by jeroen** [comment]
I am writing bindings for R: https://github.com/ropensci/writexl

**Comment by jmcnamara** [comment]
> I am writing bindings for R: https://github.com/ropensci/writexl

Cool.

Could you add `libxlsxwriter` as a "topic" under the title of your GitHub project like in [libxlsxwriter](https://github.com/jmcnamara/libxlsxwriter) so that your project shows up in [this list](https://github.com/search?q=topic%3Alibxlsxwriter&type=Repositories).



> I can add something to the docs to say Excel, and thus libxlsxwriter, doesn't support them but, for performance reasons, I won't add a check. The end user can do it in their application if they need it.

I've added a note about handling (or not handling) NaN, Inf or -Inf to the [worksheet_write_number() docs](http://libxlsxwriter.github.io/worksheet_8h.html#ad9fc47d3beaa2ab4759414e8580c2289).

Thanks.

**Comment by jeroen** [comment]
OK I have added the topic to the repo.
