### ISSUE TITLE
LICENSE.txt is missing tmpfileplus and tree.h

### ISSUE THREAD

**Issue by jeroen** [jmcnamara/libxlsxwriter#123]
I'm having a hard time publishing my bindings because the comments contain several copyright holders which are not mentioned in the license.

**Comment by jmcnamara** [comment]
The full list of licences are included in the [doc sources](https://github.com/jmcnamara/libxlsxwriter/blob/master/docs/src/license.dox) and rendered in the [on-line docs](https://libxlsxwriter.github.io/license.html).

However, the LICENSE.txt file isn't up to date with the doc file (I thought that I had linked them like the Changes file). So I'll fix that.

For now refer to the  [License file](https://github.com/jmcnamara/libxlsxwriter/blob/master/docs/src/license.dox) in the docs.

**Comment by jmcnamara** [comment]
I've created a single License file shared between the src tree and the docs with the minizip contributions called out.

Note, if you are confident that the system you are targeting already have a minizip library you can [compile libxlsxwriter without it](http://libxlsxwriter.github.io/getting_started.html#gsg_minizip) and probably drop that part of the copyright/licence. The same applies for tempfileplus.

However, the header files are still installed with libxlsxwriter if you do `make install`. I'll fix that shortly.

**Comment by jmcnamara** [comment]
Also, unrelated to this but so you know, if you are using libxlsxwriter on systems with LANG settings that change the locale to one that uses a comma as a decimal point then you will run into issues. See #64.
