### ISSUE TITLE
Question: Pointer to lxw_worksheet if lxw_workbook is closed 

### ISSUE THREAD

**Issue by petricf** [jmcnamara/libxlsxwriter#126]
If - by accident or coding error - lxw_worbook is closed, but lxw_woksheet/-format/... is used afterwards - what does happen ?

Does it throw an assert, ignore requests, invalid memory access exception, ... ?

Is there a method to verify that the workbook is closed when actually using the other pointers ?
In other words - can i check (for example) an lxw_worksheet pointer whether the accompanied workbook is still open ?

Functions like
> bool worksheet_valid (lxw_worksheet * sheet);
> bool format_valid (lxw_format * format);
> bool is_document_open (lxw_worksheet * worksheet);

to check the pointers without requiring access to lxw_workbook pointer would be nice.

Reasoning: At the location i use lxw_worksheet i have currently no access to its accompanied lxw_workbook.

**Comment by jmcnamara** [comment]
> Does it throw an assert, ignore requests, invalid memory access exception, ... ?

Currently there isn't a warning but there probably should be. Also, I could add a function to check if a workbook is closed.

However, I'm not convinced by the use case for accessing the workbook from a worksheet. That seems to me to be something that could be handled in the application logic.

If that part of the request gets some +1 then I'll add it.

**Comment by petricf** [comment]
All functions writing to a worksheet do not need access to the lxw_workbook pointer. They have a lxw_worksheet pointer.
If you simply pass the the worksheet pointer to separate (for example) thread or (im my case) a separate class instance (at init) you run in a problem (no - not if you code carefully - but shit happens ...).
Inside there you don't know whether the workbook have been already closed when accessing the class methods (which are using the worksheet pointer to write data) later.

So you have a worksheet pointer whose workbook have been closed but you do not have the ability to verify this.

**Comment by jmcnamara** [comment]
> not if you code carefully

For me this is the important part. In general I am against adding syntactic sugar for things that can be handled in the end-users application apart from cases that are really painful to do otherwise or cases that are frequently requested.

**Comment by petricf** [comment]
Sure. But nobody is perfect - even i am not.
Having a safeguard - in my opinion - is never a mistake.
