### ISSUE TITLE
Feature request: Add support for pkg-config

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#132]
Add support for creating and installing a pkg-config file to the `make install` target.

**Comment by jmcnamara** [comment]
@sjmulder Do you know much about pkg-config files and would it be worth adding one for libxlsxwriter?

**Comment by sjmulder** [comment]
It would seem useful and the format is [simple enough](https://people.freedesktop.org/~dbn/pkg-config-guide.html), but I'm not sure if .pc files are generally supplied by the author or by the distribution/packaging system.

**Comment by jmcnamara** [comment]
I'm just going to drop this. The simplicity of libxlsxwriter linking doesn't currently merit it.
