### ISSUE TITLE
File name with one letter

### ISSUE THREAD

**Issue by Nipou** [jmcnamara/libxlsxwriter#135]
In Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Visual C++ 2015   00325-60001-65048-AA435

      string filename = "test.xlsx";
      lxw_workbook  *workbook = workbook_new(filename.c_str());
      addToWorkbook(workbook);
      workbook_close(workbook);

Produce the valid file 't'. 
This code do the same :
	
      char name[10] = { 't','e','s','t','.','x','l','s','x','\0' };
      lxw_workbook  *workbook = workbook_new(&name[0]);

**Comment by jmcnamara** [comment]
There is #define code to avoid that issue with MSVC: https://github.com/jmcnamara/libxlsxwriter/blob/18c8cb6dd276bdf6da1527ad65b541539dc4e727/src/packager.c#L33

Your compiler should pick that up.

**Comment by jmcnamara** [comment]
Can you check out and compile this project using the instructions and let me know if it works for you: https://github.com/jmcnamara/MSVCLibXlsxWriter

**Comment by Nipou** [comment]
Sorry but I workaround. No time to spend.

       wxCopyFile("x", filename);
       wxRemoveFile("x");

Otherwise the library work very fine.

Thanks you

**Comment by jmcnamara** [comment]
This issue should now be fixed on the master branch.
