### ISSUE TITLE
Footer and header margins does not sets to 0

### ISSUE THREAD

**Issue by RaFaeL-NN** [jmcnamara/libxlsxwriter#140]
Unable to set margin with worksheet_set_header_opt (or worksheet_set_footer_opt) to 0, it sets to default. May be a good way is to changes this methods for using -1 as default (like in worksheet_set_margins) and 0 as working value? Thanks

**Comment by Genricke** [comment]
There is such a problem and it is not solved. :(

**Comment by jmcnamara** [comment]
There is now a fix for this on the master branch.

**Comment by RaFaeL-NN** [comment]
It works, big thanks!
