### ISSUE TITLE
Static link error

### ISSUE THREAD

**Issue by tdmartin102** [jmcnamara/libxlsxwriter#141]
I am Using Xcode 9.2 and CocoaPods. This library would not compile for me   The issue is probably a compiler setting but a easy code fix is casting.  in worksheet.c:26010, 2611, 2621,2622 a macro is used such as:

`lxw_col_t span_col_min = RB_MIN(lxw_table_cells, row->cells)->col_num;`

casting eliminates the error

`lxw_col_t span_col_min = ((lxw_cell*)RB_MIN(lxw_table_cells, row->cells))->col_num;`

mind you this should be a warning not an error.  If I knew the compiler flag to prevent this error I would use that.  Also perhaps this should apply to CocoaPods and not you.  This is my very first use of CocoaPods, so if this is the wrong place, just let me know and I'll pester them instead.

**Comment by jmcnamara** [comment]
Fix added on master branch.

**Comment by jmcnamara** [comment]
Added in version 0.7.6. Closing.
