### ISSUE TITLE
Pointers to Axis and Error_bars

### ISSUE THREAD

**Issue by RaFaeL-NN** [jmcnamara/libxlsxwriter#142]
To use the libxlsxwriter in languages other than C as external dll (where C headers can not be used), it would be better to add methods that return pointers to axis and error_bars, something like

```C
lxw_chart_axis * chart_get_axis (lxw_chart * chart, uint8_t type)
lxw_series_error_bars * chart_series_get_error_bars(lxw_chart_series * series,  uint8_t type)
```
(type means X or Y)

So, it will simply use these pointers in `chart_series_set_error_bars*`and `chart_axis_set* methods`.

**Comment by jmcnamara** [comment]
I've push a fix for this to the master branch. See commit d863c8e.

**Comment by RaFaeL-NN** [comment]
Works good, thanks

**Comment by jmcnamara** [comment]
Added in version 0.7.6. Closing.
