### ISSUE TITLE
Possible problem with black colors in charts

### ISSUE THREAD

**Issue by RaFaeL-NN** [jmcnamara/libxlsxwriter#144]
Because color=0, has_color does not sets to true and solidFill section does not presents in xml. For some objects (for example, Chart Area Line) black color is not default color for display in this way (gray is). So, it's impossible to set (for example) Chart Area Line to black by API

**Comment by jmcnamara** [comment]
You can use the hash define LXW_COLOR_BLACK for black. See the Working with Colors section of the docs and the note about black:

https://libxlsxwriter.github.io/working_with_colors.html
