### ISSUE TITLE
Lib trying to free image memory without image defined

### ISSUE THREAD

**Issue by ncfernan** [jmcnamara/libxlsxwriter#145]
When using the function **worksheet_insert_chart_opt** the options parameters is copied to an internal structure that is shared with image functions, so when the program closes the workbook, the **image** points to dirty areas because no image was set.

If the **options** parameter is set to NULL, no problem arises.

  ```
lxw_image_options options;

  options.x_offset = 0;
  options.y_offset = 0;
  options.x_scale  = 4.0;
  options.y_scale  = 1.2;

  worksheet_insert_chart_opt (worksheet, 1, col, chart, &options);
```

![image](https://user-images.githubusercontent.com/10008844/35452435-9dffdaf2-02ad-11e8-896b-3419b4edc2d0.png)

**Comment by ncfernan** [comment]
I found the problem in **worksheet.c**:

![image](https://user-images.githubusercontent.com/10008844/35453393-39c1aa76-02b1-11e8-95a3-8a6e772624aa.png)

**Comment by jmcnamara** [comment]
Thanks for the report. 

Could you add a small, compilable program that demonstrates the issue. 

John

**Comment by RaFaeL-NN** [comment]
I sent out the same report a month ago. The problem is especially relevant when using the library with other programming languages in binary form. The best way is to split the options into two structures - one for external user use with 4 fields as a parameter, and the second one complete for internal

**Comment by jmcnamara** [comment]
@ncfernan You will need to initialize the `lxw_image_options` struct since it includes some non public members.

```C
lxw_image_options options = {0};
```
However, I'll split the external and internal structs in a future release to avoid this type of issue.

**Comment by jmcnamara** [comment]
I've pushed a fix for this issue to the master branch. It will be in the next release.

**Comment by ncfernan** [comment]
Thank you, John. That was the best response for an issue that I've seen in a long time. Keep up the excellent work!

**Comment by jmcnamara** [comment]
Thanks. :-)
