### ISSUE TITLE
Regular font style in charts

### ISSUE THREAD

**Issue by RaFaeL-NN** [jmcnamara/libxlsxwriter#146]
Some chart elements, such as title name is bold by default on opening file in Excel. How to set it to regular style? Bold=0 don't set this

**Comment by jmcnamara** [comment]
Can you add a small compilable program the demonstrates the issue.

**Comment by RaFaeL-NN** [comment]
I don't know why, but it works then I set Bold to 2. OK.

**Comment by jmcnamara** [comment]
It would still be useful to see a compilable example that demonstrates the issue.

**Comment by RaFaeL-NN** [comment]
Sorry, I cannot, because I use library in binary form from other language

**Comment by jmcnamara** [comment]
Ok. But look at this from my side. I can only fix bugs that I can reproduce. If I can't reproduce an issue with a C program then it probably isn't an issue in theC library.

If there is a genuine issue in libxlsxwriter then you should be able to demonstrate it with a C program.

And I'm more than happy to fix those.

So, closing this.
