### ISSUE TITLE
Feature request: Plotarea options for Pie chart

### ISSUE THREAD

**Issue by RaFaeL-NN** [jmcnamara/libxlsxwriter#147]
No code for writing c:spPr in _chart_write_pie_plot_area. Why? I can set it in Excel runtime...
![piecolors](https://user-images.githubusercontent.com/34895749/36066170-964af0ca-0eb6-11e8-9953-aa0269720735.png)

Can you add this lines of code for pie and doughnut charts too?

**Comment by jmcnamara** [comment]
I’ll try. What is that feature called in English?

**Comment by RaFaeL-NN** [comment]
Format Plot Area
It's same with another type of charts, no differenсe. May be, just in size of area...

**Comment by RaFaeL-NN** [comment]
`/*
 * Write the <c:plotArea> element. Special handling for pie/doughnut.
 */
STATIC void
_chart_write_pie_plot_area(lxw_chart *self)
{
    lxw_xml_start_tag(self->file, "c:plotArea", NULL);

    /* Write the c:layout element. */
    _chart_write_layout(self);

    /* Write subclass chart type elements for primary and secondary axes. */
    self->write_chart_type(self);

    /* Write the c:spPr element for the plotarea formatting. */
    _chart_write_sp_pr(self, self->plotarea_line, self->plotarea_fill,
                       self->plotarea_pattern);

    lxw_xml_end_tag(self->file, "c:plotArea");
} `

It works

**Comment by jmcnamara** [comment]
Yes. That feature should be supported by default. I'll add it in a later release.

**Comment by RaFaeL-NN** [comment]
I think it's a bug. Based on docs for chart_plotarea_set_* functions, no exceptions for some type of charts

**Comment by jmcnamara** [comment]
It is a big of sorts. 

I deliberately left out support for it because I mistakenly thought that it wasn’t supported for those types of charts. 

I’ll add it back in an upcoming release once I add some test etc.

**Comment by jmcnamara** [comment]
Fixed on master. Thanks for the report. Closing.
