### ISSUE TITLE
Writing formulas on xlsx files

### ISSUE THREAD

**Issue by HenriqueMisael** [jmcnamara/libxlsxwriter#149]
In excel, 
**When you write** _it shows up in the cell_
**A2+A3** _A2+A3_
**=A2+A3** _the result of the sum_
**'=A2+A3** _=A2+A3_

Knowing that, I've tried to write "=A2+A3" using the write_string function, but it wrote just the formula, not showing up the result. Once I select the cell and press **ENTER**, however, the cell turned to the result of the formula I entered.

**Looking deep in the xlsx file I've figured out that**

- in x1/worksheets/worksheet_name.xml the cells have the tag `<c></c>`, with the attributes "`r`" for identification (A3, B6, etc).
- when I use write_string function, it writes on x1/sharedStrings.xml adding in the final of the list. The ordinal position of the string is wrote on x1/worksheets/worksheet_name.xml, in the tag `<v></v>` of the cell. For identify this is a reference for sharedStrings.xml and not the actually value of the cell, a attribute "t" of the cell it suppled with "s" (`<c r=X9 t="s"></c>`).
- when I write a formula (in excel), the tag seems standart, except for adding another tag into the cell tag: `<f></f>`, and the string equivalent to the formula is writen in it.
**Example:** if I wrote "=A2+A3" in the cell A1, the tag for it will be something like `<c r=A1><f>A2+A3</f><v>698</v></c>`, considering the result of the formula would be 698.

I have not found any method to write a formula using libxlsxwriter. It would be really useful (I thought I will found this pointed out in Issues, and not finding it suprised me).

**Comment by jmcnamara** [comment]
> I have not found any method to write a formula using libxlsxwriter. 

What about the `worksheet_write_formula()` function?: https://libxlsxwriter.github.io/worksheet_8h.html#ae57117f04c82bef29805ec3eabc219bb

**Comment by HenriqueMisael** [comment]
I searched in the examples, sorry for the bad reporting

**Comment by jmcnamara** [comment]
No problem. Closing.
