### ISSUE TITLE
Naming intervals

### ISSUE THREAD

**Issue by HenriqueMisael** [jmcnamara/libxlsxwriter#152]
Does this library have a function to name a interval/cell?
For example, in Excel, I can click on the box (left to the formula box) with the cell name (for example A4) and give it a name, and reference this cell with a name. Something like: I name B1 as "income", B2 as "taxes" and B3 as "profit". In the B1 and B2 I write 500 and 200. In the B3 (profit) I write "=income-taxes", and it returns the same as "=B1-B2".
![microsoft excel - pasta1](https://user-images.githubusercontent.com/17010656/37359997-cdc36454-26cd-11e8-933e-e19ad10c3841.jpg)
![microsoft excel - pasta1_2](https://user-images.githubusercontent.com/17010656/37360028-dde98624-26cd-11e8-9651-dad3c894de29.jpg)
![microsoft excel - pasta1_3](https://user-images.githubusercontent.com/17010656/37360061-ecb54148-26cd-11e8-93da-eb0827217e5a.jpg)
![microsoft excel - pasta1_4](https://user-images.githubusercontent.com/17010656/37360076-f4986f5c-26cd-11e8-918d-674562543ad3.jpg)

**Comment by jmcnamara** [comment]
Hi,

That is possible. It is called "defined names". See the following:

http://libxlsxwriter.github.io/workbook_8h.html#a442b4056e8d4debf56c07888f2a776f6

http://libxlsxwriter.github.io/defined_name_8c-example.html

John
