### ISSUE TITLE
CMake: doesn't enforce a unicode build for MSVC

### ISSUE THREAD

**Issue by RalfKubis** [jmcnamara/libxlsxwriter#153]
Apparently the library requires to be build with the symbol `_UNICODE` being defined.
Otherwise one gets defects like described in #104 and #148 or similar.

A potential fix would be to define this symbol in CMakeLists.txt.

**Comment by jmcnamara** [comment]
I made an attempt to try implement this via commandline switches to cmake. Unsuccessfully.

@Alexhuszagh Could you have a look at implementing this. It is catching a lot of Windows users using cmake.

**Comment by RalfKubis** [comment]
I'm on it. Just preparing a pull-request.
