### ISSUE TITLE
Issue with Installing on Visual Studio C++

### ISSUE THREAD

**Issue by r-chambers** [jmcnamara/libxlsxwriter#158]
Hello,

I am using the libxlsxwriter in a Visual Studio C++ project and have followed the instructions in the MSVCLibXlsxWriter project, building the library and then using it to build ExampleExe. However, when I do this, ExampleExe does not run: I get the error "The Application was unable to start correctly (0xc000007b)." I have looked this error up and it seems it might be caused by outdated libraries or by mismatches between 32-bit and 64-bit, though it is probably the former in this case.

I am using Visual Studio Community 2017 with v141 build tools, Windows 10 x64, and libxlsxwriter 0.3.8. 

Thank you very much for your time, and have a wonderful day.

**Comment by jmcnamara** [comment]
Hi,

Can you check that you set and use the 64 bit targets at all the compilation stages and that you copied the dlls from the 64bit folders? Also, check if the supplied zlib dll is 64 bit?

John

**Comment by r-chambers** [comment]
Well, I feel so stupid now! Thank you so much. I was accidentally copying the Zlib.dll and Zlib.lib from the wrong folder.

This fixed it! Thank you again, and I'm sorry for the silly Issue. 

Have a good day!

**Comment by jmcnamara** [comment]
No problem. Closing.
