### ISSUE TITLE
Feature Request: Chart Sizing options

### ISSUE THREAD

**Issue by TitanicHispanic** [jmcnamara/libxlsxwriter#160]
While using **scale** does indeed work, it is a rather abstract way to measure or set a chart's dimensions.

With that in mind, I'm requesting the added options of **chart_w** & **chart_h** to **lxw_image_options**, or the introduction of **lxw_chart_options** with chart configuration options.

Other, slower libraries do offer options, ranging from cellTo & cellFrom or x/y pairs. **libxlsxwriter** outperforms the other libraries I evaluated, so I'm hopeful this can happen.

**Comment by jmcnamara** [comment]
> I'm hopeful this can happen.

It won't happen.

Libxlsxwriter is a port of [XlsxWriter](https://github.com/jmcnamara/XlsxWriter) and [Excel::Writer::XLSX](https://github.com/jmcnamara/excel-writer-xlsx) all of which have the same interface. 

Chart sizes in Excel are a fixed size in pixels, row heights and column widths are fixed sizes in pixels (unless the user changes them). So it is possible for an end-user application to calculate the required scale to get a chart to span a user-defined number of cells, without support from the library.
