### ISSUE TITLE
File size is very large comparing to OpenXML SDK generated

### ISSUE THREAD

**Issue by igorko** [jmcnamara/libxlsxwriter#165]
When using OpenXML SDK for generating xlsx, size is much smaller even when using 9 compression level in libxlsxwriter. Sheet.xml document size differs very much.
 - 100 000 rows on 230 columns document. (7.5MB vs 2.4MB)
 - 400 000 rows on 230 columns document. (327MB vs 107MB) Also such large file generated with libxlsxwriter  is corrupted

**Comment by jmcnamara** [comment]
> When using OpenXML SDK for generating xlsx, size is much smaller even when using 9 compression level in libxlsxwriter.

It is a design goal of libxlsxwriter that it replicates the OpenXML variant used by Excel to ensure compatibility and to allow testing against files created in Excel.

In general libxlsxwriter files are smaller than equivalent Excel files with the default zlib compression level.

**Comment by jmcnamara** [comment]
> Also such large file generated with libxlsxwriter is corrupted

I've had no reports of that. And when I run the following test program it works fine (although it is slow to load in Excel):

```C
#include "xlsxwriter.h"

int main() {

    lxw_workbook  *workbook  = workbook_new("test.xlsx");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);
    int row;
    int col;

    for (row = 0; row < 400000; row++)
        for (col = 0; col < 230; col++)
            worksheet_write_string(worksheet, row, col, "Hello", NULL);

    workbook_close(workbook);

    return 0;
}
```

Here is the output file loaded in Excel.
![aa_image](https://user-images.githubusercontent.com/94267/39360807-8e434d9a-4a17-11e8-9420-c7ad44781df9.png)

If you have an example program that produces a corrupt file that Excel can't read that open up a new bug report issue.

BTW, the file produces by the above program is ~187MB. The same file saved by Excel is ~243MB. 

Closing.
