### ISSUE TITLE
Please honours library layout

### ISSUE THREAD

**Issue by remicollet** [jmcnamara/libxlsxwriter#166]
For now, installation layout is hardcoded

        LIBRARY DESTINATION lib
        ARCHIVE DESTINATION lib

Most Linux distributions use a multi-arch layout (/usr/lib64 in RPM distro, /usr/lib/x86_64... on .deb distro, etc)

Using `${CMAKE_INSTALL_LIBDIR}` seems a common practice

**Comment by jmcnamara** [comment]
@Alexhuszagh Can you take a look at this.

Or @remicollet can you submit a Pull Request.

**Comment by Alexhuszagh** [comment]
That should be pretty trivial to fix. We currently handle this for MSVC, so it seems natural we should support this for multi-arch Linux distros as well.

I can support a PR later today.

**Comment by remicollet** [comment]
@Alexhuszagh see pr #170
