### ISSUE TITLE
No soname for ABI tracking

### ISSUE THREAD

**Issue by remicollet** [jmcnamara/libxlsxwriter#167]
This library doesn't set any _soname_, so it is hard to track ABI compatibility

Expected, something like

    /usr/lib64/libxlswriter.so -> libxlswriter.so.1
    /usr/lib64/libxlswriter.so.1 -> libxlswriter.so.1.0
    /usr/lib64/libxlswriter.so.1.0

This means incompatible changes have to bump the soname, new symbols have to bump the minor version.

This a common good practice, respected by nearly all libraries.

**Comment by jmcnamara** [comment]
Good suggestion. I'll look into adding that.

**Comment by jmcnamara** [comment]
I still have this at the back of my mind. However, I think there is still too much flux/development going on in libxlsxwriter to try stabilise the ABI or use semantic versioning.

**Comment by jmcnamara** [comment]
Same comment as above. Libxlsxwriter still has too much change to try stabilise the ABI. Closing for now.

**Comment by imaiguo** [comment]
need soname urgently

**Comment by jmcnamara** [comment]
Ok. Re-opening this issue.

**Comment by jmcnamara** [comment]
Closing in favour of #340.
