### ISSUE TITLE
About the Known Issues and Bugs : Content is Unreadable. Open and Repair (with not repair at all)

### ISSUE THREAD

**Issue by Nipou** [jmcnamara/libxlsxwriter#172]
Some structures require minimal initialization such as:
memset(&xline, 0, sizeof(lxw_chart_line));
memset(&yline, 0, sizeof(lxw_chart_line));

Others specific values like: lxw_chart_font need faceName != “” and a bad charset cause fatal error.

In C ++ a structure can have a constructor, this would always generate valid empty structures.

If you absolutely want C code, you would need initialization functions like
**init_lxw_chart_font** (lxw_chart_font *)
**init_lxw_chart_line** (lxw_chart_line *)

It would also be useful to have validation functions such as:
bool **validate_lxw_chart_font** (lxw_chart_font *)
bool **validate_lxw_chart_line** (lxw_chart_line *)

Who could correct a badly filled structure and return false in case of correction. Or at least false in case of error.

**Comment by jmcnamara** [comment]
At some stage I may add functions that return initialised versions of structs used as parameters. But for now just initialise any structs that you are going to pass to libxlsxwriter functions:

```C
lxw_chart_line line = {0); 

/* Or with  member initialisation. */
lxw_chart_line line = {.none      = LXW_FALSE,
                       .color     = LXW_COLOR_BLACK,
                       .width     = 2.25,
                       .dash_type = LXW_CHART_LINE_DASH_SOLID};
```
