### ISSUE TITLE
Corrupt output filename on windows

### ISSUE THREAD

**Issue by dirkvdb** [jmcnamara/libxlsxwriter#176]
When I write a workbook to disk the output filename is corrupt. In my case a file with the name "C" is output.

Cause:
In packager.c:_open_zipfile_win32 the filename is converted to wchar_t and passed as a void pointer to zipOpen2_64.

Eventually in iowion32.c:win32_open64_file_func this void pointer is passed to CreateFile by casting it to LPCSTR, since my program is not compiled with unicode but multibyte character set, this is an invalid cast and results in a corrupt filename.

**Comment by jmcnamara** [comment]
Can you show the steps to reproduce this.

**Comment by jmcnamara** [comment]
Open a Windows CMD or Command Window and set up your MSVC environment, if required.

Then create a work directory and and an install directory that the include and library files will be installed to.

```
set    WORK_DIR=C:/Users/Molly/tmp
set INSTALL_DIR=C:/Users/Molly/tmp/install_dir

```

Build the Zlib library:

```
cd %WORK_DIR%

git clone https://github.com/madler/zlib.git
cd zlib
mkdir build
cd    build

cmake .. -G "Visual Studio 14 Win64" -DCMAKE_INSTALL_PREFIX:PATH="%INSTALL_DIR%/zlib"

cmake --build . --config Release --target install  
```

Build the xlsxwriter library :

```
cd %WORK_DIR%

git clone https://github.com/jmcnamara/libxlsxwriter.git
cd libxlsxwriter
mkdir build
cd    build

cmake .. -G "Visual Studio 14 Win64" -DCMAKE_INSTALL_PREFIX:PATH="%INSTALL_DIR%/libxlsxwriter" -DZLIB_ROOT:STRING="%INSTALL_DIR%/zlib"

cmake --build . --config Release --target install  
```

Create a new Win32 Console application in Visual Studio:

```
File
  -> New 
    -> Project

Visual C++ 
  -> Win32 
    -> Win32 Console Application
```

Change the ARCH to "x64" (or to match the parameter to cmake).

Replace the empty main with a libxlsxwriter example, make sure to maintain the "stdafx.h" include:

```C
#include "stdafx.h"


#include "xlsxwriter.h"

int main() {

	lxw_workbook  *workbook = workbook_new("hello_world.xlsx");
	lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);

	worksheet_write_string(worksheet, 0, 0, "Hello", NULL);
	worksheet_write_number(worksheet, 1, 0, 123, NULL);

	workbook_close(workbook);

	return 0;
}
```

Edit the application properties:

```
Project 
  -> ConsoleApplication Properties
```

Set the libxlsxwriter include path to match the path used above:

```
Configuration Properties 
  -> C/C++ 
    -> General 
      -> Additional Include Directories

Set it to the following (or similar path used above):
      
C:\Users\Molly\tmp\install_dir\libxlsxwriter\include
```      

Set the linker directories to match the path created above:
```      
Configuration Properties       
  -> Linker
    -> General
      -> Additional Library Directories

Add the following (or similar paths used above):
      
C:\Users\Molly\tmp\install_dir\libxlsxwriter\lib\x64\Release
C:\Users\Molly\tmp\install_dir\zlib\lib
```

Set the linker additional libraries to match the zlib and xlsxwriter libs created above:

```      
Configuration Properties       
  -> Linker
     -> Input
        -> Additional Dependencies

Add the following:
        
xlsxwriter.lib
zlib.lib
```       

Build the solution and run the output executable. It should create a hello_world.xlsx file in the same directory you ran it from.

**Comment by dirkvdb** [comment]
I performed very similar steps, as soon as I put a space in the filename the file was not created anymore. I'm pretty sure projects generated with the "Visual Studio 14 Win64" generator default to multi byte instead of unicode.

**Comment by dirkvdb** [comment]
In my test I was still using release 0.7.6.
It appears to be fixed in master by this commit:
https://github.com/jmcnamara/libxlsxwriter/commit/3b25ad611b5e7ef6e367debb90f66b4b78c86380#diff-ea69bda3932b6e3711b5bee1a83d7ed5

**Comment by jmcnamara** [comment]
> In my test I was still using release 0.7.6.
> It appears to be fixed in master by this commit:

This is why I asked for the steps to reproduce the issue and why I didn't mention this fix when you indicated that you were using a git clone.

Nevertheless, this fix should be packaged up into a release. I've haven't had a chance to do that recently but I'll try get to it on the weekend.

Thanks for following up. Closing this issue.
