### ISSUE TITLE
Question: State if workbook_close fails

### ISSUE THREAD

**Issue by petricf** [jmcnamara/libxlsxwriter#179]
Given the case the call to workbook_close fails.

Is the pointer to the workbook still valid and useable ?

Or is it cleaned up as documented in the case of a successful outcome ?

**Comment by jmcnamara** [comment]
> Or is it cleaned up as documented in the case of a successful outcome ?

It is cleaned up: https://github.com/jmcnamara/libxlsxwriter/blob/master/src/workbook.c#L1588
