### ISSUE TITLE
Feature request: Change format of a cell after it contens have been set

### ISSUE THREAD

**Issue by petricf** [jmcnamara/libxlsxwriter#181]
Sometimes it cam be necesary to modify a format or particular format item of a cell after it has been set by (for example) worksheet_write_string.
A reason may be also to split contents from formatting (maybe design rule) like done for html and css.

A sample workflow could be:

>lxw_format * format = worksheet_get_format ("row", "column");
>format->setAlign (...);
>worksheet_set_format ("row", "column", format);

An other solution could be to define a lxw_cell structure that would result in this workflow:

>lxw_cell * cell = worksheet_get_cell ("row", "column");
>cell->format->setAlign (...);

**Comment by jmcnamara** [comment]
Unfortunately, that isn't something that will be supported. It is a somewhat frequently requested feature in the Python and Perl versions of the library as well but it isn't implemented there either.
