### ISSUE TITLE
Question: Change row/column width without changing format

### ISSUE THREAD

**Issue by petricf** [jmcnamara/libxlsxwriter#182]
The functions worksheet_set_row and worksheet_set_column allow to change the width and height of the rows/columns.

But they always come with a lxw_format parameter.

The doc is not clear - passing NULL as lxw_format changes the formatting on all rows/columns to default ?
Or does it leave the formatting info as is ?

If the former applies - how to change the row/column size, but let the formatting info unchanged ?

**Comment by jmcnamara** [comment]
A cell format will override a column or row format.

**Comment by petricf** [comment]
But if the worksheet_set_row call comes AFTER a worksheet_write_* - which format parameter takes precedence ?
