### ISSUE TITLE
Cannot write to previous row if constant_memory mode is enabled.

### ISSUE THREAD

**Issue by igorko** [jmcnamara/libxlsxwriter#183]
If constant_memory mode is enabled then writing to row e.g. 0 will produce empty cell, if there was already writing to row e.g. 1.

**Comment by jmcnamara** [comment]
That is the documented behavior: http://libxlsxwriter.github.io/working_with_memory.html

**Comment by igorko** [comment]
Maybe it can be improved so flushing happens only after adding n-th row?

**Comment by jmcnamara** [comment]
> Maybe it can be improved so flushing happens only after adding n-th row?

That is something that could be handled in the end-user application with some simple buffering.
