### ISSUE TITLE
Question: set page number

### ISSUE THREAD

**Issue by petricf** [jmcnamara/libxlsxwriter#184]
I have multiple sheets in a workbook. The first sheet is a intro sheet. From second sheet onwards i set a footer displaying the page number.
I want the second sheet start its page numbering again at 1 when printing.

Can this be done using libxlsxwriter ?

**Comment by jmcnamara** [comment]
Is that possible in Excel? If so how do you do it?

**Comment by petricf** [comment]
In LibreOffice 6.x: Menu Format -> Page, Tab Table, Item "First pagenumber" (translated from german)
Excel (> 2010): See guide at [this location](https://www.extendoffice.com/documents/excel/2338-excel-restart-page-numbering.html)
Excel 2010: See guide at [this location](http://blogmines.com/blog/how-to-change-starting-page-number-in-excel-2010/)

**Comment by jmcnamara** [comment]
The parameter can be set in libxlsxwriter using the [worksheet_set_start_page()](https://libxlsxwriter.github.io/worksheet_8h.html#a817235e5ce7b1ea030bedd86ddbb9844) function.

However, I don't think that does what you expect it to do. It just sets the first page that will be printed.

**Comment by jmcnamara** [comment]
Any update on this?

**Comment by petricf** [comment]
Actually tested it. worksheet_set_start_page indeed sets the starting page number used when the page numbers are assigned during printing process.
The current doc of this function seems misleading. I got the impression this function for example skips the first two pages when set to 3.
But the fact is (under LibreOffice) it prints still all pages.
My suggestion is to update the doc to clarify this.

For me this question is hereby solved.

**Comment by liufeijin** [comment]
>2010  excel
in each sheet we can set the any start number by "Click Page Layout > Page Setup", the start number for each sheet is independent, we can select a sheet and set the any start number.
But the total pages in footer is counting for whole workbook.

**Comment by jmcnamara** [comment]
@liufeijin this feature request is closed. If you have an additional feature request then please start a new issue.

**Comment by jmcnamara** [comment]
I've made the docs (hopefully) a bit clearer for this function. Closing.
