### ISSUE TITLE
Question: R1C1 reference style

### ISSUE THREAD

**Issue by almos** [jmcnamara/libxlsxwriter#185]
Have a need to write formulas in R1C1 reference style.
Is it possible to enable R1C1 reference style for workbook/worksheet and use for formulas?
Thank you

**Comment by jmcnamara** [comment]
Hi,

This is something that is mentioned in the XlsxWriter [docs](https://xlsxwriter.readthedocs.io/working_with_cell_notation.html) but not in the libxlsxwriter docs. I should fix that.

Basically, R1C1 isn't supported and it is unlikely that it will be. The main issue is that Excel doesn't store the formulas in R1C1 format. If a user writes a formula in cell B5 like`=R[-3]C+R[-2]C[4]` it is actually stored in the file as `=B2+F3`.

This means that an xlsx file writer, like libxlsxwriter, would have to convert all formulas from R1C1 to A1, which would mean parsing and converting all formulas. That isn't practical to implement.

So this won't be implemented. Sorry.

John
