### ISSUE TITLE
Align X Axis labels

### ISSUE THREAD

**Issue by j15e** [jmcnamara/libxlsxwriter#186]
It looks like axis labels alignement (`c:lblAlgn`) is hardcoded to `ctr` (center). 

I would like to know if there is a way to change this property with the current library that I am not aware of? Or it would require a new feature on the chart writer?

Here are the revelant parts :

1 - An axis is created : 
https://github.com/jmcnamara/libxlsxwriter/blob/b616fb59ffe0268b1ee0cecf822bf8ed45cf4f30/src/chart.c#L4028-L4032

2 - A `c:lblAlgn` element is added : 
https://github.com/jmcnamara/libxlsxwriter/blob/b616fb59ffe0268b1ee0cecf822bf8ed45cf4f30/src/chart.c#L4093-L4094

3 - Element is added with `ctr` value : 
https://github.com/jmcnamara/libxlsxwriter/blob/b616fb59ffe0268b1ee0cecf822bf8ed45cf4f30/src/chart.c#L3204-L3215

PS I have been using your library with https://github.com/Paxa/fast_excel, I must say a big thanks, this is pretty well done!

**Comment by jmcnamara** [comment]
That internal property may not be what you think it is. 

What specific feature in Excel do you wish to change.

**Comment by j15e** [comment]
The alignment of labels on the X axis like this : 
![unnamed-7](https://user-images.githubusercontent.com/143380/41441556-1d4c27d2-7001-11e8-8dc8-f804023cb1cc.png)

**Comment by j15e** [comment]
We want to do this to align the labels when creating an histogram, to make it clear the label is for the end of each histogram bucket (ex. the last column represent >725 to 750, not 750 to 775).

**Comment by jmcnamara** [comment]
Ok. Got it.

That isn't currently supported. I'll need to put it into the Python and Perl versions first and then port it across. Your patch looks okay though so you can use that in the meantime.

**Comment by j15e** [comment]
Thanks, I hope my patch help implementing Python and Perl versions.

**Comment by jmcnamara** [comment]
Added in version 0.7.9.

**Comment by jmcnamara** [comment]
P.S. I changed the function name and enums slightly to make them consistent (or equally inconsistent) with existing code. See the changes in f7f32de
