### ISSUE TITLE
Bubble Chart?

### ISSUE THREAD

**Issue by TitanicHispanic** [jmcnamara/libxlsxwriter#190]
A standard Excel chart type is a sub-type of Scatter, which is the **Bubble** chart. I don't see any documentation or functions in my IDE that pertain to that chart type.

How can I create a **Bubble** chart?

**Comment by jmcnamara** [comment]
> How can I create a Bubble chart?

That isn't currently possible. You can add a +1 to the Python feature request. It will get added to the C library once it is added there: https://github.com/jmcnamara/XlsxWriter/issues/347
