### ISSUE TITLE
Combo Chart (e.g. Column Chart w/Line series)

### ISSUE THREAD

**Issue by TitanicHispanic** [jmcnamara/libxlsxwriter#191]
A popular chart in Market Research is a Column chart with multiple series, some of which are of a different chart type (e.g. a multi-series Column Chart with 1+ Line Chart series).

I believe I'd read a note somewhere that you acknowledge this outage. Is there an update?

**Comment by jmcnamara** [comment]
This is a duplicate of #89. There is currently no update on this.
