### ISSUE TITLE
Exceeding Limit on URLs

### ISSUE THREAD

**Issue by iamtheschmitzer** [jmcnamara/libxlsxwriter#193]
I am exceeding the limit on URLs.  I can see where this is enforced, but suprisingly, I cannot find an actual fixed-size array of URLs.  Instead it appears URLs are inserted into the list of cells.

Does anyone know why the number of URLs is constrained, or where that array is?

**Comment by jmcnamara** [comment]
> Does anyone know why the number of URLs is constrained

The number of unique, non-contiguous, URLs is constrained by Excel to 65,530 per worksheet. After that it doesn't accept any more URLs. Excel supports an optimization for contiguous URLs, i.e., in adjoining cells but that isn't supported by libxlsxwriter.

**Comment by iamtheschmitzer** [comment]
Okay, thanks
