### ISSUE TITLE
Feature request: write workbook to buffer

### ISSUE THREAD

**Issue by cruisercoder** [jmcnamara/libxlsxwriter#196]
Are there plans to implement a write workbook to buffer option?

**Comment by cruisercoder** [comment]
My use case is a REST endpoint that returns workbooks.  That's what I plan to do now is to write to a temp file and then write that out or save to a data store.  In a high volume setting, it would be a bit simpler and faster to just have access to the image.  It might be good for testing as well as you could more simply pair it with a reader to validate the sheet.  I would imagine that it should be pretty straightforward to abstract the writing calls for either a file or buffer.

**Comment by cruisercoder** [comment]
There's also the issue of security.  We have sensitive information on the sheets the use of files creates another security vector that has to be accounted for (using encrypted mounts for example).  Disk space and name uniqueness also have to be handled correctly.

**Comment by jmcnamara** [comment]
I'm somewhat open to the first part of this, writing the xlsx file to a buffer. I'd accept a PR for it but I'm not currently motivated to do it myself and this hasn't been a frequently requested feature, to date. I'll leave this open as a feature request to see if it has wider interest.

However, the second part, replacing the tmp files with in memory files would be harder to do portably. I should be just a matter of replacing [`lxw_tmpfile()`](https://github.com/jmcnamara/libxlsxwriter/blob/master/src/utility.c#L520) with a memory buffer equivalent but I'm not aware of C option that would work on OS X/Linux/Windows. `fmemopen()` might or might not work.

For specific use cases it might not be too hard. In particular if the end user is using C++ or just one OS.

**Comment by cruisercoder** [comment]
Thanks.  I will size up the work when I get some time.

**Comment by mewalig** [comment]
Not sure how that translates for the other languages but for C, could this be fairly straightforward to just compile with your own custom functions for fopen, fread, fwrite, ftell, fprintf and fclose?

**Comment by jmcnamara** [comment]
Closing this since I don't see any ANSI-C OS portable way of doing this.

**Comment by mohd-akram** [comment]
[fmem](https://github.com/Snaipe/fmem) is a possible solution to this.

**Comment by mewalig** [comment]
@jmcnamara Out of curiosity, what ANSI-C portability issues would this have raised? Not trying to change your mind, just wanting to learn

**Comment by jmcnamara** [comment]
@mewalig I was referring to `fmemopen()` style functions which afaik are not ANSI-C and which don't work on Windows.

But not impossible as you say and @mohd-akram points out the fmem library above. He also added support for writing a workbook to a buffer under the existing `USE_FMEMOPEN` define in PR #382. So this feature request has actually been implemented in version 1.1.5.
