### ISSUE TITLE
Feature request: Add option to close worksheets without closing workbook

### ISSUE THREAD

**Issue by LaurinStrelow** [jmcnamara/libxlsxwriter#2]
Hi,

it would be great to have the possibility to close worksheets. This avoids to reach the file limit with arbitrary large workbooks.

Thanks!

**Comment by LaurinStrelow** [comment]
Hi, 

is there something new on this? I get complaints from users, who run into this issue (Anything else is working great!). Are you planning to fix this soon? If not i can try to find a solution.

**Comment by jmcnamara** [comment]
Hi Laurin,

If there isn't an update to this issue then there hasn't been anything new.

To be honest this is a low priority issue for me. I find it hard to see why people need to produce workbooks with 1000+ worksheets (or whatever their ulimit is) or that they can't increase the ulimit if they do.

So if you can find a solution, such as increasing the system ulimit, then please do.

John

**Comment by wangjinbao123** [comment]
hi,can you help me to use it in ios ?

**Comment by jmcnamara** [comment]
@wangjinbao123 You shouldn't ask a new question on an older issue. If you have a new question please open a new issue. See the following in relation to your question [Building libxlsxwriter for iOS](http://kvurd.com/blog/building-libxlsxwriter-for-ios/).

**Comment by LaurinStrelow** [comment]
Hi there,

@jmcnamara I fully understand you. The worksheet is generated automatically from an input set and therefore the limit can be reached easier. In the meantime i have developed a fix for this problem, wich is working good so far. However getting the temp directory relies on the objc runtime and therefore this is no general solution. If you are interested i can open a pull request (This can take a month since i am busy atm).

@wangjinbao123 You better open a new issue where we can discuss the problem and possible solutions.

**Comment by jmcnamara** [comment]
Closing as can't/won't fix. It can be worked around on some systems by using the `USE_MEM_FILE` compilation option.
