### ISSUE TITLE
how  to insert a picture to a shape?

### ISSUE THREAD

**Issue by liufeijin** [jmcnamara/libxlsxwriter#201]
some times, we put a shape in excel because it can be put any place and don't be limited start from cell.
and put a picture in a shape, the picture can be auto fitted in the shape.

**Comment by jmcnamara** [comment]
Hi,

That isn't possible  with libxlsxwriter.

However, you can resize and reposition an image using `worksheet_insert_image_opt()`: https://libxlsxwriter.github.io/images_8c-example.html#a11

John
