### ISSUE TITLE
how to open a exist excel ? I only found the create a new excel

### ISSUE THREAD

**Issue by liufeijin** [jmcnamara/libxlsxwriter#202]
lxw_workbook  *workbook  = new_workbook
 lxw_workbook  *workbook  = workbook_new
 
have no open ?

**Comment by RaFaeL-NN** [comment]
https://libxlsxwriter.github.io/faq.html

**Comment by jmcnamara** [comment]
That features sn't supported.

Libxlsxwriter can only create new files.

**Comment by drescherjm** [comment]
It would be a tremendous effort to do so. Way more than a single person can do in a reasonable time frame.
