### ISSUE TITLE
Series name is ignored for chart type LXW_CHART_SCATTER

### ISSUE THREAD

**Issue by saedelman** [jmcnamara/libxlsxwriter#204]
The chart_series_set_name() call does nothing when the chart type is set to LXW_CHART_SCATTER or LXW_CHART_SCATTER_SMOOTH. Excel shows "Series 1", "Series 2", etc. instead of the defined name.

Looking at chart.c, the function call _chart_write_xcal_ser(...) does not call _chart_write_series_name(...). Once this is added (after _chart_write_order(..)), Excel properly reflects the name identified by the chart_series_set_name() user call.

**Comment by saedelman** [comment]
Sure, but just compare the _chart_write_xval_ser(...) and _chart_write_ser(...) functions, the latter function is called for everything other than scatter graphs and the _chart_write_series_name(..) is included there. It should be immediately obvious that it is missing from _chart_write_xval_ser(..) call.

**Comment by jmcnamara** [comment]
> It should be immediately obvious that it is missing from _chart_write_xval_ser(..) call.

Maybe or maybe not. I prefer to start with a sample program to make sure everyone is on the same page.

For example I created this test case:

```C

#include "xlsxwriter.h"

int main() {

    lxw_workbook  *workbook  = new_workbook("test_chart_scatter.xlsx");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);
    lxw_chart     *chart     = workbook_add_chart(workbook, LXW_CHART_SCATTER);

    uint8_t data[5][3] = {
        {1, 2,  3},
        {2, 4,  6},
        {3, 6,  9},
        {4, 8,  12},
        {5, 10, 15}
    };

    int row, col;
    for (row = 0; row < 5; row++)
        for (col = 0; col < 3; col++)
            worksheet_write_number(worksheet, row, col, data[row][col], NULL);

    lxw_chart_series *series1 = chart_add_series(chart,
         "=Sheet1!$A$1:$A$5",
         "=Sheet1!$B$1:$B$5"
    );

    lxw_chart_series *series2 = chart_add_series(chart,
         "=Sheet1!$A$1:$A$5",
         "=Sheet1!$C$1:$C$5"
    );

    chart_series_set_name(series1, "Apple");
    chart_series_set_name(series2, "Pear");
    
    worksheet_insert_chart(worksheet, CELL("D4"), chart);

    return workbook_close(workbook);
}

```

Which creates this output:

![aa_image](https://user-images.githubusercontent.com/94267/48271514-6a70a680-e434-11e8-989f-53d08bdb2210.png)

|

Which looks okay. Is this the type of scenario that you are talking about?

**Comment by saedelman** [comment]
It looks like I may have an older library. My output shows "Series 1" for "Apple" and "Series 2" for Pear.

**Comment by jmcnamara** [comment]
Ok to close then?

**Comment by saedelman** [comment]
Let me try it with the latest library for good measure and report back.

**Comment by jmcnamara** [comment]
Closing. If you isolate an issue you can open another issue with an example.
