### ISSUE TITLE
pkgsrc package

### ISSUE THREAD

**Issue by sjmulder** [jmcnamara/libxlsxwriter#205]
I've created a [pkgsrc](http://pkgsrc.org/) package for libxlsxwriter. pkgsrc is the default packaging solution for NetBSD, MINIX and others but can be used on most Unices including macOS and Linux.

The [WIP](http://pkgsrc.org/wip) package can be found here: https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=tree;f=libxlsxwriter.

I'll update this issue as the package goes through review and into the main tree.

**Comment by jmcnamara** [comment]
That's great. Thanks.

**Comment by sjmulder** [comment]
Forget to update this, 1.8.4 is in and 1.8.5 will be soon.
