### ISSUE TITLE
Hardcoded -install_name prefix on macOS

### ISSUE THREAD

**Issue by sjmulder** [jmcnamara/libxlsxwriter#209]
(Relates to #205)

`src/Makefile` has this bit:

    # Change make options on OS X.
    ifeq ($(UNAME), Darwin)
    LIBXLSXWRITER_SO = libxlsxwriter.dylib
    SOFLAGS = -dynamiclib $(FPIC) -install_name /usr/lib/$(LIBXLSXWRITER_SO)
    endif

This is incorrect when building with another prefix. pkgsrc happens to have a check for this and signals an error:

    => Checking for missing run-time search paths in libxlsxwriter-0.8.4
    ERROR: lib/libxlsxwriter.dylib: missing library: /usr/lib/libxlsxwriter.dylib

Should be `/opt/pkg/lib/libxlsxwriter.dylib` in my case.

I'd say this should be changed to `$(PREFIX)/lib/$(LIBXLSXWRITER_SO)` but I'm not familiar with macOS' dynamic linker.

**Comment by jmcnamara** [comment]
Closing. Superseded by #216
