### ISSUE TITLE
undefined reference to `_imp____acrt_iob_func'

### ISSUE THREAD

**Issue by iw2lsi** [jmcnamara/libxlsxwriter#212]
Hi all,

  I'm getting a strange error while linking my Qt5.10.1 app with the latest libxlsxwriter: "undefined reference to `_imp____acrt_iob_func'"...

I'm using msys2-x86_64-20180531.exe from https://www.msys2.org

 any ideas ?

   thanks a lot,

              Giampaolo

**Comment by jmcnamara** [comment]
Hi,

That function isn't part of libxlswriter so it is more likely to be an issue with gcc or the glibc libraries. A quick google shows some issues like this: https://www.google.com/search?client=firefox-b&ei=Nb4XXJqrF7uS1fAPnYmUqAI&q=undefined+reference+to+_imp____acrt_iob_func&oq=undefined+reference+to+_imp____acrt_iob_func&gs_l=psy-ab.3..0i5i10i30.3391.3391..3648...0.0..0.144.144.0j1......0....1..gws-wiz.......0i71.9gLf1D9fEqI

Either way it isn't a libxlsxwriter issue so I will close this.

John
