### ISSUE TITLE
Missing changelog items for 1.8.5

### ISSUE THREAD

**Issue by sjmulder** [jmcnamara/libxlsxwriter#215]
Changelog on [1.8.5 release page](https://github.com/jmcnamara/libxlsxwriter/releases/tag/RELEASE_0.8.5):

- Fix compile-time warnings with strict prototypes enabled.

But these are in too:

- Additional formatting tests.
- Make py.test name configurable

Maybe those should be added to the release notes?

**Comment by jmcnamara** [comment]
Hi,

The additional tests weren't worth mentioning. It was a compatibility test for an issue with the Python and Perl module that wasn't in the C version.

I should have added the py.test fix. I've updated it now and also added it to the docs.

John

**Comment by sjmulder** [comment]
Cheers 👍
