### ISSUE TITLE
I can't write the transparency of the fgcolor 

### ISSUE THREAD

**Issue by yqy159** [jmcnamara/libxlsxwriter#220]

**Comment by jmcnamara** [comment]
As far as I know Excel doesn't support transparency for cell fill colors. Is that correct?

**Comment by yqy159** [comment]
i am sorry ，I mean set up tint，eg:

**Comment by yqy159** [comment]
i am sorry ，I mean set up tint，eg:

<fill>
      <patternFill patternType="solid">
        <fgColor theme="9" tint="0.39997558519241921"/>
        <bgColor indexed="64"/>
      </patternFill>
    </fill>

**Comment by yqy159** [comment]
i am sorry ，I mean set up tint， I don't know what this tint means how do I set it up

**Comment by yqy159** [comment]
<fill>
      <patternFill patternType="solid">
        <fgColor theme="9" tint="0.39997558519241921"/>
        <bgColor indexed="64"/>
      </patternFill>
    </fill>

**Comment by yqy159** [comment]
`   <fill>
      <patternFill patternType="solid">
        <fgColor theme="9" tint="0.39997558519241921"/>
        <bgColor indexed="64"/>
      </patternFill>
    </fill>`

**Comment by jmcnamara** [comment]
> I mean set up tint

Unfortunately that isn't supported and is unlikely to be in the future.
