### ISSUE TITLE
Consider a vcpkg build option.

### ISSUE THREAD

**Issue by bangusi** [jmcnamara/libxlsxwriter#222]
vcpkg makes it much easier to acquires libraries on Windows especially
Made a request here  https://github.com/Microsoft/vcpkg/issues/6019

**Comment by bangusi** [comment]
Was the effort to create a port successful?

**Comment by jmcnamara** [comment]
> Was the effort to create a port successful?

The effort is ongoing. I can't give any estimate for when it will be available. You will see updates in this, or the other issue, when there are some updates.

**Comment by jmcnamara** [comment]
A libxlswriter port has been added by the vcpkg team.

Closing.
