### ISSUE TITLE
Worksheet names ending in single-quote aren't raising an error

### ISSUE THREAD

**Issue by mewalig** [jmcnamara/libxlsxwriter#223]
If a worksheet is created using a name where the final char is a single-quote, libxlsxwriter should raise an error, but does not. The below screenshots show

1. Excel complaining if you try to do this by renaming a worksheet manually and 
2. Excel not complaining using the same name, if the final char is not a single-quote

The screenshots use a name of 31 chars but it appears that the issue exists whenever the name ends in single quote

![image](https://user-images.githubusercontent.com/8260442/55894365-f9baeb00-5b87-11e9-967f-3a33c580359b.png)

![image](https://user-images.githubusercontent.com/8260442/55894668-8665a900-5b88-11e9-8d5f-b045f5c45786.png)

**Comment by jmcnamara** [comment]
Thanks. That is a bug.

**Comment by RaFaeL-NN** [comment]
Single-quote cannot be the first char too

**Comment by jmcnamara** [comment]
For the record the limitations on worksheet naming are given [here](https://support.office.com/en-ie/article/rename-a-worksheet-3f1f7148-ee83-404d-8ef0-9ff99fbad1f9):

> **Important: Worksheet names cannot:**
>
> * Be blank .
> 
> * Contain more than 31 characters.
>
> * Contain any of the following characters: / \ ? * : [ ]
>
> * For example, 02/17/2016 would not be a valid worksheet name, but 02-17-2016 would work fine.
>
> * Begin or end with an apostrophe ('), but they can be used in between text or numbers in a name.
>
> * Be named "History". This is a reserved word Excel uses internally.

**Comment by jmcnamara** [comment]
Fixed on master. The function now returns `LXW_ERROR_INVALID_SHEETNAME_CHARACTER` if the worksheet name starts on ends with an apostrophe.

**Comment by jmcnamara** [comment]
Changed the function to return an error specific code: `LXW_ERROR_SHEETNAME_START_END_APOSTROPHE`.
