### ISSUE TITLE
ZIP errors are not specified

### ISSUE THREAD

**Issue by evanmiller** [jmcnamara/libxlsxwriter#227]
I am getting an error when creating a large XLSX file (2,000+ columns, 100,000+ rows).

```
[ERROR][/Code/libxlsxwriter/src/packager.c:1103]: Error in closing member in the zipfile
[ERROR] workbook_close(): Zlib error adding file to xlsx file '/private/tmp/Albania - Estonia.xlsx'.
```

The logic of `RETURN_ON_ZIP_ERROR` indicates that the error is not `ZIP_ERRNO` (née `Z_ERRNO`) - however, I do not know what the actual error code is. Any way to bubble this up so I can access it from client code?

**Comment by jmcnamara** [comment]
> Any way to bubble this up so I can access it from client code?

Not without remapping all the zlib error codes. There are only 6 so that is probably doable. However, the zlib error codes aren't hugely informative either so they probably wouldn't be very useful to you anyway. See: https://www.zlib.net/manual.html

**Comment by evanmiller** [comment]
Distinct from the Zlib errors there are the ZIP errors, which would help me narrow down the offending code path.

https://github.com/jmcnamara/libxlsxwriter/blob/b616fb59ffe0268b1ee0cecf822bf8ed45cf4f30/include/xlsxwriter/third_party/zip.h#L88-L90

**Comment by evanmiller** [comment]
I should also add: The library's error messages incorrectly report all ZIP errors as Zlib errors.

**Comment by jmcnamara** [comment]
> I should also add: The library's error messages incorrectly report all ZIP errors as Zlib errors.

Ah yes. Thanks.

**Comment by jmcnamara** [comment]
I've pushed a fix for this to master where the library tries to bubble up the zip (not zlib) errors.

I simulated some of the failure conditions and the warning/error is now:

```
[ERROR] workbook_close(): Zip ZIP_BADZIPFILE error while creating xlsx file 'chart.xlsx'. 
This may require the use_zip64 option for large files. 
System error = Undefined error: 0
```

Can you try it out with your real world test case.

**Comment by evanmiller** [comment]
Works perfectly. Thank you.
