### ISSUE TITLE
worksheet_write_rich_string(): support 1 fragment

### ISSUE THREAD

**Issue by mewalig** [jmcnamara/libxlsxwriter#231]
Rather than require the caller to check how many fragments there are and handle the 1 case differently from the 1+ case, it would be nice if worksheet_write_string() would do it:

    if (i <= 2)
       /*  err = LXW_ERROR_PARAMETER_VALIDATION; */
      return worksheet_write_string(self, row, col, rich_strings[0]->string, rich_strings[0]->format);

**Comment by jmcnamara** [comment]
> Rather than require the caller to check how many fragments there are and handle the 1 case differently from the 1+ case,

I think this case should be handled by the user. If there aren't string fragments then it isn't a rich string.

So, unfortunately, this is a won't fix for me. But thanks for the suggestion.

**Comment by jmcnamara** [comment]
BTW, you are encountering a lot of edge case in the library (which is good). What are you working on?
