### ISSUE TITLE
minor documentation error for worksheet_set_column()

### ISSUE THREAD

**Issue by mewalig** [jmcnamara/libxlsxwriter#232]
In https://libxlsxwriter.github.io/worksheet_8h.html#ab9b7fb95e1bd9b0da70befd0d37a9173, "LXW_DEF_COL_HEIGHT" should be "LXW_DEF_COL_WIDTH":

    worksheet_set_column(worksheet, 0, 0, LXW_DEF_COL_HEIGHT, bold);

should be

    worksheet_set_column(worksheet, 0, 0, LXW_DEF_COL_WIDTH, bold);

**Comment by jmcnamara** [comment]
Thanks. Fixed on master.
