### ISSUE TITLE
call workbook_close somtimes not  create xlsx file

### ISSUE THREAD

**Issue by myseemylife** [jmcnamara/libxlsxwriter#235]
I have inserted 19000+row data ，6 colums，then call workbook_close,but the lib not always create  the file successfully.after 2 hours debug,in iowin32.c line 185.
 `
 hFile = CreateFile((LPCTSTR)filename, dwDesiredAccess, dwShareMode, NULL, dwCreationDisposition, dwFlagsAndAttributes, NULL);
` the handle is NULL.
GetLastError = 32. need help

**Comment by jmcnamara** [comment]
According to this [MS Doc](https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-) Error 32 is:

```
ERROR_SHARING_VIOLATION

    32 (0x20)

    The process cannot access the file because it is being used by another process.
```
Is the file already open in Excel?

Also, can you put this as the close() for your application and let me know the output:

```C
   lxw_error error = workbook_close(workbook);

    /* Check if there was any error creating the xlsx file. */
    if (error)
        printf("Error in workbook_close().\n"
               "Error %d = %s\n", error, lxw_strerror(error));
```

**Comment by jmcnamara** [comment]
Closing due to lack of feedback.

**Comment by myseemylife** [comment]
Sorry Disappeared for many days~
I reproduce the case today，got ` error =  LXW_ERROR_CREATING_XLSX_FILE`,
OS: Win10 64bit

**Comment by jmcnamara** [comment]
What is the full printf output from the error code above?
