### ISSUE TITLE
Feature request: worksheet_write_blank()

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#24]
Add `worksheet_write_blank()` function like the Python XlsxWriter Worksheet method `write_blank()`.
See https://xlsxwriter.readthedocs.org/index.html

* Difficulty: 1 (Easy 1 - 5 Hard)
* Priority: 4 (High 1 - 5 Low)

Add +1 as a comment to vote for this feature and to get an update when it is implemented.

**Comment by mrenters** [comment]
Doesn't this function already exist?

**Comment by jmcnamara** [comment]
Indeed it does. Looks like I'm ahead for the night already. :-)
