### ISSUE TITLE
move / reorder worksheets

### ISSUE THREAD

**Issue by liquidaty** [jmcnamara/libxlsxwriter#240]
Hello, 

If I do:
```
lxw_worksheet *ws_C = workbook_add_worksheet(wb, "Sheet C");
lxw_worksheet *ws_B = workbook_add_worksheet(wb, "Sheet B");
lxw_worksheet *ws_A = workbook_add_worksheet(wb, "Sheet A");
```
then is there any way later to re-order the worksheets, before closing the workbook, so that the worksheets are saved in a different order than they were created in (e.g. Sheet A, then Sheet B, then Sheet C)?

**Comment by jmcnamara** [comment]
> is there any way later to re-order the worksheets, before closing the workbook

No. This was never part of the design. It isn't even supported in the Python or Perl versions.

While it is theoretically possible there are some potential edge cases where it isn't desirable to have the worksheets change order internally. So this is unlikely to be implemented. Sorry.
