### ISSUE TITLE
Libxlsxwriter Roadmap

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#245]
See the [XlsxWriter Roadmap](https://github.com/jmcnamara/XlsxWriter/issues/653).

**Comment by tritueviet** [comment]
hello @jmcnamara  i check the constant memory not working with merge range? can you support for this case?

**Comment by jmcnamara** [comment]
> i check the constant memory not working with merge range? can you support for this case?

The `worksheet_merge_range()` function needs to write the all the cells in the merged range which is in conflict with the "constant memory" rule that it can only write one row at a time. So that is why merged ranges aren't supported in "constant memory" mode. 

While it could be supported technically (i.e., it would be possible) it would take a lot of effort and isn't currently a feature that is requested very often. So overall due to complexity, effort, and lack of requests it won't be supported in the future.

**Comment by tritueviet** [comment]
Can you share some document, i will learn fast and help build this.

**Comment by jmcnamara** [comment]
> Can you share some document, i will learn fast and help build this.

Could you open a new issue to discus that question. This is issue is for roadmap items.

**Comment by tritueviet** [comment]
> > Can you share some document, i will learn fast and help build this.
> 
> Could you open a new issue to discus that question. This is issue is for roadmap items.

https://github.com/jmcnamara/libxlsxwriter/issues/435 I requested it here, thanks for supporting this feature as soon as possible.
