### ISSUE TITLE
Feature request: Add autofilter conditions functionality

### ISSUE THREAD

**Issue by a2nath** [jmcnamara/libxlsxwriter#254]
Hi I've been looking at this example from python examples. Is this feature going to be ported in the c++ version of the plugin? If so, could you provide a timeline for that? 

My comment can be seen here: github.com/jmcnamara/XlsxWriter/issues/653#issuecomment-557170745
To clarify even further, this is what I'm talking about: xlsxwriter.readthedocs.io/working_with_autofilters.html#filter-data-in-an-autofilter

**Comment by jmcnamara** [comment]
> Is this feature going to be ported in the c++ version of the plugin?

Yes.



> If so, could you provide a timeline for that?

No. I can't/don't provide timelines for feautures. In terms of the [Roadmap](https://github.com/jmcnamara/XlsxWriter/issues/653) it is somewhere in item 8.

**Comment by znakeeye** [comment]
So this feature is about serializing a filter string to be applied when using Autofilters? Because the Autofilters feature itself is already in place (the [docs](https://libxlsxwriter.github.io/index.html)), right?

Very much wanted feature indeed! +1

**Comment by Robert-M-Muench** [comment]
+1

**Comment by jmcnamara** [comment]
Note, this feature is now underway. Initial code is on main but it requires examples and documentation. That will follow in the next week or so.

**Comment by jmcnamara** [comment]
This functionality has been added in libxlsxwriter version 1.1.2. See https://libxlsxwriter.github.io/working_with_autofilters.html and https://libxlsxwriter.github.io/autofilter_8c-example.html 

Closing feature request.
