### ISSUE TITLE
worksheet->vba_name allows illegal worksheet codeName

### ISSUE THREAD

**Issue by mewalig** [jmcnamara/libxlsxwriter#256]
Hi,

Worksheet codenames seem to have tighter limitations than worksheet names, and because codenames are, at the moment, set to the same value as the worksheet name, under certain conditions, a generated XLSM file will throw errors when opened. 

Two examples of this are:
- if a worksheet name starts with a number
- if a worksheet name contains Asian characters

The below line appears to require modification to address this issue:
```
worksheet_set_vba_name(worksheet, worksheet->name)
```

I am not sure exactly what the codeName limitations are, but at the least, codenames that begin with A-Za-z and only contain alphanumeric ASCII chars, up to a total of 31 characters, seem to work (and of course they must be unique across worksheets within the same wb). Obviously it is somewhat desirable to try to retain a codename similar to the actual worksheet name, so perhaps something that at least tries to use alphanumerics that are in the ws name would be ideal, along the lines of:

first char = first char of name, if A-Za-z, else 'z'
subsequent chars = corresponding char of name, if A-Za-z0-9, else '_'

last several chars may need to be _XXXX where XXXX is a number, in order to ensure uniqueness

I could take a crack at this if you'd like

**Comment by RaFaeL-NN** [comment]
https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/not-a-legal-object-nameitem

**Comment by mewalig** [comment]
It seems to have a limit of 31 chars for the property that corresponds to the XML property "codeName"-- when I manually try to change it in Excel, the following works: 
```
z123456789012345678901234567890
```
and the following fails:
```
z1234567890123456789012345678901
```
![image](https://user-images.githubusercontent.com/8260442/71208485-12cb7e00-2277-11ea-85ee-d546060b21ad.png)

**Comment by jmcnamara** [comment]
@mewalig What was the original sheetname you encountered that raised this issue?

**Comment by jmcnamara** [comment]
> I am not sure exactly what the codeName limitations are, but at the least, codenames that begin with A-Za-z and only contain alphanumeric ASCII chars, up to a total of 31 characters, seem to work 

I think the limit may be as low as 22 characters for the VBA name as stored in Excel. I came across that once before:

https://github.com/jmcnamara/XlsxWriter/issues/628#issuecomment-494979289

> I could take a crack at this if you'd like

Thanks but this issue doesn't happen often enough to try fix it like this. I'd prefer, for now, to just handle this, and other error case, using the debug steps in docs "What to do if it doesn't work":


https://libxlsxwriter.github.io/working_with_macros.html#ww_macros_debugging

**Comment by mewalig** [comment]
@jmcnamara The sheet name in my use case where this issue came up was "1785_data_compare". Having sheet names that start with numbers is actually extremely common for our use cases.

**Comment by jmcnamara** [comment]
> The sheet name in my use case where this issue came up was "1785_data_compare".

What was the corresponding via name used by Excel in this case?

 I tried to replicate it but the worksheet VBA names were "Sheet1", "Sheet2", etc.

On a Unix-like system you can find the codename as follows (just change myfile to whatever filename you have):

```bash
$ unzip myfile.xlsm -d myfile
$ xmllint --format `find myfile -name "*.xml" | xargs` | grep "Pr.*codeName"
```

**Comment by mewalig** [comment]
The workbook did not exist before being created by libxlsxwriter, which by default set the equal the sheet name ("1785_data_compare"), which Excel would then throw a repair-able error upon opening. Creating from scratch using Excel, I tried creating a sheet in an XLSM, and also tried creating one in XLSX and then converting to XLSM, and in all cases I could come up with, the codeName was always set to SheetN (unless/until I later manually changed it).

**Comment by jmcnamara** [comment]
> in all cases I could come up with, the codeName was always set to SheetN (unless/until I later manually changed it).

Same here. So that should probably be the default. I'll re-open this as a bug and fix it.

**Comment by jmcnamara** [comment]
@mewalig I've pushed a fix to master for the issue with the incorrect default code name. Try it out if you get a chance.

There will still be cases where the user has to override the default but this should cover the majority of the default cases.

**Comment by jmcnamara** [comment]
Upstreamed in 0.9.2/0.9.3.
