### ISSUE TITLE
Unable to compile code with Cocoapods version 0.9.0

### ISSUE THREAD

**Issue by sunkumar** [jmcnamara/libxlsxwriter#259]
Dear Team,

Today I have updated code with version 0.9.0 and it stop compiling code via Xcode 11.2.1. 

It is working fine with version 0.8.9 pod version. Below are the message I am getting

Undefined symbol: _MD5_Init
Undefined symbol: _MD5_Update
Undefined symbol: _MD5_Final

**Comment by jmcnamara** [comment]
Thanks for the report. I see the issue. I'll fix it soon and push a new version.

**Comment by jmcnamara** [comment]
I've pushed version 0.9.1 to the Cocoapods repository. Can you try it again.

**Comment by sunkumar** [comment]
Thanks Its working now!
