### ISSUE TITLE
Compiling error in GCC<5

### ISSUE THREAD

**Issue by RaFaeL-NN** [jmcnamara/libxlsxwriter#262]
I am using GCC 3.4.5 and get error

```
In file included from ../include/xlsxwriter/app.h:14,
                 from app.c:11:
../include/xlsxwriter/workbook.h:961: error: wrong number of arguments specified for `deprecated' attribute
```

It's because of "deprecated" from C++14. GCC supports C++14 from version 5 ("deprecated" from 4.9). Can you change

`#ifdef __GNUC__`

in common.h to

`#if __GNUC__ >=5`

?

**Comment by jmcnamara** [comment]
Done. Fixed on master.

**Comment by RaFaeL-NN** [comment]
> Done. Fixed on master.
I think "> 5" is not right, " >= 5" is

**Comment by jmcnamara** [comment]
I fixed that after the push. It is on master already.

**Comment by jmcnamara** [comment]
Thanks by the way.
