### ISSUE TITLE
Additions for 0.9.2 release notes

### ISSUE THREAD

**Issue by sjmulder** [jmcnamara/libxlsxwriter#264]
As a suggestion, these changes in 0.9.2 do seem relevant enough to add to the release notes:

 - Makefile now respects DESTDIR and PREFIX, including when setting
   rpath on macOS.
 - Removal of deprecated functions.
 - Naming changes in bundled MD5 code to avoid conflicts with OpenSSL.
 - Warning fixes (int sizes etc).
 - __atribute__((deprecated)) not used on GCC < 5.
 - Fix for vba_name allowing illegal worksheet codename.

**Comment by jmcnamara** [comment]
Thanks. I've added some of those into the changes file.

Some are too minor to include though.

**Comment by sjmulder** [comment]
Fair enough! Thanks.
