### ISSUE TITLE
internal hyperlink location not set

### ISSUE THREAD

**Issue by mewalig** [jmcnamara/libxlsxwriter#267]
calling ```worksheet_write_url()``` with an internal target such as:
    "internal:#'my target worksheet'!A1"

the link location was being set to an empty string, so the output xlsx cell contained a link that appeared to be clickable, but upon click, did not do anything. This issue did not seem to exist a few months ago, so may have been introduced from a recent change.

Making the following change to src/worksheet.c around line 4888 seemed to fix the problem, though I'm not sure this doesn't cause other problems:

    if(found_string != url_copy) /* added this line. maybe should be: if(link_type == HYPERLINK_EXTERNAL)? */
        *found_string = '\0';

**Comment by jmcnamara** [comment]
Thanks. Just to be clear can you add a small complete C program that demonstrates the issue and I'll look at it.

**Comment by jmcnamara** [comment]
Also is it valid to have # at the start of the link like that?

**Comment by mewalig** [comment]
Oh, should it instead be called as follows?
    worksheet_write_url(ws, "internal:'my target worksheet'!A1")

? If so we'll just do that. Not sure why we thought we needed the "#" before

Would it be possible to add an example (or a reference thereto) of an internal hyperlink to https://libxlsxwriter.github.io/hyperlinks_8c-example.html?

**Comment by jmcnamara** [comment]
> Oh, should it instead be called as follows?

Yes. That is right.



> Would it be possible to add an example (or a reference thereto) of an internal hyperlink to

I'm not sure it make send there but there are several examples in the API docs:

https://libxlsxwriter.github.io/worksheet_8h.html#a9b2ac96ee23574a432f5703eedcaf9a1
