### ISSUE TITLE
Error opening file with Excel

### ISSUE THREAD

**Issue by duncangroenewald** [jmcnamara/libxlsxwriter#268]
I am getting an error on one generated file when opening with Excel.  See the following error log output.  I can upload a copy of the generated file is required.  The file seems to open fine but it's a bit annoying getting this message.

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Repair Result to XXXX Extract 2020-01-17_2307480.xml</logFileName><summary>Errors were detected in file ’/Users/Shared/XXXX/Reports/Stock/XXXX Extract 2020-01-17_230748.xlsx’</summary><repairedRecords summary="Following is a list of repairs:"><repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet1.xml part</repairedRecord></repairedRecords></recoveryLog>

**Comment by jmcnamara** [comment]
>  I can upload a copy of the generated file is required.

Yes, if you can. If it contains confidential information you can email it to me instead.

A small program that reproduces the issue would be better. Or if you can debug it then strip your program down until the error goes away.

It isn't a very common issue but things that can cause it are:

- No UTF8 data
- Overlapping merged ranges.

**Comment by duncangroenewald** [comment]
Thanks, it was being caused by Swift Double values that were NaN.  I would think it should handle that - i.e. convert to something Excel understands.  As it is I fixed it by adding a check for Nan and don't write out the value.

**Comment by jmcnamara** [comment]
> I would think it should handle that - i.e. convert to something Excel understands.

It is hard to detect NaN portably in C. Also Excel doesn't have a representation for NaN (outside of a formula result).

> As it is I fixed it by adding a check for Nan and don't write out the value.

I think that is the best approach for now.
