### ISSUE TITLE
Add option USE_DOUBLE_FUNCTION to CMakeLists

### ISSUE THREAD

**Issue by petricf** [jmcnamara/libxlsxwriter#269]
For non-US locales the option -DUSE_DOUBLE_FUNCTION must be passed to the make call to create valid excel files.

This patch allows to pass this option at cmake execution. This let cmake also execute the make step for non-US locales. It saves an extra execution step.

It can be found at gentoo bugtracker:
  [https://bugs.gentoo.org/attachment.cgi?id=603408&action=edit](https://bugs.gentoo.org/attachment.cgi?id=603408&action=edit)

The patch was created by Jon Hood.

Please apply this patch.

**Comment by jmcnamara** [comment]
Thanks. I'll add that and probably make it the default.

**Comment by jmcnamara** [comment]
Added to main. This will be in the next release of libxlsxwriter.
