### ISSUE TITLE
Copy one sheet to another and also add new content

### ISSUE THREAD

**Issue by sapomuyverde** [jmcnamara/libxlsxwriter#271]
Hi,
I have created a sheet in excel, now I require exactly the same content of the first sheet in the second sheet and in the second sheet I must also add a promissory note (it is an invoice report), is there any way/trick to be able to do this?, any ideas?.

I appreciate your help and your time.

Regards,
Javier

**Comment by jmcnamara** [comment]
There isn't any way to copy one worksheet to another.

The simplest, and only way, is to create a function that takes a worksheet point and applies a standard formatting.
