### ISSUE TITLE
Incorrect image height

### ISSUE THREAD

**Issue by RaFaeL-NN** [jmcnamara/libxlsxwriter#274]
examples\images.c

`
    
    lxw_workbook  *workbook  = workbook_new("images.xlsx");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);
    worksheet_insert_image(worksheet, CELL("B2"), "logo.png");    
    workbook_close(workbook);  `

Height is 103%. Why?

![images](https://user-images.githubusercontent.com/34895749/75614974-42d4ae80-5b4f-11ea-988e-92c0c26e8d3e.png)

0.6 scale -> 63%, and so on. 1.1 -> 116%. 
But 0.5 scaling is correct, but 0.5 only

**Comment by jmcnamara** [comment]
Could you attach the image you are using

**Comment by RaFaeL-NN** [comment]
[images.zip](https://github.com/jmcnamara/libxlsxwriter/files/4271059/images.zip)

**Comment by jmcnamara** [comment]
It looks okay in my version of Excel when I run this program (same as your with the filename and image renamed):

```C

#include "xlsxwriter.h"

int main() {
    lxw_workbook  *workbook  = workbook_new("gh274.xlsx");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);

    worksheet_insert_image(worksheet, CELL("B2"), "gh274.png");

    workbook_close(workbook);

    return 0;
}
````

Output:

![Screenshot 2020-02-29 at 23 15 59](https://user-images.githubusercontent.com/94267/75616499-bd9acb00-5b49-11ea-98a8-536f681be845.png)


What happens when you manually insert that image into Excel? What dimensions do you get?

**Comment by RaFaeL-NN** [comment]
When I do it manually I get all dimensions like on your screenshot. I try 3 versions of Windows and 3 versions of Excel and always get 103/100. Could you attach gh274.xlsx to compare files?

**Comment by RaFaeL-NN** [comment]
I get 3% every 1 row. If an image is smaller of a cell, height is right. If an image places on two rows, I get 3%. If on 3 rows, 6%, and so on

**Comment by RaFaeL-NN** [comment]
I found an issue. _worksheet_size_row returns 19 instead of 20. I change

`

        if (row) {
        if (row->hidden && anchor != LXW_OBJECT_MOVE_AND_SIZE_AFTER)
            pixels = 0;
        else
            pixels = (uint32_t) (4.0 / 3.0 * row->height);
    }
    else {
        pixels = (uint32_t) (4.0 / 3.0 * self->default_row_height);
    }

`

to 

`

       if (row) {
        if (row->hidden && anchor != LXW_OBJECT_MOVE_AND_SIZE_AFTER)
            pixels = 0;
        else
            pixels = (uint32_t) (row->height * 4.0 / 3.0);
    }
    else {
        pixels = (uint32_t) (self->default_row_height * 4.0 / 3.0);
    }

`

and it works correct now for me. I don't know a nature of this issue (old compiler, compiling options or smth other) but I hope you'll apply this patch too

**Comment by jmcnamara** [comment]
> I found an issue. _worksheet_size_row returns 19 instead of 20

Good find. Does the following work? It may be more explicit. The `4.0/3.0` actually comes from the ratio of DPIs `96.0/72.0`:

```C
        if (row->hidden && anchor != LXW_OBJECT_MOVE_AND_SIZE_AFTER)
            pixels = 0;
        else
            pixels = (uint32_t) (0.75 * row->height);
    }
    else {
        pixels = (uint32_t) (0.75 * self->default_row_height);
    }
```

**Comment by RaFaeL-NN** [comment]
Do you mean (row->height) / 0.75 ? 4/3=1.3(3)

**Comment by jmcnamara** [comment]
Good thanks. I’ll probably go with that.

**Comment by jmcnamara** [comment]
Ok. Thanks. Fixed on master.
