### ISSUE TITLE
Will worksheet_merge_range() work for current row with 'constant_memory'?

### ISSUE THREAD

**Issue by znakeeye** [jmcnamara/libxlsxwriter#277]
In `worksheet.h` I see the following alarming comment:
```c
 /*
 * @note Merged ranges generally don’t work in libxlsxwriter when the Workbook
 * #lxw_workbook_options `constant_memory` mode is enabled.
 */
lxw_error worksheet_merge_range(lxw_worksheet *worksheet, lxw_row_t first_row,
                                lxw_col_t first_col, lxw_row_t last_row,
                                lxw_col_t last_col, const char *string,
                                lxw_format *format);
```

But what if `first_row` and `last_row` both equal the current row (in constant memory mode). Won't that work? I had some success with this restriction. Was it a mere coincidence or can you expect this API to work in that case?

If looping each row, and then each column... when can I expect this API to fail?

**Comment by jmcnamara** [comment]
> But what if first_row and last_row both equal the current row (in constant memory mode)

Yes. That will work.
