### ISSUE TITLE
How to get the default format?

### ISSUE THREAD

**Issue by znakeeye** [jmcnamara/libxlsxwriter#279]
In `workbook.c` you add a default format:

```c
/* Add the default cell format. */
    format = workbook_add_format(workbook);
    GOTO_LABEL_ON_MEM_ERROR(format, mem_error);
```

How do you retrieve that format? E.g. I would like to change the default font for all cells, so I expected something like this:

```c
format = workbook_get_default_format(workbook);
```

But no such API. Ideas?

**Comment by jmcnamara** [comment]
That font isn't exposed, deliberately, since changing it generally affects size calculations used for image insertion and other cell measurements.

If you really want to access it anyway, then you can do so via the `workbook->formats` linked list. However, things may break and I don't recommend it.

**Comment by znakeeye** [comment]
Thanks for clarification! Then I'm probably better off adding a custom format and provide that instance when writing cell values.

**Comment by jmcnamara** [comment]
> Then I'm probably better off adding a custom format and provide that instance when writing cell values.

Yes. That is safer.
