### ISSUE TITLE
Feature request: worksheet_insert_image()

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#28]
Add `worksheet_insert_image()` function like the Python XlsxWriter Worksheet method `insert_image()`.
See https://xlsxwriter.readthedocs.org/index.html

* Difficulty: 3 (Easy 1 - 5 Hard)
* Priority: 1 (High 1 - 5 Low)

Add +1 as a comment to vote for this feature and to get an update when it is implemented.

**Comment by nelson2005** [comment]
+1

**Comment by jmcnamara** [comment]
Support for this feature has been merged onto master. Documentation will be added in the next few days but it is functional if you want to try it out.

See the demo.c program in the examples dir on master. It produces this file:

![screenshot](https://cloud.githubusercontent.com/assets/94267/12072867/3103099c-b0f2-11e5-879e-df791971759a.png)

Note, images in headers and footers aren't currently supported. Annoyingly Excel uses a different internal XML structure for those. That feature will be added as part of feature request #43.
