### ISSUE TITLE
worksheet_set_row_opt (constant_memory) shows inverted expander

### ISSUE THREAD

**Issue by znakeeye** [jmcnamara/libxlsxwriter#280]
I see a glitch when setting the outline on each row, in sequence. E.g.:

```c
lxw_row_col_options options = { .hidden = 0, .level = 1, .collapsed = 0 };
worksheet_set_row_opt(ws, currentRow++, LXW_DEF_ROW_HEIGHT, NULL, &options);
```

**Actual:**
![outline_actual](https://user-images.githubusercontent.com/958469/78136217-8870e980-7423-11ea-9113-d64977efaec0.png)

**Expected:**
![outline_expected](https://user-images.githubusercontent.com/958469/78136207-83ac3580-7423-11ea-83b9-368b80799b48.png)

Why is it inverted like that?

**Comment by jmcnamara** [comment]
For clarity, can you add a small complete compilable C program that demonstrates the issue.

**Comment by znakeeye** [comment]
```c++
lxw_workbook_options wo { 1, NULL, 0 };
auto wb = workbook_new_opt("foo.xlsx", &wo);
auto ws = workbook_add_worksheet(wb, "Sheet1");

int row = 0;

lxw_row_col_options co = { 0, 1, 0 };
worksheet_set_row_opt(ws, row++, LXW_DEF_ROW_HEIGHT, NULL, &co);
worksheet_set_row_opt(ws, row++, LXW_DEF_ROW_HEIGHT, NULL, &co);
worksheet_set_row_opt(ws, row++, LXW_DEF_ROW_HEIGHT, NULL, &co);

workbook_close(wb);
```

**Comment by jmcnamara** [comment]
That isn't a complete compilable C program.

P.S. I just checked and the "Actual" is the Excel default. 

You can get the "Expected" by changing the Excel worksheet settings via `worksheet_outline_settings()`: https://libxlsxwriter.github.io/worksheet_8h.html#a9efae5027e762c9a29f6afa547e4b2db

In particular the `symbols_below` option.

**Comment by znakeeye** [comment]
Ah! Thanks a lot!

PS. Will improve my samples from now on :)

**Comment by jmcnamara** [comment]
No problem. Thanks for following up.

**Comment by znakeeye** [comment]
By the way, your API design is absolutely brilliant. Keep up the good work!
