### ISSUE TITLE
worksheet_merge_range might produce a corrupt file

### ISSUE THREAD

**Issue by znakeeye** [jmcnamara/libxlsxwriter#281]
I want to create this:

![image](https://user-images.githubusercontent.com/958469/78145430-29b26c80-7431-11ea-8558-9b408ab2f9da.png)

So I tried this:

```c
#include "xlsxwriter.h"

int main()
{
    auto wb = workbook_new_opt("foo.xlsx");
    auto ws = workbook_add_worksheet(wb, "Sheet1");

    int row = 0;
    worksheet_merge_range(ws, row, 0, row, 2, "AB", NULL);
    row++;
    worksheet_merge_range(ws, row, 0, row, 1, "A", NULL);
    worksheet_merge_range(ws, row, 1, row, 2, "B", NULL);

    workbook_close(wb);
    
    return 0;
}
```

Then when opening the file Excel complains. Shouldn't `libxlsxwriter` be able to detect this error?

It seems impossible to create this cell pattern using the merge API. Ideas?

**Comment by znakeeye** [comment]
I can get the pattern if I change the last merge call to:
```
worksheet_write_string(ws, row, 2, "B", NULL);
```

Do you think it is up to the developer to handle this? Or should the merge method have a special case where it internally calls `worksheet_write_string(self, first_row, last_col, string, format)` for `first_row == last_row`?

**Comment by znakeeye** [comment]
The more I think of it, I believe that `worksheet_merge_range` should return some new error code for this overlapping issue. That way we can take action should the error occur.

It's very hard to detect this condition before calling the method. You would have to maintain a dictionary of added merge ranges and check if the new merge would overlap.

**Comment by znakeeye** [comment]
I guess overlap-detection would be quite costly? Certainly don't want to reduce performance.

**Comment by jmcnamara** [comment]
I think you worked out all the answers here yourself:

- Overlapping merge ranges causes a corrupt file warning.
- Thus you should avoid doing that.
- The library should warn or prevent the user from doing that.
- But it is expensive and tricky so currently it doesn't.
