### ISSUE TITLE
Change size of outline symbols?

### ISSUE THREAD

**Issue by znakeeye** [jmcnamara/libxlsxwriter#282]
Please pay attention to the size of the symbols below.

**libxlsxwriter:**
![outline_actual](https://user-images.githubusercontent.com/958469/78136217-8870e980-7423-11ea-9113-d64977efaec0.png)

**old document (wanted):**
![outline_expected](https://user-images.githubusercontent.com/958469/78136207-83ac3580-7423-11ea-83b9-368b80799b48.png)

These two documents seem to have a different default style. I.e. the second one has "Arial 8" and `libxlsxwriter` has "Calibri 11".

Looking at the `worksheet_outline_settings` it doesn't take a `format` argument. Ideas?

**Comment by jmcnamara** [comment]
You need to create a small compilable C program that demonstrates the issue.

**Comment by jmcnamara** [comment]
You should also verify that what you are seeing isn't Excel's default behaviour, i.e., not a libxlsxwriter issue.

**Comment by znakeeye** [comment]
Well, I don't know how to reproduce this in libxlsxwriter, since I cannot find an API that allows me to change the font for the outline symbols.

In Excel, you can accomplish this:
1. Select row 1-3. `Data` -> `Group` -> `Group...`
2. Click the triangle between `A` and `1` to select everything.
3. Change the font to Arial, 8 points.

**Comment by znakeeye** [comment]
Please advise!

The way I see it, we are lacking an API to alter the default style. I understand that style is important for measuring etc, but perhaps we could have a way to set it immediately on creating a worksheet?

**Comment by jmcnamara** [comment]
You may be able to do what you want by setting the default row height via `worksheet_set_default_row()`:

https://libxlsxwriter.github.io/worksheet_8h.html#a74121de7c4f67639b30f302d4af48eb4

For Arial 8 the default row height would be 11.25.

**Comment by znakeeye** [comment]
Thanks. That actually works. I guess Excel internally sets the default row height like that when selecting the entire sheet.

How did you come up with the number `11.25`?

**Comment by jmcnamara** [comment]
> How did you come up with the number `11.25`?

I set the font to Arial 8 using the steps that you described and then checked the height by mouseover in Excel:


![aa_image](https://user-images.githubusercontent.com/94267/79442908-0fe85c00-7fd1-11ea-8123-cf6a814b30ab.png)
