### ISSUE TITLE
worksheet_set_row_opt scales inserted image vertically?

### ISSUE THREAD

**Issue by znakeeye** [jmcnamara/libxlsxwriter#284]
When inserting an image (`constant_memory = true`) it is somehow scaled by the outline row height. Is this expected behavior?

**The 349x70 image**
![foo349x70](https://user-images.githubusercontent.com/958469/79473212-1f819800-8005-11ea-9684-6d31b9962c53.png)

**Expected:**
![image](https://user-images.githubusercontent.com/958469/79473252-2c05f080-8005-11ea-99d3-4238731b1586.png)

**Actual:**
![image](https://user-images.githubusercontent.com/958469/79473280-332cfe80-8005-11ea-9bff-2a2d998f51e8.png)

```c
#include "xlsxwriter.h"

int main()
{
    lxw_workbook_options wb_options = { LXW_TRUE, NULL, LXW_FALSE };

    auto wb = workbook_new_opt("foo.xlsx", &wb_options);
    auto ws = workbook_add_worksheet(wb, "Sheet1");

    lxw_image_options img_options {
        4, 3,
        0.43, 0.43,
        LXW_OBJECT_POSITION_DEFAULT,
        NULL, NULL, NULL
    };

    lxw_row_col_options options = { LXW_FALSE, 1, LXW_TRUE };
    worksheet_set_row_opt(ws, 0, 100.0, NULL, &options); // This scales image vertically?!

    worksheet_insert_image_opt(ws, 0, 0, "foo349x70.png", &img_options);
    workbook_close(wb);
    
    return 0;
}
```

**Comment by znakeeye** [comment]
Shouldn't `lxw_worksheet_find_row()` consider `optimize_row`? I.e.:

```c
lxw_row *
lxw_worksheet_find_row(lxw_worksheet *self, lxw_row_t row_num)
{
    lxw_row tmp_row;

    if (self->optimize && row_num == self->optimize_row->row_num) {
        return self->optimize_row;
    }
```

**Comment by znakeeye** [comment]
I can confirm that the above seems to fix this problem. Can you please verify that this patch is valid and consider pushing it to master?

**Comment by znakeeye** [comment]
Update: My suggested fix does not work if adding text on any other row. E.g. before closing the workbook:

```c
worksheet_write_string(ws, 1, 0, ":(", NULL);
```

Obviously, the "optimize_row" is updated to row 1 before the image is written to row 0. This is bad :(

Ideas?

**Comment by jmcnamara** [comment]
I haven't had a chance to look at this yet. Just to be clear, does this happen when you set `.constant_memory = LXW_FALSE` in the `workbook_new_opt()` constructor?

**Comment by znakeeye** [comment]
It does **not** happen when I set `.constant_memory = LXW_FALSE`. I investigated this a bit further, and my latest idea is the following:

```c
/* Subtract the underlying cell heights to find the end cell. */
if (!self->optimize) { // <---- HERE!
    while (height >= _worksheet_size_row(self, row_end, anchor)) {
        height -= _worksheet_size_row(self, row_end, anchor);
        row_end++;
    }
}
```

Thus, no fiddling with the height when using `constant_memory`. Makes sense?

**Comment by jmcnamara** [comment]
> It does **not** happen when I set `.constant_memory = LXW_FALSE`

Okay. In that case it is a bug.



> Makes sense?

I don't know. I'll have to write some test cases and then fix it. I'll look into it.

**Comment by znakeeye** [comment]
Please, also have a look at this [other issue](https://github.com/jmcnamara/libxlsxwriter/issues/283). There seems to be a generic problem with the first outline when `symbols_below` is **false**.

**Comment by znakeeye** [comment]
No news regarding this bug?

**Comment by jmcnamara** [comment]
> No news regarding this bug?

As far as I remember a fix for this turned out to be too complicated. So, realistically, it is probably a "won't fix". I fill probably document that image scaling with modified row heights doesn't work in "constant_memory" mode.

**Comment by znakeeye** [comment]
Too bad :/

Please recall my suggested fix:

> ```c
> /* Subtract the underlying cell heights to find the end cell. */
> if (!self->optimize) { // <---- HERE!
>     while (height >= _worksheet_size_row(self, row_end, anchor)) {
>         height -= _worksheet_size_row(self, row_end, anchor);
>         row_end++;
>     }
> }
> ```

I've been using this patch for a while now. It seems to work quite well. Not sure when and why it would break. Perhaps we could add some `#define ENABLE_SHAKY_IMAGE_SCALING_PATCH` to allow for this "weak" patch?

**Comment by jmcnamara** [comment]
> Please recall my suggested fix:

Unfortunately, some of the test cases fail if that patch is applied.

I'll keep the issue open and see if there is anything that can be done.

**Comment by jmcnamara** [comment]
I don't think this is easily fixed, and currently it isn't worth the effort since it seems to be a bit of an edge case. So for now I'm just going to [document it](https://libxlsxwriter.github.io/working_with_memory.html#ww_mem_constant) and leave it as a "won't fix". Sorry.

**Comment by znakeeye** [comment]
Too bad. Having a logo at the top of generated reports is not uncommon. So I would expect this bug to re-appear.

If I get time, I could try to find a better fix. Or perhaps, the existing tests are not bullet-proof in this case?

**Comment by jmcnamara** [comment]
> Having a logo at the top of generated reports is not uncommon.

Some users use header images for this (which is why I added that feature). See: https://libxlsxwriter.github.io/headers_footers_8c-example.html

Also this only affects `constant_memory` mode which is primarily meant for large files or raw data conversions so hopefully it won't affect too many people.

> Or perhaps, the existing tests are not bullet-proof in this case?

The test cases are based on files created by Excel so they need to remain the same.
