### ISSUE TITLE
Add 'd' suffix for debug build

### ISSUE THREAD

**Issue by znakeeye** [jmcnamara/libxlsxwriter#285]
It would be nice if the `cmake` script would add a `d` suffix by default when targeting `Debug`. I.e.:

```
if(NOT CMAKE_DEBUG_POSTFIX)
  set(CMAKE_DEBUG_POSTFIX d)
endif()
```

**Comment by jmcnamara** [comment]
I haven't had any other requests for this but if you want to submit a pull request I can review it.

**Comment by jmcnamara** [comment]
Closing. Probably not widely useful.
