### ISSUE TITLE
Does libxlsxwriter contain any encryption/decryption code?

### ISSUE THREAD

**Issue by znakeeye** [jmcnamara/libxlsxwriter#286]
When compiling the library, will any type of encryption/decryption be linked with the library?

Reading the source code, there seem to be few fragments of encryption which are excluded:

```
/* Encryption not required by libxlsxwriter. */
#ifndef NOCRYPT
#define NOCRYPT
#endif
#ifndef NOUNCRYPT
#define NOUNCRYPT
#endif
```

However, it would be great if the documentation was clear about the use of encryption/decryption. This is a very important topic e.g. when it comes to **trade compliance**.

**Comment by jmcnamara** [comment]
> When compiling the library, will any type of encryption/decryption be linked with the library?

No. The `NOCRYPT` flag is for minizip.c in the third party code.

> This is a very important topic e.g. when it comes to **trade compliance**.

Good suggestion. I'll add something about that to the Licence page.

**Comment by jmcnamara** [comment]
Note, the library does embed and use (optionally on MD5) which is a hashing function. I don't know if that is covered or forbidden by export/trade compliance. Does anyone know?

**Comment by znakeeye** [comment]
A bit uncertain, I'd say. [Here](https://www.federalregister.gov/documents/2010/06/25/2010-15072/encryption-export-controls-revision-of-license-exception-enc-and-mass-market-eligibility-submission) is a somewhat old source that states that `MD5` is "cryptographic". Still, this hashing function is no longer considered secure. Hmm.

Which parts of the library depend on MD5?

**Comment by jmcnamara** [comment]
> Which parts of the library depend on MD5?

From the [Licence](https://libxlsxwriter.github.io/license.html) file:

_Note, the MD5 library is used to avoid including duplicate image files in the xlsx file. If this functionality isn't required it is possible to compile libxlsxwriter without this library by passing `USE_NO_MD5=1` to make._

**Comment by znakeeye** [comment]
Ah, great. So with this flag set, the library will definitely be 100% free of cryptographic functions. It seems.

**Comment by jmcnamara** [comment]
Closing this even though we didn't get an answer to the underlying question on whether export compliance is required with libxlsxwriter. If anyone know that please let me know.
