### ISSUE TITLE
Feature request: workbook_add_vba_project()

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#29]
Add `workbook_add_vba_project()` function like the Python XlsxWriter Workbook method `add_vba_project()`.
See https://xlsxwriter.readthedocs.org/index.html
- Difficulty: 3 (Easy 1 - 5 Hard)
- Priority: 3 (High 1 - 5 Low)

Add +1 as a comment to vote for this feature and to get an update when it is implemented.

If you would like to make a donation to accelerate this feature you can do so via [PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ATE9EFWNF7PBJ) or contact me [directly](jmcnamara@cpan.org). Currently $0 of $300.

**Comment by nelson2005** [comment]
+1

**Comment by jmcnamara** [comment]
Since I've had a few requests about this I've added a note about making donations to prioritize this feature. See the Feature Request on GitHub.

**Comment by jmcnamara** [comment]
I've pushed an initial version of this to master. You will have to use the Python vba_extract utility (installed with xlsxwriter) for now.

Here is an example:

```C
#include "xlsxwriter.h"

int main() {

    lxw_workbook  *workbook  = new_workbook("test_macro01.xlsm");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);

    workbook_add_vba_project(workbook, "vbaProject01.bin");

    worksheet_write_number(worksheet, CELL("A1"), 123 , NULL);

    return workbook_close(workbook);
}
```

**Comment by jmcnamara** [comment]
Added docs and an example file.

**Comment by jmcnamara** [comment]
Added in version 0.8.7. See https://libxlsxwriter.github.io/working_with_macros.html
