### ISSUE TITLE
Improve docs for CocoaPod install 

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#291]
The documentation on [how to use CocoaPods](https://libxlsxwriter.github.io/getting_started.html#gsg_cocoapods) could use some improvements. See the following StackOverflow post:

https://stackoverflow.com/questions/59981701/how-to-use-c-library-in-xcode-project/

**Comment by FrankenApps** [comment]
I could put together an example, a bit like the one currently provided, however updated for Swift 5 (would be iOS only) and I could update the docs on that a bit and post the link to my repo as an additional example. I will only need a week or two, to find the time to do it...

**Comment by jmcnamara** [comment]
> I will only need a week or two, to find the time to do it...

Yes. That is fine. Take your time.

Thanks.

John

**Comment by jmcnamara** [comment]
Merged upstream in version 0.9.5. Thanks.
