### ISSUE TITLE
Writing a number in percent format

### ISSUE THREAD

**Issue by sapomuyverde** [jmcnamara/libxlsxwriter#293]
Hi,
I receive data from sql and one of the columns comes in a percentage format something like 81.46% the data type is string.

If i write something like:
format_set_num_format (format1, "0.00%")
worksheet_write_number (worksheet, 10, 0, salesPercentage, format1)

I get this 8146.00%, Instead of what I expect, which is this 81.46%

On the other hand, if I treat the data as a string
worksheet_write_string (worksheet, 10, 0, salesPercentage, )

I display the correct data as I want in Excel, but with the warning number stored as text, which I want to avoid.

Any ideas how I could format percentage correctly.

Regards,
Javier

**Comment by jmcnamara** [comment]
In Excel percentages are divided by 100. You can verify that by creating a percentage in Excel and then converting it to a number. 

So the same thing applies with Libxlsxwriter. You will need to divide the numbers by 100 and apply the number format.

**Comment by sapomuyverde** [comment]
Hi,
It works perfect, I appreciate your help.

Regards
Javier
