### ISSUE TITLE
Footer date format

### ISSUE THREAD

**Issue by sapomuyverde** [jmcnamara/libxlsxwriter#294]
Hi,
To put a footer I use

"&LCurrent date: &D" "&RCurrent time: &T";
worksheet_set_footer(worksheet2, footer2)

This puts the date in 03/06/2020 format, I normally use the dd-mmm-yyyy format in dates, how can I put the desired date format in the footer.

Regards,
Javier

**Comment by jmcnamara** [comment]
> how can I put the desired date format in the footer.

How would you do it in Excel? Is it even possible?

**Comment by sapomuyverde** [comment]
Hi,
By your answer I am assuming that is not possible, so a quick web search I see that this depends on the regional settings OS or also do it through VBA.

So I continue as is.

I appreciate your help.

Regards,
Javier

**Comment by jmcnamara** [comment]
> By your answer I am assuming that is not possible,

I don't know if it is possible or not but as a general approach it is best to try figure out what you want to do in Excel first and then apply that to libxlsxwriter.
