### ISSUE TITLE
Height DPI is incorrectly set to width DPI for PNG and JPEG images

### ISSUE THREAD

**Issue by evanmiller** [jmcnamara/libxlsxwriter#295]
There are bugs in these two lines:

https://github.com/jmcnamara/libxlsxwriter/blob/a0d920e589b00b264b37ca3c7b7cefa547721a46/src/worksheet.c#L2825
https://github.com/jmcnamara/libxlsxwriter/blob/a0d920e589b00b264b37ca3c7b7cefa547721a46/src/worksheet.c#L2951

They should read:

```C
object_props->y_dpi = y_dpi ? y_dpi : 96; 
```

```C
image_props->y_dpi = y_dpi ? y_dpi : 96; 
```

**Comment by jmcnamara** [comment]
Yikes. Thanks, I fix those.

Btw, do you have an image with different X and Y dpi that shows this issue. 

I can probably create one but if you have one already that I can use in a test case could you upload it to save time.

**Comment by evanmiller** [comment]
I do not have a test file. I discovered this while trying to debug some images being inserted with incorrect aspect ratios - possibly related to #284.

**Comment by jmcnamara** [comment]
This isn't related to #284.

No problem. I'll try come up a test case for it.

**Comment by jmcnamara** [comment]
Fixed on master. Thanks.
