### ISSUE TITLE
Following the tutorial in getting started, don't flow.

### ISSUE THREAD

**Issue by gangss2** [jmcnamara/libxlsxwriter#299]
Trying install the zlib for lua, I Try instal this lib for C to see if to do. I managed to install the ZLIB but not the xlsxwriter lib.
Where I need to include the zlib.h dependencies? The Getting Started don't answer me.

>  GanGss@DESKTOP-7IN7G8A ~ $ cd zlib-1.2.11/ && example.exe && cd .. zlib version 1.2.11 = 0x12b0, compile flags = 0x55
> uncompress(): hello, hello!
> gzread(): hello, hello!
> gzgets() after gzseek: hello!
> inflate(): hello, hello!
> large_inflate(): OK
> after inflateSync(): hello, hello!
> inflate with dictionary: hello, hello!
>  GanGss@DESKTOP-7IN7G8A ~ $ cd libxlsxwriter/ && make make[1]: Entering directory `/home/GanGss/libxlsxwriter/third_party/minizip' In file included from ioapi.c:29:
> ioapi.h:46:10: fatal error: zlib.h: No such file or directory
>  46 | #include "zlib.h"
>  | ^~~~~~~~
> compilation terminated.
> make[1]: *** [ioapi.o] Error 1 make[1]: Leaving directory `/home/GanGss/libxlsxwriter/third_party/minizip' make: *** [all] Error 2 GanGss@DESKTOP-7IN7G8A ~/libxlsxwriter $

**Comment by jmcnamara** [comment]
Sorry, I can't answer general questions like this. Maybe try StackOverflow. I looks like zlib ins't installed since the compiler can't find it on any of the expected paths. Check to make sure you installed zlib.
