### ISSUE TITLE
Feature request: worksheet outlines

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#30]
Add worksheet outline functionality and like the Python XlsxWriter: 

https://xlsxwriter.readthedocs.io/working_with_outlines.html

- Difficulty: 3 (Easy 1 - 5 Hard)
- Priority: 3 (High 1 - 5 Low)

Add +1 as a comment to vote for this feature and to get an update when it is implemented.

**Comment by papa-kilo** [comment]
This capability would be useful for my uses. I'm willing to work on this if that would be helpful to you.

**Comment by papa-kilo** [comment]
+1

**Comment by RaFaeL-NN** [comment]
+1

**Comment by Genricke** [comment]
+1
Please add collapse row. Thanks !

**Comment by jmcnamara** [comment]
I've added initial support for this feature to the mast branch.

I'll be adding additional features and docs in the next few days. In the meantime you can try out this example: https://github.com/jmcnamara/libxlsxwriter/blob/master/examples/outline.c

**Comment by RaFaeL-NN** [comment]
Big thanks!
Outline settings is also needed, because default Excel display option is strange. Thanks

**Comment by jmcnamara** [comment]
> Outline settings is also needed

No problem. All the features of the Python version, link above, will be added to the C version.

**Comment by RaFaeL-NN** [comment]
Thank you, works perfect

**Comment by jmcnamara** [comment]
Added in version 0.7.6. Closing.
