### ISSUE TITLE
Please don't use field name "delete".

### ISSUE THREAD

**Issue by toge** [jmcnamara/libxlsxwriter#300]
"delete" is C++ reserved word.
So C++ compiler can't compile 0.9.6.

```
include/xlsxwriter/chart.h:815:13: error: expected unqualified-id before ‘delete’
  815 |     uint8_t delete;
      |             ^~~~~~
```

**Comment by jmcnamara** [comment]
Ouch. That shows how long  it has been since I've written any C++ and also why Doxygen has colorising that word. :-(

I'll change it to `hide` or similar. 

I should also add a C++ compilation test. I usually don't bother due to all the alloc warnings/errors. Anyone have any suggestions on that?

**Comment by jmcnamara** [comment]
Fixed in version 0.9.7.

Let me know how you are compiling this with C++ so I can try avoid issues like this in future. Thanks.

**Comment by toge** [comment]
Thank you for your quick response!
Now I can compile 0.9.7, and every code work fine!

I usually compile C++ code with `g++ -std=c++17 -Wall -Wextra -pedantic`.
g++ 10.2.0 can work  fine with your library without any warning messages.

**Comment by jmcnamara** [comment]
> I usually compile C++ code with `g++ -std=c++17 -Wall -Wextra -pedantic`.

How exactly are you compiling. I can't get minizip to compile with those options. If I compile minizip separately I can compile everything else, but with a lot of warnings:

```
$ CFLAGS="-std=c++17 -Wall -Wextra -pedantic -fpermissive" make V=1 CC=g++-9
```
