### ISSUE TITLE
How to convert opencv Mat data to image_buffer?

### ISSUE THREAD

**Issue by simon5u** [jmcnamara/libxlsxwriter#301]
Hi all, I am using opencv to read the frame from video. I want to output the frame into excel but I received the following error "[WARNING]: worksheet_insert_image()/_opt: couldn't read image type for: image_buffer.". Following is my code:-
  
```
        Mat full = cv::imread("test.png");
        int fsize = full.total() * full.elemSize();
        unsigned char * fdata = new uchar[fsize];
        memcpy(fdata, full.data, fsize * sizeof(unsigned char));
        worksheet_insert_image_buffer(worksheet, 1, 3, fdata, fsize * sizeof(unsigned char));
```

Please help. Thanks.

**Comment by jmcnamara** [comment]
That warning usually means that the data doesn't contain any headers that indicate that the file is a known image format.

Can you add the image to this issue on GitHub. Also can you print out the size of `fsize` to see if it equates to the byte size of the file.

Also, it would be good to attach a full working example to avoid any confusion.

**Comment by simon5u** [comment]
Thanks for the reply. I am using ubuntu16, gcc5.4.0, opencv2.4.9, libxlsxwriter and codeblocks. Attached is the code I am trying. Please help.
[xlsx_example.tar.gz](https://github.com/jmcnamara/libxlsxwriter/files/5051323/xlsx_example.tar.gz)

**Comment by jmcnamara** [comment]
I compiled and ran your example.

The `worksheet_insert_image_buffer()` function works on a buffer of image data. However, the cv::MAT appears to be a matrix representation of the pixels in the file.

You need to be able to convert this into the raw buffer format for the PNG file or use some simpler read mechanism. The imread() function probably isn't the right way to do what you need to do.

I don't use OpenCV so I can't really help you with this. It is more of a general question than a Libxlsxwriter question. As such it may be better to ask it on StackOverflow.

Also, if you are reading from video you will need to ensure that the frame data is actually in PNG (or a supported format). You can't insert a raw H.264 or other video frame into Excel.

**Comment by simon5u** [comment]
Thanks for the feedback. Here is the solution I found:-

```
    /* Insert an image. */
    cv::Mat img = cv::imread("logo.png");
    // encode image into jpg
    cv::vector<uchar> buf;
    cv::imencode(".png", img, buf, std::vector<int>() );
    // encoded image is now in buf (a vector)
    unsigned char *imageBuf = new unsigned char [buf.size()];
    memcpy(imageBuf, &buf[0], buf.size());
    //  size of imageBuf is buf.size();
    worksheet_insert_image_buffer(worksheet, 1, 2, imageBuf, buf.size());
    workbook_close(workbook);
    delete[] imageBuf;
```

**Comment by jmcnamara** [comment]
Thanks for letting me know. Someone else may find that useful.
