### ISSUE TITLE
Diagonal borders

### ISSUE THREAD

**Issue by RaFaeL-NN** [jmcnamara/libxlsxwriter#304]
I found _format_set_diag_ functions in the source but there is no docs for it. Is this functions undocumented, not supported or just orphaned? Can I use it?

**Comment by jmcnamara** [comment]
I think it is just a mistake/omission that it isn't documented. It is documented in the Perl and Python versions. For example: https://xlsxwriter.readthedocs.io/format.html#format-set-diag-border

I'll update the docs but in the meantime there is a test case for it here that you can see how it is used: https://github.com/jmcnamara/libxlsxwriter/blob/master/test/functional/src/test_format09.c

```C
#include "xlsxwriter.h"

int main() {

    lxw_workbook  *workbook  = workbook_new("test_format09.xlsx");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);

    lxw_format    *border1   = workbook_add_format(workbook);
    lxw_format    *border2   = workbook_add_format(workbook);
    lxw_format    *border3   = workbook_add_format(workbook);
    lxw_format    *border4   = workbook_add_format(workbook);


    format_set_border      (border1, LXW_BORDER_HAIR);
    format_set_border_color(border1, LXW_COLOR_RED);

    format_set_diag_type (border2, LXW_DIAGONAL_BORDER_UP);
    format_set_diag_color(border2, LXW_COLOR_RED);

    format_set_diag_type (border3, LXW_DIAGONAL_BORDER_DOWN);
    format_set_diag_color(border3, LXW_COLOR_RED);

    format_set_diag_type (border4, LXW_DIAGONAL_BORDER_UP_DOWN);
    format_set_diag_color(border4, LXW_COLOR_RED);

    worksheet_write_blank(worksheet, 1, 1, border1);
    worksheet_write_blank(worksheet, 3, 1, border2);
    worksheet_write_blank(worksheet, 5, 1, border3);
    worksheet_write_blank(worksheet, 7, 1, border4);

    return workbook_close(workbook);
}
```

There is an enum called `lxw_format_diagonal_types` with the types of diagonal borders.

**Comment by jmcnamara** [comment]
I've added documentation and an example for diagonal cell borders: http://libxlsxwriter.github.io/format_8h.html#a1bd8ade5206d187f4f790dbb004ca129

Thanks for pointing out the omission.
