### ISSUE TITLE
Automatic column width

### ISSUE THREAD

**Issue by gufoe** [jmcnamara/libxlsxwriter#307]
Hello, is there any way to set the column width to automatically adjust with its content?

**Comment by jmcnamara** [comment]
Unfortunately, there is no way to specify "AutoFit" for a column in the Excel file format. This feature is only available at runtime from within Excel. So it isn't something that we be done be the library.

The only workaround would be to try track the width of the data as you write it and then size the columns based on that. However, even that isn't easy without access to some functions that would given you a pixel, or other, length for a string in a particular font. If you are on Windows you might have that but on other platforms it isn't easy.

**Comment by gufoe** [comment]
Ok, thank you for the info!
