### ISSUE TITLE
Feature request: placing a horizontal line object on top off a chart

### ISSUE THREAD

**Issue by ungakatunga** [jmcnamara/libxlsxwriter#309]
It will be very useful, to have a function set for placing some objects on top of a chart sheet. For example: a horizontal line and a separate textbox for the visualization of the median value etc.

Needed Function Set:
- function to create a line object
- function to stylize the line object
- function to get the chart sheet coordinates for a specific value on axis x or y
- function to get the chart dimension in chart sheet coordinates
- function to place the line object on the chart sheet exactly
...
- text box object analogous

**Comment by jmcnamara** [comment]
Unfortunately these features won't be added. Libxlsxwriter is mainly a port of the Python library XlsxWriter and this feature doesn't exist in the Python version.

Also, this would be quite difficult to implement.

So, unfortunately this is a won't fix.
