### ISSUE TITLE
Feature request: worksheet_data_validation()

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#31]
Add `worksheet_data_validation()` function like the Python XlsxWriter Worksheet method `data_validation()`.
See https://xlsxwriter.readthedocs.io/working_with_data_validation.html
- Difficulty: 4 (Easy 1 - 5 Hard)
- Priority: 2 (High 1 - 5 Low)

Add +1 as a comment to vote for this feature and to get an update when it is implemented.

**Comment by evanmiller** [comment]
I'd like to put in a plug for this feature -- its absence is one of the few things keeping my code base dependent on xlsLib. Just so other users are aware, Excel's data validation is how drop-down menus are implemented for choosing among a discrete set of values.

Also @jmcnamara the correct link is: https://xlsxwriter.readthedocs.io/working_with_data_validation.html

**Comment by jmcnamara** [comment]
@evanmiller Noted.

**Comment by jmcnamara** [comment]
@evanmiller I've started work on data validation in libxlsxwriter. It isn't fully useable yet but you could try it out in a few days, when it is more functional. If you are interested.

If so let me know what type of data validation you want to do.

**Comment by evanmiller** [comment]
@jmcnamara Thanks. I'm interested in pop-up buttons -- in xlsLib I do something like

```{C}
formula_t *cond1 = xlsWorksheetFormula(prediction_ws);
xlsFormulaPushCharacterArray(cond1, "FALSE\0TRUE", sizeof("FALSE\0TRUE")-1);
            
xlsWorksheetValidateCellArea(prediction_ws, first_cell, last_cell,
    DVAL_TYPE_LIST | DVAL_OP_EQUAL | DVAL_STRING_LIST_IN_FORMULA,
    cond1, NULL, NULL, NULL, NULL, NULL);
```

**Comment by jmcnamara** [comment]
This type of validation?

![screen shot 2017-09-20 at 23 42 27](https://user-images.githubusercontent.com/94267/30671270-e4be318c-9e5d-11e7-9b4c-f2bc6153d29f.png)

**Comment by evanmiller** [comment]
@jmcnamara Yes.

**Comment by jmcnamara** [comment]
@evanmiller That is currently doable with the code on the `data_validation` branch. The above was created using this program: 

```C
#include "xlsxwriter.h"

int main() {

    lxw_workbook  *workbook  = new_workbook("test_data_validation01.xlsx");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);

    char *list[] = {"Foo", "Bar", "Baz", NULL};

    lxw_data_validation *data_validation = calloc(1, sizeof(lxw_data_validation));
    data_validation->validate = LXW_VALIDATION_TYPE_LIST;
    data_validation->source_list = list;

    worksheet_data_validation_cell(worksheet, CELL("C2"), data_validation);

    free(data_validation);

    return workbook_close(workbook);
}

```

Most of the guard rails are still missing but if you can figure it out based on the above program, you can try it out.

**Comment by evanmiller** [comment]
@jmcnamara Thanks. I'll trust you that it works as advertised, and I'll keep it in mind when deciding to port the rest of my code.

**Comment by jmcnamara** [comment]
Added in version 0.75. See [Working with Data Validation](https://libxlsxwriter.github.io/working_with_data_validation.html) and [data_validate.c](https://libxlsxwriter.github.io/data_validate_8c-example.html).
