### ISSUE TITLE
Zip file not properly closed after file write error

### ISSUE THREAD

**Issue by matthiasstraka** [jmcnamara/libxlsxwriter#310]
I am having an issue with writing an xlsx file to a disk that is already full. A write error is reported (in _add_file_to_zip) but the corresponding zip file remains open when reporting the error to the caller of workbook_close. This prevents me from erasing a failed xlsx file.

How to reproduce:
- Create small RAM disk (or choose disk with low remaining storage space)
- Write large XLSX file to it

**Comment by jmcnamara** [comment]
Thanks for the report. I'll look into it.

**Comment by jmcnamara** [comment]
Can you try the fix on the gh310 branch to see if it resolves your issue.

**Comment by matthiasstraka** [comment]
Thanks, this looks better. Sorry for not fixing it myself as I do not have the time to check for side effects at the moment.
I would also suggest swapping `fclose(worksheet->file);` and `RETURN_ON_ERROR(err);` in __write_worksheet_files_ and maybe call `zipCloseFileInZip(self->zipfile);` in the error paths of __add_file_to_zip_ or clean up zipfile in an approriate way.

**Comment by jmcnamara** [comment]
> I would also suggest swapping `fclose(worksheet->file);` and `RETURN_ON_ERROR(err);` in __write_worksheet_files_ and maybe call `zipCloseFileInZip(self->zipfile);` in the error paths of __add_file_to_zip_ or clean up zipfile in an approriate way.

Good suggestions. I'll look into that.

**Comment by jmcnamara** [comment]
I've force pushed an updated version onto the same branch: 2c8cf48

Try it out for your failing test case if you get a chance.

**Comment by matthiasstraka** [comment]
I tested you commits and can happily report that both the current temporary file and the xlsx-zip file are closed when my disk runs full. Thus, I can delete the file after writing failed and no temporary files stay around. This issue is fixed for me.

**Comment by jmcnamara** [comment]
Cool thanks for the feedback @matthiasstraka 

I'll do a bit more testing and merge it up to main.

**Comment by jmcnamara** [comment]
@matthiasstraka Thanks for testing.

There were still some possible, but unlikely, paths that could return an error without a cleanup. I think all of them are covered now.

When you get a chance can you test once more with the code on the same branch: 487628e

No rush.

**Comment by jmcnamara** [comment]
Fixed and merged to main. Thanks for the report.
