### ISSUE TITLE
Feature request: support cmake import with sub_directory

### ISSUE THREAD

**Issue by ANaumann85** [jmcnamara/libxlsxwriter#318]
I would like to add the library in cmake as a subdirectory with a simple
```[cmake]
add_subdirectory(libxlsxwriter )
```
call.

But at the release 1.0.0 (and master too), that does not work directly. Because in your [CMakeLists.txt, line 97](https://github.com/jmcnamara/libxlsxwriter/blob/59e15dd3ac79a6f0e11f8427cdd236354e4250bd/CMakeLists.txt#L97)  the variable "PROJECT_NAME" is set as a cache variable. That means
  * if the variable was set as cache variable before, the content will not be changed. Therefore your library gets the corresponding.
  * if the variable was set as non-cache variable, it changes between different cmake runs:
    1. In the first run, you add the library with name xlsxswriter
    2. starting from the second run, you add the library under the name of the surrounding project

**Comment by jmcnamara** [comment]
@evanmiller or @Alexhuszagh Does this CMake change seem reasonable?

**Comment by evanmiller** [comment]
@jmcnamara I am not familiar enough with CMake variables to offer an opinion here.

**Comment by ANaumann85** [comment]
would further comments or links to the documentation help?

**Comment by jmcnamara** [comment]
@ANaumann85 Yes. Any additional explanation would be good. I don't really understand what the issue is.

**Comment by ANaumann85** [comment]
I created a small [working example](https://github.com/ANaumann85/example-for-libxlsxwriter-issue-318). 

The example imports the libxsxwriter as a sub directory and tries to compile a copy of your demo.c. That works fine, as long as one runs cmake only once. 

But after a second cmake run, the target for the library xlsxwriter gets another name, the demo looses the relation to the library and therefore it looses the include path to the libxslxwriter.
