### ISSUE TITLE
Feature request: worksheet_conditional_formatting()

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#32]
Add `worksheet_conditional_formatting()` function like the Python XlsxWriter Worksheet method `conditional_formatting()`.
See http://xlsxwriter.readthedocs.io/working_with_conditional_formats.html
- Difficulty: 4 (Easy 1 - 5 Hard)
- Priority: 2 (High 1 - 5 Low)

Add +1 as a comment to vote for this feature and to get an update when it is implemented.

If you would like to make a donation to accelerate this feature you can do so via [PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ATE9EFWNF7PBJ) or contact me [directly](jmcnamara@cpan.org). Currently $0 of $800.

**Comment by Diddlik** [comment]
+1

**Comment by Diddlik** [comment]
Hello, is it known when this feature is finished?
It is the last thing, what I'm missing in this library.
BR Pavel

**Comment by jmcnamara** [comment]
There is no planned date for this. It is on the shorter todo list but it is also non-trivial and I don't have a lot of time at the moment.

You will get an update on this issue when there is something new.

**Comment by trikkegitaar** [comment]
+1

**Comment by thdankert** [comment]
+1

**Comment by spulchtopek** [comment]
+1

**Comment by jmcnamara** [comment]
Since I've had a few requests about this I've added a note about making donations to prioritize this feature. See the Feature Request on GitHub.

**Comment by Tangjiahui26** [comment]
> Since I've had a few requests about this I've added a note about making donations to prioritize this feature.

That'd be great.
Conditional formatting is also an important feature for xlsxwriter Python module.

**Comment by romul** [comment]
+1
Is there any news on this issue?

**Comment by TricksterGuy** [comment]
+1 on this. However...

 I couldn't wait, so I forked and implemented enough of the code just to support my use case. I used the python version of this library as a guide.

If its okay with you... I would be fine with finishing the implementation, cleaning up the code, and adding unit tests for it and submitting a pull request. 

If we can get an API hammered down (there appears to be a ton of different conditional format options and flavors) then I can continue.

**Comment by jmcnamara** [comment]
@TricksterGuy Thanks for the suggestion and sorry for not replying sooner.


I'm going to pass on collaborating on this, at this point, since I need to work on the other items on the [Roadmap](https://github.com/jmcnamara/XlsxWriter/issues/653) in order (conditional formatting is third on the current list). Also, I need to work through my process for implementing a feature in the same way that I always do. I'll ping back into this thread once I have started on  it. Thanks. -- John

**Comment by jmcnamara** [comment]
I'm closing this feature request and replacing it with #302 so as not to spam people who subscribed to this feature request three years ago. Anyone who is still interested in this feature can +1/subscribe to #302.

**Comment by jmcnamara** [comment]
I've added some information about work in progress code for conditional formatting in #302, if anyone is interested in trying it.

**Comment by jmcnamara** [comment]
This feature is now on master for anyone who wants to try it. Docs are here: http://libxlsxwriter.github.io/working_with_conditional_formatting.html

**Comment by jmcnamara** [comment]
This feature is now available in version 1.0.0 of libxlsxwriter.
