### ISSUE TITLE
Compile libxlsxwriter for iOS applications

### ISSUE THREAD

**Issue by ChineseRoyalStar** [jmcnamara/libxlsxwriter#321]
May i know if this lib can be used for the compile of iOS application? Any special setup is needed if it can be integrated into iOS project. Looking forward to your reply, thanks!

**Comment by jmcnamara** [comment]
For iOS and macOS the easiest way to use libxlsxwriter is via CocoaPods. See the following section of the docs:

http://libxlsxwriter.github.io/getting_started.html#gsg_macos
