### ISSUE TITLE
Fuzzing issues: help needed

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#323]
There are 2 fuzzing issues that have been reported:

- #312 heap-buffer-overflow in utility.c:461:12
- #313 stack-buffer-overflow in worksheet_insert_image_buffer_opt 

I've closed the originals to merge them into this single amalgamated issue but you can see the details in the links.

I'm looking for someone to:

- Reproduce the issues
- Propose a fix for each and, after discussion, implement it.

**Comment by ANaumann85** [comment]
I looked at the buffer-overflow in issue #313 . In that example, the user creates a buffer on the heap, but gives the wrong buffer size to the function "worksheet_insert_image_buffer". At that point, you have very small chances to detect that mistake. In my optinion, the issue #313 is not a bug in the library, but a wrong usage.

**Comment by ANaumann85** [comment]
The issue #312 is a bit delicate and consists of two problems:

1. It seems, that you rely on the null terminator of a string. For example in the [file worksheet.c](https://github.com/jmcnamara/libxlsxwriter/blob/9aa3d73a5bd1f18d6777f01d4652ca19940cd0e0/src/worksheet.c#L6673) is a check for the end of the  string using `!*string`. That works only, if your string is really terminated by a 0. But if you get a zero-length array without the null-terminator, then the test does not work. 

2. the function `lxw_utf8_strlen` also relies on the zero-terminated string. If your string is not zero-terminated, [the loop](https://github.com/jmcnamara/libxlsxwriter/blob/9aa3d73a5bd1f18d6777f01d4652ca19940cd0e0/src/utility.c#L461) will not stop at the end of the string, but some where else. 

Both problems arise, if you got wrongly terminated strings. It is not clear to me, how one should handle these errors. In my opinion, these are user errors.

**Comment by jmcnamara** [comment]
@ANaumann85 Thank you, I appreciate your analysis. Could you also add those comments to the issues (even if they are marked as closed). Thanks once more.

**Comment by jmcnamara** [comment]
Closing this merged issue. Any further discussion should happen in the individual bug reports.
