### ISSUE TITLE
Feature request: C++ header

### ISSUE THREAD

**Issue by reinder** [jmcnamara/libxlsxwriter#324]
Hi All,

I'm currently working on some C++ code using libxlsxwriter which is great by the way! Thanks!

As I'm writing some wrapper functions to make life easier when using it from C++, I was wondering if there are any plans for developing a C++ header only wrapper?

If  there is a demand for a C++ wrapper, I'm willing to contribute to that.

**Comment by jmcnamara** [comment]
Hi,

> I was wondering if there are any plans for developing a C++ header only wrapper?

There is a CPP wrapper/lib called libxlsxwriterpp  (https://github.com/Alexhuszagh/libxlsxwriterpp).

John

**Comment by reinder** [comment]
Thx, I'll look into that :)
