### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by willm132** [jmcnamara/libxlsxwriter#325]
Will this project get SPM support in the future? It appears to still me maintained.

**Comment by jmcnamara** [comment]
Hi Will,

It could be added. I don't know what is involved and I don't actually use Swift but maybe someone else will step in to do it. There is already support for Cocoa Pods: https://libxlsxwriter.github.io/getting_started.html#gsg_cocoapods

**Comment by jmcnamara** [comment]
Closing. I recommend using Cocoa Pods instead.

**Comment by mariohahn** [comment]
As the time goes by and SPM is more and more common, I think we could reopen that issue and add SPM?
