### ISSUE TITLE
Releasing windows binaries 

### ISSUE THREAD

**Issue by mantielero** [jmcnamara/libxlsxwriter#331]
It would be helpful having a .zip with all the binaries that are needed in Windows.

Amazing library by the way.

**Comment by taozuhong** [comment]
```text
mingw32/mingw-w64-i686-libxlsxwriter 1.0.0-1
    A C library for creating Excel XLSX files (mingw-w64)
mingw64/mingw-w64-x86_64-libxlsxwriter 1.0.0-1
    A C library for creating Excel XLSX files (mingw-w64)
ucrt64/mingw-w64-ucrt-x86_64-libxlsxwriter 1.0.0-1
    A C library for creating Excel XLSX files (mingw-w64)
clang64/mingw-w64-clang-x86_64-libxlsxwriter 1.0.0-1
    A C library for creating Excel XLSX files (mingw-w64)
```

**Comment by mantielero** [comment]
I am not that familiar with mingw, but I managed to install `msys2` and `mingw-w64-x86_64-libxlsxwriter`. So I got: `libxlsxwriter.dll`. 

Outside of mingw, I am creating a binary. When I run it I get:
```
λ myfile.exe
could not load: libxlsxwriter.dll
(bad format; library may be wrong architecture)
```
But I think I am in the right architecture. In msys2:
```
$ file myfile.exe
sar.exe: PE32 executable (console) Intel 80386, for MS Windows
$ file libxlsxwriter.dll
libxlsxwriter.dll: PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows
```

**Comment by jmcnamara** [comment]
> It would be helpful having a .zip with all the binaries that are needed in Windows.

That is a good suggestion but I don't want to get involved with compiling and distributing DLLs and then dealing with the inevitable problems when they don't work because they are installed in the wrong place.

So this is a pass from me. Closing.

**Comment by RaFaeL-NN** [comment]
I compile Windows binaries every 5-10 releases. You can download it here: https://sourceforge.net/projects/libxlsxwriter/
