### ISSUE TITLE
Assign the result of a formula to a variable

### ISSUE THREAD

**Issue by sapomuyverde** [jmcnamara/libxlsxwriter#334]
It is possible to assign the result of a formula to a variable and then use that variable, for example: I do something like this:

worksheet_write_formula(worksheet, lin, 8, "=SUM(I5:I10), numberRightTotal) --> (total sales, to say)
Then make use of the "variable", without repeating the formula, something like this:
worksheet_write_number(worksheet,  lin+10, 8, total sales, numberRight )

Any idea how to solve in this way.

Regards,
Javier

**Comment by jmcnamara** [comment]
Unfortunately that isn't possible. Libxlsxwriter doesn't evaluate the formula in any way so there isn't any results to return/store.

**Comment by sapomuyverde** [comment]
Thank you for your answer and for your time.
