### ISSUE TITLE
VERSION_GREATER_EQUAL not recognized by CMake 3.6

### ISSUE THREAD

**Issue by evanmiller** [jmcnamara/libxlsxwriter#336]
I get the following error attempting to configure libxlsxwriter 1.0.6 using CMake 3.6.3:

```
CMake Error at CMakeLists.txt:114 (if):
  if given arguments:

    "3.6.3" "VERSION_GREATER_EQUAL" "3.12"

  Unknown arguments specified
```

A similar issue with another project was reported here: https://github.com/glfw/glfw/issues/1584

I suggest using a combination of VERSION_GREATER and VERSION_EQUAL to achieve the same result. Happy to open a pull request.

**Comment by jmcnamara** [comment]
That's Evan. I'll look into fixing that.

**Comment by jmcnamara** [comment]
Thanks for the report. Fixed on main.

**Comment by evanmiller** [comment]
@jmcnamara Thanks!
