### ISSUE TITLE
Cell Text Overlapping

### ISSUE THREAD

**Issue by willm132** [jmcnamara/libxlsxwriter#338]
Is it possible to make the text it one row overlap the other rows. This is a really long text title here and I want it to get all the way to the right side of the row, but it is being cut off at column B

<img width="951" alt="Screen Shot 2021-06-14 at 2 25 41 PM" src="https://user-images.githubusercontent.com/47162632/121940909-9e16ba00-cd1c-11eb-8b70-6bd5de430d75.png">

**Comment by jmcnamara** [comment]
The general answer to "how do I do something with Libxlsxwriter" is "how would you do it in Excel"?

One way would be to merge the cells like this: [worksheet_merge_range()](https://libxlsxwriter.github.io/worksheet_8h.html#ad5a2a09ec65c0f286b756235c7327225) or wrap the text in the cells like this: [format_set_text_wrap()](https://libxlsxwriter.github.io/format_8h.html#a56d55dd9257d8f0645c62b296d2c196d)
