### ISSUE TITLE
worksheet_merge_range to display numerical data

### ISSUE THREAD

**Issue by sapomuyverde** [jmcnamara/libxlsxwriter#344]
There is some restriction in which I cannot use worksheet_merge_range to combine columns and put numeric data?, I mean,
I have tried to put a numeric data: something like this:

worksheet_merge_range(worksheet,  6,  11,  6, 14, totalCtes, numberWithoutDecimalCenter)

and it didn't work, so I had to convert the variable to string and it worked, is it expected behavior?.

Regards,
Javier

**Comment by jmcnamara** [comment]
> and it didn't work, so I had to convert the variable to string and it worked, is it expected behavior?.

Yes. 

From the docs for [worksheet_merge_range](https://libxlsxwriter.github.io/worksheet_8h.html#ad5a2a09ec65c0f286b756235c7327225):

> The `worksheet_merge_range()` function writes a char* string using `worksheet_write_string()`. In order to write other data types, such as a number or a formula, you can overwrite the first cell with a call to one of the other write functions. The same Format should be used as was used in the merged range.

```C
// First write a range with a blank string.
worksheet_merge_range (worksheet, 1, 1, 1, 3, "", format);
 
// Then overwrite the first cell with a number.
worksheet_write_number(worksheet, 1, 1, 123, format);
```

**Comment by sapomuyverde** [comment]
I didn't check the docs, thanks for clarifying.
