### ISSUE TITLE
Test failure on i686 and armv7hl

### ISSUE THREAD

**Issue by manisandro** [jmcnamara/libxlsxwriter#347]
We are hitting the following test failure on Fedora/i686:

    TEST 42/381 utility:test_unixtime [FAIL]
      ERR: /builddir/build/BUILD/libxlsxwriter-RELEASE_1.1.0/test/unit/utility/test_datetime_to_excel.c:644
    	expected 0,
    	got      49711.3

See [1] for full build.log, and root.log containing version of compiler etc.

[1] https://koji.fedoraproject.org/koji/taskinfo?taskID=72411207

**Comment by manisandro** [comment]
Same on armv7hl

**Comment by jmcnamara** [comment]
Thanks for the report. I'll look into it.

Could you add a link to the armv7hl logs.

**Comment by jmcnamara** [comment]
Also, where can I get an iso for fedora 35 for testing?

**Comment by manisandro** [comment]
Here is the latest rawhide compose:

https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20210722.n.0/compose/Everything/x86_64/iso/Fedora-Everything-netinst-x86_64-Rawhide-20210722.n.0.iso

**Comment by jmcnamara** [comment]
@manisandro could you add the output for the following from one or both of those systems:

```
echo | gcc -E -xc -include 'time.h' - | grep time_t | grep typedef
```

**Comment by manisandro** [comment]
Here is a scratch build which also executes the command you posted [1]. For the arches of interest, you'll find the output in the respective build.logs.

[1] https://koji.fedoraproject.org/koji/taskinfo?taskID=72727811

**Comment by jmcnamara** [comment]
@manisandro Thanks for that.

I've pushed a fix for this to the main branch if you could test it.

**Comment by manisandro** [comment]
Looks good, thanks [1]!

[1] https://koji.fedoraproject.org/koji/taskinfo?taskID=72771694
