### ISSUE TITLE
No function to merge cells in Swift

### ISSUE THREAD

**Issue by CypriotUnknown** [jmcnamara/libxlsxwriter#362]
Hello,

First of all, thank you for this amazing library. I cannot find the function on the worksheet class to merge cells. I am assuming this is only the case with the Swift version of the library.

Please help if I'm missing something out.

Thanks..

**Comment by jmcnamara** [comment]
For clarity which Swift version of the library are you using?

**Comment by CypriotUnknown** [comment]
Hello. It's 0.2.0

**Comment by jmcnamara** [comment]
Ok. But which library are you using. Can you provide a link to it.

**Comment by CypriotUnknown** [comment]
https://github.com/damuellen/xlsxwriter.swift

**Comment by jmcnamara** [comment]
Then it is probably best to open the issue there. There isn't any issue with merge ranges in the C library. You can @ me into the new issue. I'll close this one here.

**Comment by CypriotUnknown** [comment]
Ok thanks. I did open the issue but I can't @ you there.
