### ISSUE TITLE
Utility.h macros not available with cocoapods in iOS

### ISSUE THREAD

**Issue by tekayamarouene** [jmcnamara/libxlsxwriter#367]
Hello team,

I am using libxlsxwriter with cocoapods. 
My problem is that i can't use macros in the Utility.h file like CELL("A1").
I am using OS = iOS and libxlsxwriter 1.1.4 with swift language.
For the sample code you can use this repository:
https://github.com/FrankenApps/LibXlsxWriterSwiftSample

Thank you

**Comment by jmcnamara** [comment]
Isn't that because C macros aren't available in Swift:

[Using Imported C Macros in Swift](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/using_imported_c_macros_in_swift)

> C macros that are more complex than simple constant definitions have no counterpart in Swift.

**Comment by tekayamarouene** [comment]
> Isn't that because C macros aren't available in Swift:
> 
> [Using Imported C Macros in Swift](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/using_imported_c_macros_in_swift)
> 
> > C macros that are more complex than simple constant definitions have no counterpart in Swift.

yes this is right. Thank you for your quick response.
