### ISSUE TITLE
There is no function to change axis type: Automatic, Text, Date

### ISSUE THREAD

**Issue by aa4re** [jmcnamara/libxlsxwriter#376]
Hello,
In the third image that appears in this tutorial
https://libxlsxwriter.github.io/working_with_charts.html
The axis type configuration setting appears in the displayed window:
Horizontal axis type : automatic, Text, Date
What I want to know is how to programmatically set the axis type to Text instead of Automatic using the libxlsxwriter library
I have the problem shown on this page:
https://es.extendoffice.com/documents/excel/3242-excel-show-milliseconds.html
Thank you very much

**Comment by aa4re** [comment]
![imagen](https://user-images.githubusercontent.com/18484541/183837451-e0913b2d-7654-40ca-9fe6-5bdbdeaa994e.png)

**Comment by jmcnamara** [comment]
That isn't currently supported in the C version. It is supported in the Python version:

https://xlsxwriter.readthedocs.io/chart.html?highlight=text_axis#chart-set-x-axis

I could look at adding it to the C version **however** it is a feature that is rarely used in practice and I don't know if it will actually fix any real world problem that you have. In addition it is easily replicated with the existing APIs by setting a text format on the data the chart is graphed from.

But let's take a step back. What is the issue that you are having. the doc you linked to talks about setting millisecond precision. Is that what you are trying to do?

**Comment by aa4re** [comment]
Thank you very much for your reply,
I have made a mistake when putting the link of the problem that I have, the correct link is:
https://www.extendoffice.com/documents/excel/4203-excel-chart-with-date-and-time-on-x-axis.html

The library generates this graph, where the X axis type is set to automatic.

![imagen](https://user-images.githubusercontent.com/18484541/183885674-b64a51aa-2849-475c-8764-75cd5708a85e.png)

The correct graph that I want to show is the following, the only thing that changes is that now I have manually changed the type of the x-axis to Text.

![imagen](https://user-images.githubusercontent.com/18484541/183885772-a6c745ec-4cfd-4c90-939e-6ee798e8105f.png)


It is very important to be able to change the type of axis since anyone who works with time data will encounter this problem.
it's possible?

**Comment by jmcnamara** [comment]
Ok. Could you add a small working example (to avoid confusion) and I will look at adding the feature.

**Comment by jmcnamara** [comment]
Just a reminder that without a small working example I cannot evaluate this issue and will close it after a week.

**Comment by jmcnamara** [comment]
Closing due to lack of response.
