### ISSUE TITLE
对于其他语言编码如何操作呢，打开后显示数据损坏，英文字符串是没有问题

### ISSUE THREAD

**Issue by AlongsCode** [jmcnamara/libxlsxwriter#377]
How to manipulate encodings in other languages? After opening, it shows that the data is corrupted.
English is no problem. My excel cannot be opened correctly when I use Chinese

**Comment by jmcnamara** [comment]
The Excel file format only supports UTF-8. You will need to convert your encoding to that format.

**Comment by AlongsCode** [comment]
谢谢
