### ISSUE TITLE
Date Time format from System

### ISSUE THREAD

**Issue by snagytx** [jmcnamara/libxlsxwriter#378]
Hello,

Is it possible to add date/time fields with the format getting pulled from the system? I don't want to set the format manually, I just want to mark the field as date/time field.

The date/time fields should be updated automatically when opened in different system date/format settings. Us us MM/DD/YYYY while EU is DD/MM/YYYY.

Thanks.

**Comment by jmcnamara** [comment]
> The date/time fields should be updated automatically when opened in different system date/format settings. Us us MM/DD/YYYY while EU is DD/MM/YYYY.

Excel has some built in formats that change with the system:

![Screenshot 2022-09-23 at 15 36 03](https://user-images.githubusercontent.com/94267/192002872-e12198ae-bd0c-425d-9924-b8370646b126.png)

You can enable these with libxlsxwriter using the [`format_set_num_format_index()`](http://libxlsxwriter.github.io/format_8h.html#a688aa42bcc703d17e125d9a34c721872) function:


```C
      format = workbook_add_format(workbook);
      format_set_num_format_index(format, 14); // m/d/yy
```

**Comment by snagytx** [comment]
Yes, I was about to test using `format_set_num_format_index`
