### ISSUE TITLE
Feature request: worksheet_write_comment()

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#38]
Add `worksheet_write_comment()` function like the Python XlsxWriter Worksheet method `write_comment()`.
See https://xlsxwriter.readthedocs.io/working_with_cell_comments.html
- Difficulty: 5 (Easy 1 - 5 Hard)
- Priority: 3 (High 1 - 5 Low)

Add +1 as a comment to vote for this feature and to get an update when it is implemented.

If you would like to make a donation to accelerate this feature you can do so via [PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ATE9EFWNF7PBJ) or contact me [directly](jmcnamara@cpan.org). Currently $0 of $800.

**Comment by scottyd57** [comment]
I would be willing to look into this feature.  I need this to process my excel files.  Let me know if I can help.

**Comment by jmcnamara** [comment]
> Let me know if I can help.

Thanks for the offer. Libxlsxwriter is mainly a port of the Python and Perl libraries that I wrote. I have the tests, docs and an API so in general I don't need help.

What I do need is time to work on it and I've had even less of that recently than usual.

**Comment by jmcnamara** [comment]
Since I've had a few requests about this I've added a note about making donations to prioritize this feature. See the Feature Request on GitHub.

**Comment by LifeToDevice** [comment]
+1

**Comment by sevenyang2019** [comment]
can libxlsxwriter support the function of write_comments now ?

**Comment by jmcnamara** [comment]
@sevenyang2019 No. This issue would be closed if it was completed or updated if there was some progress.

**Comment by jmcnamara** [comment]
The initial version of comment support is available on the vml branch. You can now add comments to libxlsxwriter cells as follows:

```C
#include "xlsxwriter.h"

int main() {

    lxw_workbook  *workbook  = workbook_new("comments1.xlsx");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);

    worksheet_write_string( worksheet, 0, 0, "Hello" , NULL);

    worksheet_write_comment(worksheet, 0, 0, "This is a comment");

    return workbook_close(workbook);
}
```

And get output like this:

![comments1](https://xlsxwriter.readthedocs.io/_images/comments1.png)

It only works when lxw_workbook_options constant_memory = LXW_FALSE (which is the default).

I'll be adding more options and documentation in the next week or so but if anyone is feeling brave and would like to try it let me know how you get on.

The eventual functionality will be like XlsxWriter: https://xlsxwriter.readthedocs.io/working_with_cell_comments.html

**Comment by jmcnamara** [comment]
I've added some additional functionality, more tests, and merged this up to master. Docs and further examples to be added.

**Comment by jmcnamara** [comment]
The final version of this feature is now on master with docs and examples if anyone wants to try it. I will push it out to the packagers in the next few days.

**Comment by jmcnamara** [comment]
Upstream in version 0.92/0.93.
