### ISSUE TITLE
Add a function to insert glb 3D model. Similar to worksheet_insert_image();

### ISSUE THREAD

**Issue by slugdev** [jmcnamara/libxlsxwriter#380]
Newer versions of excel support 3D models. Having a function to insert glb files would be great. Example attached
[glb_example.xlsx](https://github.com/jmcnamara/libxlsxwriter/files/9668084/glb_example.xlsx)

**Comment by jmcnamara** [comment]
Realistically I think this is unlikely to be added. It is the wrong combination of difficult and not commonly requested.
