### ISSUE TITLE
Conditional format is not works as expected when type is LXW_CONDITIONAL_TYPE_TOP or LXW_CONDITIONAL_TYPE_BOTTOM

### ISSUE THREAD

**Issue by informationsea** [jmcnamara/libxlsxwriter#386]
Always top 10 value or top 10% of cells are matched to condition, even if value is other than 10. 

I confirmed this problem in latest main branch and 1.1.4 release.

**Comment by jmcnamara** [comment]
Thanks for the report and the fix. I fixed it myself and modified one of the test cases (which should have been more general to catch it in the first place).

Is see that you are maintaining a Rust port/wrapper of libxlsxwriter. It looks good and very complete.

I'm currently working on a pure Rust port of xlsxwriter as well. If you have any suggestions on that let me know.

Keep up the good work and let me know if you find anything else like this.

-- John
