### ISSUE TITLE
Feature Request: Swift Package Manager support

### ISSUE THREAD

**Issue by bvirlet** [jmcnamara/libxlsxwriter#390]
Thanks for building this library. I see that you have added CocoaPods support. Do you have any plans for, or would you be interested in Swift Package Manager support?

**Comment by jmcnamara** [comment]
I don't use Swift so I don't have plans for it. I am open to adding it to the project if maintaining it is similar to the CocoaPods support, for example.

This question was asked previously at #325 

The is also these resources:

- https://github.com/FrankenApps/LibXlsxWriterSwiftSample
- https://github.com/damuellen/xlsxwriter.swift

**Comment by jmcnamara** [comment]
@FrankenApps You helped out previously with the libxlsxwriter Swift sample app. Is this something you could help with?

**Comment by FrankenApps** [comment]
I would be open to look into this, because I think the ecosystem is slowly transitioning towards Swift Package Manager. 
However I can sadly not make any commitment to a timeframe at the moment and this will likely take several months from my side to get around to.

**Comment by jmcnamara** [comment]
Merged to main. Thanks. Closing.
