### ISSUE TITLE
[vcpkg] license

### ISSUE THREAD

**Issue by Teles1** [jmcnamara/libxlsxwriter#392]
I submitted a pull request and they recommended updating the license agreement in there in order to make it complete. I thought it was Free BSD but the header files mention something else. Perhaps could you submit a pull request to vcpkg updating it? 
Here is the PR I sent-> https://github.com/microsoft/vcpkg/pull/29401

**Comment by FrankXie05** [comment]
@Teles1 I don't think the upstream licenses did anything wrong, they just mentioned all the licenses involved in the files they used. This is normal behavior. If you want to add `Free BSD` licenses, you can suggest that they separate all licenses.
Take it out and perfect it. 🧐

**Comment by jmcnamara** [comment]
Folks I would prefer the license field to say FreeBSD or link to the license file. 

I put a lot of work into clarifying the main license in the [docs](https://libxlsxwriter.github.io/license.html) and the licences of all of the optional sub-components. I've also detailed how any of the sub-licensed components can be [compiled in/out](http://libxlsxwriter.github.io/getting_started.html#gsg_compilation_options). The issue there, from a `vcpkg` point of view, is that adding those additional compilation options to compile out the embedded libraries and replace them with system libraries will make the compilation more error prone (in particular openssl).

But either way a license file of `null` feels sub-optimal.

**Comment by Teles1** [comment]
Oh right. Fair enough. I tried putting in OpenBSD as the license in there in first place but can't merge it in hence the mixture of licenses. And I have to agree with @jmcnamara my nightmare when I was getting started with c++ was libraries with multiple dependencies and back then i didn't know how to put them together without having to compile every single one with MSVC.

**Comment by jmcnamara** [comment]
@Teles1 do you know what are the allowed licences in that field? The specific license for libxlsxwriter is: BSD 2-Clause "Simplified" License. https://spdx.org/licenses/BSD-2-Clause.html

**Comment by jmcnamara** [comment]
I'll answer my own question by reading the [docs](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#license) :-)

> The license of the port. This is an [SPDX license expression](https://spdx.dev/ids/#how), or null for proprietary licenses and other licenses for which one should "just read the copyright file" (e.g., Qt).

So, the licence field should be the SPDX identifier `BSD-2-Clause` or if you feel that isn't complete, I think it is, then set it to `null`.

**Comment by Teles1** [comment]
Let's wait for @FrankXie05 He's the specialist in this case lol. But I did try BSD and then Frank [mentioned this](https://github.com/microsoft/vcpkg/pull/29401#issuecomment-1414702679). Thank you for spending some of your time on this.

**Comment by Teles1** [comment]
To be fair I think there is something else wrong with vcpkg + libxlswriter. I just tried using it and I can't import it on my cmake project even after the fact that I installed it. It can't find it. Works fine on Visual Studio tho.

I tried 
`find_package(xlsxwriter CONFIG REQUIRED)`
and
`find_package(libxlsxwriterCONFIG REQUIRED)`

**Comment by Teles1** [comment]
Yah, it works fine standalone cmake + add_subdirectory. 
`add_subdirectory(libxlsxwriter)

target_link_libraries(excel PRIVATE xlsxwriter)`

Something to do with vcpkg export methodology that I am not familiar with.

**Comment by FrankXie05** [comment]
> @Teles1 do you know what are the allowed licences in that field? The specific license for libxlsxwriter is: BSD 2-Clause "Simplified" License. https://spdx.org/licenses/BSD-2-Clause.html

@Teles1 We respect the choice of the upstream, since the author stated that the specific license is `BSD-2-Clause`, we also allow the license to be added to port `libxlsxwriter`. I will complete this task today. :)



> To be fair I think there is something else wrong with vcpkg + libxlswriter. I just tried using it and I can't import it on my cmake project even after the fact that I installed it. It can't find it. Works fine on Visual Studio tho.
> 
> I tried `find_package(xlsxwriter CONFIG REQUIRED)` and `find_package(libxlsxwriterCONFIG REQUIRED)`

Maybe you missed the `CMAKE_TOOLCHAIN_FILE`.

**Comment by Teles1** [comment]
I'm using vcpkg for other libraries and couldn't get it to work. It may
just be me being dumb too. Thank you sir for your great work

**Comment by FrankXie05** [comment]
@Teles1 For the use of most of the ports provided by vcpkg. Just add two lines of code. :)
The first add `find_package()`, and second link your project: `target_link_libraries(project_name PRIVATE xlsxwriter)`.
