### ISSUE TITLE
A bug in documentation

### ISSUE THREAD

**Issue by Horseechen** [jmcnamara/libxlsxwriter#393]
There is a confusing error in the 7th example in the following code(http://libxlsxwriter.github.io/data_validate_8c-example.html ): `data_validation->validate` should be assigned with a value of `LXW_VALIDATION_TYPE_LIST_FORMULA` rather than `LXW_VALIDATION_TYPE_LIST`. 

original code:
```cpp
    /*
     * Example 7. Limiting input to a value in a dropdown list.
     */
    worksheet_write_string(worksheet,
                           CELL("A15"),
                           "Select a value from a drop down list (using a cell range)",
                           NULL);
 
    data_validation->validate     = LXW_VALIDATION_TYPE_LIST;
    data_validation->value_formula = "=$E$4:$G$4";
 
    worksheet_data_validation_cell(worksheet, CELL("B15"), data_validation);
```

it should be
```cpp
    /*
     * Example 7. Limiting input to a value in a dropdown list.
     */
    worksheet_write_string(worksheet,
                           CELL("A15"),
                           "Select a value from a drop down list (using a cell range)",
                           NULL);
 
    data_validation->validate     = LXW_VALIDATION_TYPE_LIST_FORMULA;
    data_validation->value_formula = "=$E$4:$G$4";
 
    worksheet_data_validation_cell(worksheet, CELL("B15"), data_validation);
```

**Comment by jmcnamara** [comment]
The member name for `data_validation->value_formula` is a little bit confusing but the example is correct. The data validation list comes from a range in the spreadsheet:

![Screenshot 2023-02-14 at 14 25 31](https://user-images.githubusercontent.com/94267/218766788-e66fe7cc-499b-4dc4-b633-609244ddb520.png)

Probably the member should be called something like `value_range` or `value_source` but I was trying to reuse/minimise the number of fields.

**Comment by Horseechen** [comment]
No, the example is wrong. Because the parameter in Example 6 works in Example 7. You may try to change the value in reference cells then you will find that truth.

**Comment by Horseechen** [comment]
By the way, in this page http://libxlsxwriter.github.io/working_with_data_validation.html
`data_validation->validate` is assigned with `LXW_VALIDATION_TYPE_LIST_FORMULA`
![image](https://user-images.githubusercontent.com/19280960/218788613-09661f20-d0ae-4543-ae74-529fac236d7d.png)

**Comment by Horseechen** [comment]
By the way, in this page http://libxlsxwriter.github.io/working_with_data_validation.html
`data_validation->validate` is assigned with `LXW_VALIDATION_TYPE_LIST_FORMULA`
![image](https://user-images.githubusercontent.com/19280960/218788613-09661f20-d0ae-4543-ae74-529fac236d7d.png)

**Comment by jmcnamara** [comment]
Ok, thanks. I get it now. 

You are right the example is incorrect. The validation type should be `LXW_VALIDATION_TYPE_LIST_FORMULA`.

**Comment by Horseechen** [comment]
I would like to say thank you because the libxlsxwriter is really useful. Thank you for your sharing.

**Comment by jmcnamara** [comment]
Fixed on main and the documentation has been updated.
