### ISSUE TITLE
Feature Request: Add zig package

### ISSUE THREAD

**Issue by kassane** [jmcnamara/libxlsxwriter#401]
The purpose of this proposal is to allow Zig developers to use libxlsxwriter in their projects without the need for git modules or any other external tool.

`zig-pkg` is still experimental and will be available in the v0.11.0 release - expected at the end of May.

Theoretically it works similar to `go mod` or `fetchContent (cmake)`.

**Comment by kassane** [comment]
@jmcnamara ,

My upgrade with all deps, see:
 - Windows: https://github.com/kassane/libxlsxwriter/actions/runs/4959441372/jobs/8873814165#step:4:1
 
Still don't understand why GH-action on linux and macOS are getting error during download of zlib (zig-pkg).
After testing on my linux machine, it worked the same on the Windows machine mentioned above!
https://github.com/kassane/libxlsxwriter/actions/runs/4959441372

https://github.com/jmcnamara/libxlsxwriter/blob/58dde43713d3d51fdd3fe65db67f3af6afbcc272/build.zig.zon#L1-L10

changelog: https://github.com/jmcnamara/libxlsxwriter/compare/main...kassane:libxlsxwriter:pkg-update

**Comment by jmcnamara** [comment]
@kassane 

The libxlsxwriter zig CI/GitHub action is failing on main. It looks like a CI issue since the code hasn't changed. Could you have a look.

**Comment by kassane** [comment]
> [@kassane](https://github.com/kassane)
> 
> The libxlsxwriter zig CI/GitHub action is failing on main. It looks like a CI issue since the code hasn't changed. Could you have a look.

By default, CI get latest release v0.14.1. update CI `setup-zig@v2`.

Since zig v0.14.1 tarball changes rename. Old: <os>-<arch>.<ext> to  <arch>-<os>.<ext>

**Comment by jmcnamara** [comment]
> By default, CI get latest release v0.14.1. update CI `setup-zig@v2`.

Thanks. That worked.
