### ISSUE TITLE
Unit tests won't run when using Microsoft C compiler

### ISSUE THREAD

**Issue by HolgiHo** [jmcnamara/libxlsxwriter#413]
When using the Microsoft C compiler (Visual Studio / VS Build Tools), the unit test registration in `ctest.h` does not work (and has apparently never worked before). The unit test executable `xlsxwriter_unit.exe` simply executes zero test cases.

Reason: The test case registration macro `CTEST(...)` works by adding instances of `struct ctest` to a special linker segments (on *nix platforms). When using MSC, the structs are added to the normal data segment and thus cannot be found by the test case driver in `ctest_main`.

Solution: Use linker segments also in MSC. This requires a special syntax, as linker segments specifications are not portable between platforms.

PR will follow shortly.

**Comment by jmcnamara** [comment]
Thanks for the report.

> Solution: Use linker segments also in MSC. 

There is an upstream PR to fix this in `ctest` but it doesn't seem to have been merged: https://github.com/bvdberg/ctest/pull/35

I'd prefer not to include local fixes for this issue so I think I will pass on this.

The PR also includes some other fixes: "fix build error in VS: use const char* in struct lxw_header_footer_options".  Any idea why this doesn't show up in the "CMake on Windows" CI test?

**Comment by HolgiHo** [comment]
### VS build error
The error occurs when compiling the following code in a C++ file, even when xlsxwriter.h uses the extern "C" { ... } declaration.
```
lxw_header_footer_options header_options;
header_options.image_left = "logo_small.png";
```
gives `error C2440: '=': cannot convert from 'const char [15]' to 'char *'`
This works C, so cmake builds don't complain. However, it should be possible to use the struct members also from a C++ implementation file without writing strange things like
```
header_options.image_left = const_cast<char*>("logo_small.png");
```
using `const char*` for image_strings[] in `_worksheet_set_header_footer_image` is not really required as this is always C code, but it's cleaner.

### ctest
I saw ctest.h was already modified (see its git log) to "work" on Windows. So I wondered that it compiles, but no tests are found. 

IMHO, in the short term, working unit tests under Windows are important for libxlsxwriter development. The ctest repository seems to be a bit abandoned, so I doubt if the PR you mentioned will ever be merged into ctest, also because there are lots of guesses and no clear statements how the MS compiler works. (The source of truth is here I think: https://devblogs.microsoft.com/oldnewthing/20181107-00/?p=100155 and the two follow-up articles.)

I mean, if ctest once supports MSVC, you can simply copy the latest version from there and you're done.

**Comment by jmcnamara** [comment]
> The error occurs when compiling the following code in a C++ file, even when xlsxwriter.h uses the extern "C" { ... } declaration.

Thanks for flagging this. I'll look into that separately. I have [a simple test](https://github.com/jmcnamara/libxlsxwriter/blob/main/test/cpp/test_compilation.cpp) to ensure CPP compatible `const char*` in the APIs but it doesn't flag them in structs or assignments so I'm going to work on that for a bit to see if I can have better automated tests.

After that I'll look at the unit test part of the PR. I just need to figure out if I should upgrade to the latest `ctest.h` before adding this fix.

**Comment by jmcnamara** [comment]
I've added a fix to change all the public "char*" members to "const char*". You can try it when you get a chance.

I'll look into the `ctest.h` issue next. It is likely that I will upgrade to the latest version. The previous version I used with from 2014 with local fixes over time.
