### ISSUE TITLE
libxlsxwrite can only write data to tables, but not read data from tables?

### ISSUE THREAD

**Issue by zhjr2019** [jmcnamara/libxlsxwriter#421]
libxlsxwrite can only write data to tables, but not read data from tables?

**Comment by slw287r** [comment]
You can use [xlsxio](https://github.com/brechtsanders/xlsxio)'s `xlsxio_read` to read from XLSX file.

BTW xlsxio does not support multiple sheet writing as libxlsxwrite.

**Comment by jmcnamara** [comment]
> libxlsxwrite can only write data to tables, but not read data from tables?

That is correct. Libxlsxwriter is a library for writing files only.
