### ISSUE TITLE
Using this lib in for another computer language

### ISSUE THREAD

**Issue by fperillo** [jmcnamara/libxlsxwriter#422]
I'm helping to create an interface to this lib to be used by another computer programming language.

In this moment the full libxlswriter library is included and it means there are some dirs that are useless and also confusing for our users, like test and examples.

Is it "legal" to include in our project only parts of your library? 

Thank you

**Comment by jmcnamara** [comment]
> Is it "legal" to include in our project only parts of your library?

Yes, if you maintain the copyright headers and can comply with the Licences: https://github.com/jmcnamara/libxlsxwriter/blob/main/License.txt

Note there are already several language ports of libxlsxwriter:
https://github.com/search?q=libxlsxwriter&type=repositories

**Comment by fperillo** [comment]
Thank you.

I will only remove some dirs, "test", "docs", "dev", "examples".

Our language needs an external c compiler.... it actually takes the source code and translate it to c, that is then compiled with one of the supported c compiler on one of the supported operating system: there are tens of combinations, also for very niche c compilers.

So it is really important to provide source code that can be easily compiled by people that is not proficient in c. It will be compiled by our "make" equivalent.

Thank you for your great project !
