### ISSUE TITLE
Issue: Corrupt file compiled using VS2008 on Windows

### ISSUE THREAD

**Issue by myspace9** [jmcnamara/libxlsxwriter#434]
After libxlaxwriter successfully compiled using VS2008 on the Windows platform, the xlsx file created was opened as a corrupted file. After decompressing the xlsx file and checking the components, it was found that there were errors in the XML content, such as garbled, binary, or missing content

**Comment by myspace9** [comment]
![QQ截图20240311144815](https://github.com/jmcnamara/libxlsxwriter/assets/35983719/c2ace7ec-266d-438d-bb5c-b924a776578b)

**Comment by myspace9** [comment]
this is ".rels "

**Comment by jmcnamara** [comment]
It looks like the file may contain text that UTF-8 which in the only encoding supported by Excel. Could that be the case? What font encoding are you using?

**Comment by myspace9** [comment]
> It looks like the file may contain text that isn't UTF-8 which is the only encoding supported by Excel. Could that be the case? What text encoding are you using?

only i delete emyg_dtoa.c

**Comment by myspace9** [comment]
> > It looks like the file may contain text that isn't UTF-8 which is the only encoding supported by Excel. Could that be the case? What text encoding are you using?
> 
> only i delete emyg_dtoa.c

The problem has been resolved

**Comment by myspace9** [comment]
but，the cell value can not support Chinese，do you have any good suggestions?
Thank you

**Comment by jmcnamara** [comment]
Just to be clear, is the issue resolve and what resolves it?

**Comment by myspace9** [comment]
> Just to be clear, is the issue resolve and what resolves it?

resolving the encoding by adding emyg_dtoa.c and for Chinese, setting the conversion from GBK to UTF8

**Comment by jmcnamara** [comment]
> resolving the encoding by adding emyg_dtoa.c

That is interesting. Do you know why that fixed it? 

The usual reason is that files are corrupted and then fixed by `emyg_dtoa.c` is that floats in the users locale are written with a comma as a decimal point like this: `1234,56`. That happens in German locales. Could that be the case in your locale?
