### ISSUE TITLE
password

### ISSUE THREAD

**Issue by TThityou** [jmcnamara/libxlsxwriter#436]
# How to create a file with a password?

When the document is opened by execl, it will be prompted for a password.I did not find how to set the password to the file in this project.Thank you for your answer.

**Comment by jmcnamara** [comment]
Libxlsxwriter only supports [worksheet passwords](https://libxlsxwriter.github.io/worksheet_8h.html#a1b49e135d4debcdb25941f2f40f04cb0) which don't enable encryption and offers very weak protection.

To protect the entire workbook you could use [msoffice-crypt](https://github.com/herumi/msoffice). It has a command line application but also a library.
