### ISSUE TITLE
Still Tagging Releases?

### ISSUE THREAD

**Issue by bdkjones** [jmcnamara/libxlsxwriter#437]
The last tagged release of `libxlswriter` is from 2022. The commit history shows a bunch of work since then, including some important fixes for overflows and other bugs.

Is @jmcnamara or anyone else still tagging official releases? The commit history shows failing tests on some of the commits since the last tagged release in 2022, so I'm a little hesitant to just clone and build `master` for a production app.

**Comment by jmcnamara** [comment]
I have mainly been spending my free time and energy on the Rust version of this library lately but the C version is due a release to roll up some fixes.

I'll try do that in the next few days.

**Comment by jmcnamara** [comment]
Release 1.1.6 has been tagged on main. Regards.
