### ISSUE TITLE
1.1.6 release did not get marked as latest release

### ISSUE THREAD

**Issue by chenrui333** [jmcnamara/libxlsxwriter#438]
👋 it looks like 1.1.6 release did not get marked as latest release, raise this issue for some awareness. Thanks! 

![image](https://github.com/jmcnamara/libxlsxwriter/assets/1580956/150fae7a-2680-4334-8b7e-79b366bcc8c8)

cc @jmcnamara

relates to https://github.com/Homebrew/homebrew-core/pull/168137

**Comment by jmcnamara** [comment]
There was a break in the release CI and that part didn't get done. It is fixed now but let me know if you have any issues.

**Comment by jmcnamara** [comment]
I need to do a hot fix release as 1.1.7 for a missing .so version increment. It should be available in the next hour or so. Better to wait for that.

**Comment by jmcnamara** [comment]
> I need to do a hot fix release as 1.1.7 for a missing .so version increment.

Done.

**Comment by chenrui333** [comment]
Thanks @jmcnamara!!
