### ISSUE TITLE
How to insert image data of type CV:: Mat

### ISSUE THREAD

**Issue by ZRBzrb6119** [jmcnamara/libxlsxwriter#439]
The byte data of type CV:: Mat seems to fail the image type verification
`
if (memcmp(&signature[1], "PNG", 3) == 0) 
{
        if (_process_png(image_props) != LXW_NO_ERROR)
            return LXW_ERROR_IMAGE_DIMENSIONS;
}
    else if (signature[0] == 0xFF && signature[1] == 0xD8) {
        if (_process_jpeg(image_props) != LXW_NO_ERROR)
            return LXW_ERROR_IMAGE_DIMENSIONS;
    }
    else if (memcmp(signature, "BM", 2) == 0) {
        if (_process_bmp(image_props) != LXW_NO_ERROR)
            return LXW_ERROR_IMAGE_DIMENSIONS;
    }
    else if (memcmp(signature, "GIF8", 4) == 0) {
        if (_process_gif(image_props) != LXW_NO_ERROR)
            return LXW_ERROR_IMAGE_DIMENSIONS;
    }
    else {
        LXW_WARN_FORMAT1("worksheet image insertion: "
                         "unsupported image format for: %s.",
                         image_props->filename);
        return LXW_ERROR_IMAGE_DIMENSIONS;
    }
`

**Comment by jmcnamara** [comment]
A couple of questions:

- Is the image type in the buffer actually supported by libxlsxwriter?
- If so what happens if you dump the image to a file and then create a simple hello world program that inserts the image from a file (not buffer)?
- Could you attach a sample image that is failing?

**Comment by jmcnamara** [comment]
Closing due to lack of feedback. I will reopen with a working example or if the questions above are answered.
