### ISSUE TITLE
add support for xlsb

### ISSUE THREAD

**Issue by 675076143** [jmcnamara/libxlsxwriter#452]
https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-xlsb/acc8aa92-1f02-4167-99f5-84f9f676b95a

**Comment by jmcnamara** [comment]
Unfortunately adding support for xlsb is non-trivial and would take a lot of work to duplicate all of the xml writing code with equivalent BIFF binary writing code. It is also much harder to debug when something goes wrong. I know this from experience of working with the xls file format.

So overall this is a "won't/can't fix".
