### ISSUE TITLE
It seems there is a memory leak in constant memory enabled when trying to insert date 

### ISSUE THREAD

**Issue by videni** [jmcnamara/libxlsxwriter#453]
Sorry, I don't know much about C. I can't reproduce it with C. I only found the problem in [here](https://github.com/viest/php-ext-xlswriter/issues/455). I copy the critical code here if you can spot it quickly. The code enabled const memory is not copied here, but it is enabled in my local. The code looks very normal. 

```
PHP_METHOD(vtiful_xls, insertDate)
{
    zval *data = NULL, *format_handle = NULL;
    zend_long row = 0, column = 0;
    zend_string *format = NULL;

    ZEND_PARSE_PARAMETERS_START(3, 5)
            Z_PARAM_LONG(row)
            Z_PARAM_LONG(column)
            Z_PARAM_ZVAL(data)
            Z_PARAM_OPTIONAL
            Z_PARAM_STR_OR_NULL(format)
            Z_PARAM_RESOURCE_OR_NULL(format_handle)
    ZEND_PARSE_PARAMETERS_END();

    ZVAL_COPY(return_value, getThis());

    xls_object *obj = Z_XLS_P(getThis());

    WORKBOOK_NOT_INITIALIZED(obj);
    SHEET_LINE_SET(obj, row);

    if (Z_TYPE_P(data) != IS_LONG) {
        zend_throw_exception(vtiful_exception_ce, "timestamp is long", 160);
        return;
    }

    // Default datetime format
    if (format == NULL || (format != NULL && ZSTR_LEN(format) == 0)) {
        format = zend_string_init(ZEND_STRL("yyyy-mm-dd hh:mm:ss"), 0);
    }

    lxw_datetime datetime = timestamp_to_datetime(data->value.lval);

    if (format_handle != NULL) {
        datetime_writer(&datetime, row, column, format, &obj->write_ptr, zval_get_format(format_handle));
    } else {
        datetime_writer(&datetime, row, column, format, &obj->write_ptr, obj->format_ptr.format);
    }

    // Release default format
    if (ZEND_NUM_ARGS() == 3) {
        zend_string_release(format);
    }
}
```

```
/*
 * Write the datetime to the file
 */
void datetime_writer(lxw_datetime *datetime, zend_long row, zend_long columns, zend_string *format, xls_resource_write_t *res, lxw_format *format_handle)
{
    lxw_format *value_format = workbook_add_format(res->workbook);

    if (format_handle != NULL) {
        format_copy(value_format, format_handle);
    }

    format_set_num_format(value_format, ZSTR_VAL(format));
    worksheet_write_datetime(res->worksheet, (lxw_row_t)row, (lxw_col_t)columns, datetime, value_format);
}
```

**Comment by jmcnamara** [comment]
- What OS are you using?
- What hardware is it?
- On the OS is the /tmp directory mapped to system memory?
- Are you seeing a "leak" where the application doesn't return memory to the OS after it completes?
- Or are you seeing a situation where the application just consumes memory as it runs?

If it is the last one **and** your /tmp is mapped to memory then the application is consuming disk space but that disk space has been mapped to memory. 

If this is the case then libxlsxwriter has an option to change the location of the temp files it used:

http://libxlsxwriter.github.io/workbook_8h.html#a7329be90faba9e9ee65f58cb221aa4f1

Check if php-ext-xlsxwriter has the same opinion. 

Note, libxlsxwriter has hundreds of tests for memory leaks that run in the CI so it is unlikely that it is an actual leak.

**Comment by videni** [comment]
@jmcnamara, thansk for the tips, there is  no option to change the location of the temp files in the  php-ext-xlsxwriter , and the problem it not the tmp files,    I run the code on MacOS, Ubuntu , Alpine linux, all have the issue. 

I think it can reproduced by this [link](https://github.com/viest/php-ext-xlswriter/issues/455#issuecomment-2311511661), you can observe continious growth of memory  when constant memory enabled and insert  1 million  rows with a datetime. sorry it is PHP code.

**Comment by jmcnamara** [comment]
Ok. Sorry I can't help you other than the advice above.

**Comment by videni** [comment]
@jmcnamara  after some experiments, I found this line caused the memory leak. does the code below remind you something please?

```
 lxw_format *value_format = workbook_add_format(res->workbook);

    if (format_handle != NULL) {
       // this line caused memory leak,
        format_copy(value_format, format_handle);
    }

```
the format_copy method
```
void format_copy(lxw_format *new_format, lxw_format *other_format)
{
    new_format->bold = other_format->bold;
    new_format->bg_color = other_format->bg_color;
    new_format->border_count = other_format->border_count;
    new_format->border_index = other_format->border_index;
    new_format->bottom = other_format->bottom;
    new_format->bottom_color = other_format->bottom_color;
    new_format->color_indexed = other_format->color_indexed;
    new_format->diag_border = other_format->diag_border;
    new_format->diag_color = other_format->diag_color;

    new_format->font_size = other_format->font_size;
    new_format->bold = other_format->bold;
    new_format->italic = other_format->italic;
    new_format->font_color = other_format->font_color;
    new_format->underline = other_format->underline;
    new_format->font_strikeout = other_format->font_strikeout;
    new_format->font_outline = other_format->font_outline;
    new_format->font_shadow = other_format->font_shadow;
    new_format->font_script = other_format->font_script;
    new_format->font_family = other_format->font_family;
    new_format->font_charset = other_format->font_charset;
    new_format->font_condense = other_format->font_condense;
    new_format->font_extend = other_format->font_extend;
    new_format->theme = other_format->theme;
    new_format->hyperlink = other_format->hyperlink;

    new_format->hidden = other_format->hidden;
    new_format->locked = other_format->locked;

    new_format->text_h_align = other_format->text_h_align;
    new_format->text_wrap = other_format->text_wrap;
    new_format->text_v_align = other_format->text_v_align;
    new_format->text_justlast = other_format->text_justlast;
    new_format->rotation = other_format->rotation;

    new_format->fg_color = other_format->fg_color;
    new_format->bg_color = other_format->bg_color;
    new_format->pattern = other_format->pattern;
    new_format->has_fill = other_format->has_fill;
    new_format->has_dxf_fill = other_format->has_dxf_fill;
    new_format->fill_index = other_format->fill_index;
    new_format->fill_count = other_format->fill_count;

    new_format->border_index = other_format->border_index;
    new_format->has_border = other_format->has_border;
    new_format->has_dxf_border = other_format->has_dxf_border;
    new_format->border_count = other_format->border_count;

    new_format->bottom = other_format->bottom;
    new_format->diag_border = other_format->diag_border;
    new_format->diag_type = other_format->diag_type;
    new_format->left = other_format->left;
    new_format->right = other_format->right;
    new_format->top = other_format->top;
    new_format->bottom_color = other_format->bottom_color;
    new_format->diag_color = other_format->diag_color;
    new_format->left_color = other_format->left_color;
    new_format->right_color = other_format->right_color;
    new_format->top_color = other_format->top_color;

    new_format->indent = other_format->indent;
    new_format->shrink = other_format->shrink;
    new_format->merge_range = other_format->merge_range;
    new_format->reading_order = other_format->reading_order;
    new_format->just_distrib = other_format->just_distrib;
    new_format->color_indexed = other_format->color_indexed;
    new_format->font_only = other_format->font_only;
}
```

**Comment by jmcnamara** [comment]
That definitely looks like an issue. It seems to be creating a new format object for each call to `datetime_writer()`. These objects are cleaned up on exit so it isn't a **leak**. However, it will cause a memory **growth**. Especially, if you writing a million cells.

You should contact the author and let them know.

You may be able to work around it by writing a number instead of a date. In Excel a date is a number with a format. You will need to covert the dates yourself but it will avoid this issue (unless the number writer is doing the same thing).

See: https://libxlsxwriter.github.io/working_with_dates.html

**Comment by videni** [comment]
@jmcnamara I see, thanks a lot. Finally, I understand what the real problem is. The `php-ext-xlswriter` almost calls the `workbook_add_format ` method for each cell. that  issue existed for 2 years, still not fixed. Some design issues might exist , not easy to fix.   There might be two ways to solve the problem:

1.   Reuse existing from upper level code. 
2.  Or don't create format for each cell,  but use the format set by  `set_column` method instead.

 except strings,  the `number` has the same issue as `datetime`,  if no format passed for the `worksheet_write_string`, `worksheet_write_number`, `worksheet_write_datetime`, it will use the format set by the`set_column` method , right?

**Comment by videni** [comment]
Closed  as solved by php-ext-xlswriter,  @jmcnamara  thanks for help,
