### ISSUE TITLE
Any plans for Shape support?

### ISSUE THREAD

**Issue by znakeeye** [jmcnamara/libxlsxwriter#457]
In [drawing.c(847)](https://github.com/jmcnamara/libxlsxwriter/blob/d9633436dcfee1d5018218e7b980241ccd612245/src/drawing.c#L847) there seems to be a comment indicating that `Shape` support is coming. Any plans for it?

E.g.:

![image](https://github.com/user-attachments/assets/194b7366-fd5e-4009-80e8-b5d14deefb72)

If not planned, is it possible to somehow write a custom element. If I could store xml as a string and feed it to some API...

**Comment by jmcnamara** [comment]
That is supported in the Python/Perl/Rust versions (at least for textboxes): https://xlsxwriter.readthedocs.io/working_with_textboxes.html

However, I don't have plans to implement it in the C version due to the work involved and the fact that it isn't frequently requested.

**Comment by jmcnamara** [comment]
Closing as won't fix. Sorry.

**Comment by znakeeye** [comment]
Ok. And there is no way to somehow write custom xml? I.e. I would grab `drawing1.xml` from an XLSX file and inject that when writing using `libxlsxwriter`.

**Comment by jmcnamara** [comment]
> is no way to somehow write custom xml? I.e. I would grab `drawing1.xml` from an XLSX file and inject that when writing using `libxlsxwriter`

Unfortunately not. There are drawing and shape ids that need to be tracked/updated and additional file references to be added. That is one of the implementation difficulties with the xlsx format, there are a lot of interlinked relationships.
