### ISSUE TITLE
Read overflows causing corruption, and performance issues

### ISSUE THREAD

**Issue by znakeeye** [jmcnamara/libxlsxwriter#459]
Please check `utility.c`. There you find several of these **dangerous** loops:
```c
while (p && some_operation_here)
    p++;
```
It should be `*p` in all cases. E.g. See `lxw_name_to_row_2` where parsing "A1" would increment `p` like 1,000,000 times with some bad luck. Thus, we have a read overflow.

**Fix:**
1. Replace all `if (p)` with `if (*p)`
2. Replace all `while (p` with `while (*p`

**Comment by jmcnamara** [comment]
If you need one just for this I can do one. Let me know.

**Comment by znakeeye** [comment]
Yes please. Maintaining local patches is not great 🙂

**Comment by jmcnamara** [comment]
The changes are upstream in v1.1.9
