### ISSUE TITLE
Feature request: tmpdir

### ISSUE THREAD

**Issue by eroncastro** [jmcnamara/libxlsxwriter#46]
From https://xlsxwriter.readthedocs.org/workbook.html
- "tmpdir: XlsxWriter stores worksheet data in a temporary files prior to assembling the final XLSX file. The temporary files are created in the system’s temp directory. If the default temporary directory isn’t accessible to your application, or doesn’t contain enough space, you can specify an alternative location using the tempdir option:"

Could you please add this option to your C library?

Thanks in advance,

Eron

**Comment by jmcnamara** [comment]
Hi Eron,

I implemented a workaround for this in the following patch:

https://github.com/jmcnamara/libxlsxwriter/commit/211dacdfd87978a1c0ac040177c1cb6eda06b445

However, it isn't ANSI C compliant so it isn't integrated into the master branch.

You can try it out in your own code to see if it works for you.

John.
