### ISSUE TITLE
zig build update - deprecates defineCMacro -> root_module.addCMacro

### ISSUE THREAD

**Issue by zigster64** [jmcnamara/libxlsxwriter#465]
Not a bug in libxlswriter ...

With the zig build, recent compiler update has a breaking change to the way C Macros are passed from the build system to the target platform.

https://github.com/ziglang/zig/commit/142471fcc46070326526e3976f0150fe734df0b6

effect is that usage of defineCMacro should be replaced now with root_module.addCMacro

Added a PR to cover this. PR is tested with a build of zig-libxlswriter, and then end to end tested with my Zig app that generates spreadsheets.

**Comment by jmcnamara** [comment]
PR merged.

**Comment by l14zj** [comment]
https://www.instagram.com/fgv5_?igsh=MXRleXVsamp6Nnd2cw==
