### ISSUE TITLE
Feature request: Per-cell indentation

### ISSUE THREAD

**Issue by evanmiller** [jmcnamara/libxlsxwriter#48]
Hi, I am currently porting code from xlslib over to libxlsxwriter. One of the incompatibilities I'm hitting is that xlslib allows setting certain attributes on a per-cell basis, including indentation and font, without explicitly defining a workbook-wide format.

I am unfamiliar with XLSX internals, but I would like to request the ability to set the indentation of each cell without having to define a separate format for that indentation level. Right now I am forced to create formats for the Cartesian product of (numeric format strings) x (indentation levels), and the code is getting hairy.

**Comment by jmcnamara** [comment]
> without explicitly defining a workbook-wide format.

The main issue here is that in Excel indentation and fonts are part of formats and are workbook wide. The library could hide that but for now it doesn't.

> Right now I am forced to create formats for the Cartesian product of (numeric format strings) x (indentation levels), and the code is getting hairy.

I feel your pain.This is a frequently requested feature in the Perl and Python versions as well.

However, realistically it isn't going to be implemented in the short term until it is implemented first in the other versions and ported over.

**Comment by jmcnamara** [comment]
Closing this as it is unlikely to be implemented.
