### ISSUE TITLE
OSX yosemite make results in: unknown type name 'z_crc_t'

### ISSUE THREAD

**Issue by aalvarado** [jmcnamara/libxlsxwriter#5]
Unable to compile on OSX Yosemite

I installed both zlib from homebrew-dupes and minizip but I'm unable to use export flags in the Makefile.

Please advice.

```
> ~/projects/libxlsxwriter $ make
zip.c:160:11: error: unknown type name 'z_crc_t'
    const z_crc_t* pcrc_32_tab;
          ^
In file included from zip.c:186:
./crypt.h:35:53: error: unknown type name 'z_crc_t'
static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                    ^
./crypt.h:48:51: error: unknown type name 'z_crc_t'
static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                  ^
./crypt.h:65:69: error: unknown type name 'z_crc_t'
static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                    ^
./crypt.h:94:28: error: unknown type name 'z_crc_t'
                     const z_crc_t* pcrc_32_tab,
                           ^
5 errors generated.
make[1]: *** [zip.so] Error 1
make: *** [all] Error 2
``

**Comment by jmcnamara** [comment]
Hi Adan,

I don't normally use homebrew to get libs so I'll look into that. I have an idea why it isn't working.

In the meantime can you install Zlib using the method suggested in the [Getting Started](http://libxlsxwriter.github.io/getting_started.html) section of the docs. I use that on OS X and it works fine.

John

**Comment by aalvarado** [comment]
will do, and report back, thanks!

**Comment by aalvarado** [comment]
following the getting started guide did work, thanks!

**Comment by aalvarado** [comment]
I was able to compile zlib separately and make minizip compile by placing the libs from zlib two directories above and running make.

**Comment by jeroen** [comment]
I just ran into exactly the same problem. I found that you can also make it work by compiling with

    CPPFLAGS=-DNOCRYPT

This skips over the crypto types. I don't think these are used by `libxlswriter`? @jmcnamara

**Comment by jmcnamara** [comment]
> I just ran into exactly the same problem.

I doubt you encountered the same issue but you may have seen the same symptoms. Probably best to open a new bug report with the steps to reproduce it.



> This skips over the crypto types. I don't think these are used by libxlswriter?

Correct. They aren't used and libxlsxwriter compiles it's local copy of minizip with:

    CFLAGS += -O3 -DNOCRYPT -DNOUNCRYPT
