### ISSUE TITLE
Feature request: Add other chart features

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#51]
Add chart functions like the Python XlsxWriter module.
See https://xlsxwriter.readthedocs.org/index.html

Formatting:
- [x] Chart formatting: Line/Border
- [x] Chart formatting: Solid Fill
- [x] Chart formatting: Pattern Fill
- [x] Chart formatting: Fonts

Features:
- [x] Chart series option: Marker

- [x] Chart axes: Reverse
- [x] Chart axes: Max and min
- [x] Chart axes: Log base

Functions:
- [x] Chart set_legend()
- [x] Chart set_chartarea()
- [x] Chart set_plotarea()

- [x] Chart set_rotation()
- [x] Chart set_hole_size()

Add +1 as a comment to vote for the feature you would like and  to get an update when it is implemented.

**Comment by Diddlik** [comment]
+1

**Comment by jmcnamara** [comment]
Chart fonts added in 0.4.4.

**Comment by jmcnamara** [comment]
Chart legends added in 0.4.5.

**Comment by jmcnamara** [comment]
Chart line and fill formatting added in 0.4.6.

**Comment by jmcnamara** [comment]
Chart axes: Reverse, Max and min, Log base added in 0.4.7.

**Comment by jmcnamara** [comment]
Chart marker added in 0.4.8: http://libxlsxwriter.github.io/working_with_charts.html#chart_markers

**Comment by jmcnamara** [comment]
Closing this with 13 completed items and moving the remaining items to other Feature requests.
