### ISSUE TITLE
Feature request:add border line functions

### ISSUE THREAD

**Issue by BillSheng** [jmcnamara/libxlsxwriter#52]
I just put your library into my Xcode project and it works just fine. Thank you for your great lib.
But I have to draw border lines of cells for users want this feature as a formal excel document.
Is it possible?

**Comment by jmcnamara** [comment]
Hi,

You can either use a merge range (like this [example](http://libxlsxwriter.github.io/merge_range_8c-example.html)) or else create a format for each of the cells in the range with the appropriate border components. For a 3x3 range, or larger, you will need 8 individual formats. It is a bit of work but it is doable.

John

**Comment by BillSheng** [comment]
Hi, John,

Thank you for your example!

But I don't want to merge cells to get border line,
Would you please give me a sample to draw lines
for selected range without merge?

Thank you in advance.

SHENG

2016/06/15 7:13$B!"(BJohn McNamara <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by BillSheng** [comment]
I found the way to draw border for every cell,
Thanks!

Sheng

2016/06/15 10:43$B!"(BYongming SHENG <sheng@kernel-soft.co.jp> $B$N%a%C%;!<%8(B:
