### ISSUE TITLE
Warning about redefinition of SLIST_ENTRY

### ISSUE THREAD

**Issue by utelle** [jmcnamara/libxlsxwriter#57]
The source file `packager.c` includes the header file `windows.h`. At least using Visual C++ 2010 I get a warning that the symbol `SLIST_ENTRY` is redefined in header file `winnt.h` which is indirectly included by `windows.h`. It's just a warning and the symbol is not used in `packager.c`, so no harm is done. However, it might be a good idea to rename the symbol in `libxlsxwriter` to something else to avoid name clashes (and thus potential problems).

**Comment by jmcnamara** [comment]
Hi Ulrich,

I don't see that warning using this [project ](https://github.com/jmcnamara/MSVCLibXlsxWriter)in MSVC 2013.

The `SLIST_ENTRY` is a macro definition of a struct and it comes from the FreeBSD/Linux header `queue.h` which is included with libxlsxwriter.

So I think you will just have to live with this warning in MSVC 2010.

John

**Comment by utelle** [comment]
Interesting. Maybe this warning is related to the Windows SDK in use - which might be different for MSVC 2013.

Some googling reveals that other projects seem to be affected, too. Some define a different symbol to avoid the warning. I also found a version of [queue.h](https://searchcode.com/codesearch/view/11905748/), which explicitly undefines the symbol before redefining it. However, the latter only works if `windows.h` is included **before** `queue.h`. For `libxlsxwriter` this would currently not work, since `windows.h` is included **afterwards**.

Personally, I can live with the warning. So feel free to close this issue.

**Comment by jmcnamara** [comment]
Okay. Thanks for the followup. Closing.

**Comment by jmcnamara** [comment]
Hi, 

I pushed a fix for this warning to master. Basically it undefs the macro before including `windows.h`.

When you get a chance you can try it and let me know if it fixes the warning on Windows.

John

**Comment by utelle** [comment]
Yes, this eliminates the warning.

**Comment by ZChidori** [comment]
No,doesn't affect my use,I just want to solve it.In any case,thanks.
