### ISSUE TITLE
Feature request: add support for charts

### ISSUE THREAD

**Issue by mts749** [jmcnamara/libxlsxwriter#6]
I noticed that chart creation is supported in the Python version. Would it be possible to add this capability to the C library?

Thanks,
Martin

**Comment by jmcnamara** [comment]
Hi,

That is the plan. The features will probably mirror the XlsxWriter features, in the same order of addition.

John

**Comment by mts749** [comment]
Thanks very much.

Is there somewhere I can look to see the history of the XlsxWriter feature additions?

Also, not sure if this is the correct venue, but I would like to commend you on these libraries. The code is very clean and elegant and the documentation is beautiful. Well done!

Martin

**Comment by jmcnamara** [comment]
> Is there somewhere I can look to see the history of the XlsxWriter feature additions?

Whoops, sorry, I meant to add a link to the XlsxWriter Changes file. [Here it is](https://xlsxwriter.readthedocs.org/changes.html).


> Also, not sure if this is the correct venue, but I would like to commend you on these libraries.

Thanks. :-)

**Comment by mts749** [comment]
Just wondering if you have an ETA/schedule for porting the XlsxWriter features to libxlsxwriter?

Also, I'm happy to contribute to this effort if desired. 

Martin

**Comment by jmcnamara** [comment]
> Just wondering if you have an ETA/schedule for porting the XlsxWriter features to libxlsxwriter?

I try to avoid setting any time expectations but I would say that something like charts in libxlsxwriter is at least 6 months away.

Perhaps https://github.com/dbzhang800/QtXlsxWriter might more useful to you in the meantime.

**Comment by mts749** [comment]
Thanks for this. I had a quick look at the project. I'm hesitant to move to another library just for charts especially since I have built a (small, and admittedly incomplete) objC interface on top of libxlsxwriter. 

I think I'll just wait for the features to be ported and concentrate on other aspects of my application.

**Comment by jmcnamara** [comment]
Closing this in favour of the same feature request at #36.
