### ISSUE TITLE
Add support for OpenBSD

### ISSUE THREAD

**Issue by edgarpettijohn** [jmcnamara/libxlsxwriter#65]
Here are my patches to build on OpenBSD 6.0 with no errors/warnings.  Please review and include in src distribution.  I haven't gotten a chance to really play around with the lib yet, but all of the examples I've looked at and built, etc seem to work well and are easy to follow.  It reminds me of GTK+. 

[libpatch.txt](https://github.com/jmcnamara/libxlsxwriter/files/358422/libpatch.txt)

Thanks!

**Comment by jmcnamara** [comment]
Hi Edgar,

Thanks for that. It is good to support another OS. I'll merge the changes up in the next few days.

One question. Are the patches to `miniunz.c` and `minizip.c` actually required? They aren't used by libxlsxwriter and are only included since they are part of the [minizip component from zlib](https://github.com/madler/zlib/tree/develop/contrib/minizip).

Thanks for your contribution.

John

**Comment by edgarpettijohn** [comment]
Sent from my iPhone

> On Jul 12, 2016, at 3:24 AM, John McNamara <notifications@github.com> wrote:
> 
> Hi Edgar,
> 
> Thanks for that. It is good to support another OS. I'll merge the changes up in the next few days.
> 
> One question. Are the patches to miniunz.c and minizip.c actually required? They aren't used by libxlsxwriter and are only included since they are part of the minizip component from zlib.
> 

I'll have to check. I just took a knife to everything fseeko64 related.

Edgar

**Comment by edgarpettijohn** [comment]
I think the problem is that there is no way to tell the Makefile that I want to use my systems zlib.  Or I'm missing something. 

Edgar

**Comment by jmcnamara** [comment]
Hi Edgar,

I've set up an OpenBSD system for testing and I've pushed up a few fixes for the issues you pointed out and a few other warnings from the unit test suite. You can try it when you get a chance.

I didn't have to install the zlib dev libraries at all which is nice.

I'm building Python at the moment (pkg_add failed to install any of the Python versions for some reason). Once it is done I'll check if everything is okay in functional test suite.

John

**Comment by jmcnamara** [comment]
I got Python installed and working and the test suite passes on OpenBSD 5.9. There are a few more warnings, that I don't see on other systems, to get rid off but they are mostly harmless.

**Comment by edgarpettijohn** [comment]
Thats what I assumed.  I built all of the examples and they seemed to work properly, so I wasn't going to dig into the tests.

**Comment by edgarpettijohn** [comment]
builds without error/warnings.

**Comment by jmcnamara** [comment]
Great. Thanks for letting me know and for pointing out the issue in the first place.

**Comment by edgarpettijohn** [comment]
As far as packaging goes.  I would rather follow releases.  When do you expect to have another release?  If its a ways off I'll figure something out.

**Comment by jmcnamara** [comment]
Hi Edgar,

I pushed a new release, 0.4.2, with the OpenBSD fixes just a short while ago: http://libxlsxwriter.github.io/changes.html

Closing, thanks.

John
