### ISSUE TITLE
Exporting lxw_strerror symbol for C++

### ISSUE THREAD

**Issue by lemmel** [jmcnamara/libxlsxwriter#66]
Hi.

I'm a C++ developper and I gave a try to your library, and I saw that the lxw_strerror function wasn't exported as C symbol.

The file : include/xlsxwriter/utility.h
I moved the block
```
#ifdef __cplusplus
extern "C" {
#endif
```
just above the declaration of lxw_strerror.

P.S. : Thanks a lot for giving time to create such a library.

**Comment by jmcnamara** [comment]
Thanks for the report.

Fixed on the master branch. Closing.

John
