### ISSUE TITLE
Improve documentation about column width unit

### ISSUE THREAD

**Issue by lemmel** [jmcnamara/libxlsxwriter#67]
Could you add something about the unit used when setting (e.g. through the  worksheet_set_column_opt function) the width of a column ?

It is not cm, mm, inch, pica because when I looked for information about it, I found :
- http://ericwhite.com/blog/precisely-calculating-cell-sizes-in-open-xml-spreadsheetml/ (precisely at https://youtu.be/zgO_vOfThCI?t=238)
- ISO/IEC 29500-1:2012 (can be found: http://standards.iso.org/ittf/PubliclyAvailableStandards/index.html)

I quote the ISO document: 
> Column width measured as the number of characters of the maximum digit width of the
numbers 0, 1, 2, ..., 9 as rendered in the normal style's font. There are 4 pixels of margin
padding (two on each side), plus 1 pixel padding for the gridlines.

So to be sure of a column width, the developper must define the default font and set the width accordingly.

P.S. : 
- I'm not sure about it, but it seems that the Excel vanilla default font is Calibri, style Normal, Size 11. I don't know for sure that user settings can not change that value (i.e. that the value is per document)
- libreoffice, and probably openoffice, under Linux do strange things with width, and don't get the good width.

**Comment by jmcnamara** [comment]
Hi,

This is explained a little better in the docs for the [Python version of this library](http://xlsxwriter.readthedocs.io/worksheet.html#worksheet-set-column): 

> The width parameter sets the column width in the same units used by Excel which is: the number of characters in the default font. The default width is 8.43 in the default font of Calibri 11. The actual relationship between a string width and a column width in Excel is complex. See the following explanation of column widths from the [Microsoft support documentation for more details](https://support.microsoft.com/en-us/kb/214123).

I'll port that, and the other updated text, to the C docs.

John

**Comment by jmcnamara** [comment]
I've pushed a update to master and regenerated the online docs.

Thanks for the report.

Closing.

John
