### ISSUE TITLE
Feature Request: Option to set logarithmic scale on Y axis

### ISSUE THREAD

**Issue by Racerxali** [jmcnamara/libxlsxwriter#70]
Hi, 

While using the chart settings, I don't find any option to set logarithmic scale. Can u please guide how can we use this feature. Also when using scatter chart, there seems to be an issue that it does not show series title in the legend (rather it shows default series title like Series1) when using chart_series_set_name(), while proper series name appears in other charts. I hope this is not a bug.

**Comment by jmcnamara** [comment]
Hi,,

> While using the chart settings, I don't find any option to set logarithmic scale

Unfortunately, that isn't supported yet.

It is supported in the Perl/Python version of the lib so it will be ported over in time: https://xlsxwriter.readthedocs.io/chart.html?highlight=log#chart-set-x-axis



> Also when using scatter chart, there seems to be an issue that it does not show series title in the legend (rather it shows default series title like Series1) when using chart_series_set_name(), while proper series name appears in other charts. I hope this is not a bug.

It should work. There are tests for it and the following example shows it: http://libxlsxwriter.github.io/chart_scatter_8c-example.html

If you think it doesn't work in some condition then open up a new issue and submit a small example program that demonstrates it.

Thanks,

John

**Comment by jmcnamara** [comment]
Log scale added in version 0.4.7: http://libxlsxwriter.github.io/chart_8h.html#ac27a9a20daf4f0a6be8595fbd7f41151

Also fixed the issue with chart titles in Scatter charts. Thanks for the report.
