### ISSUE TITLE
Worksheet row or column index out of range Error

### ISSUE THREAD

**Issue by ankithherle** [jmcnamara/libxlsxwriter#74]
I am getting `Worksheet row or column index out of range` when I tried to Write a cell.

1. - I write cell in 2nd row row and 1st column in 1st iteration of the loop
2. - When I try to write a cell in the 2nd row row and 2nd column in the 2nd iteration I am getting out of range error.

What is the reason for above mentioned behavour ?
What are cases or possibilities which can result in ` Worksheet row or column index out of range Error`  ?

**Comment by jmcnamara** [comment]
Hi Ankith,

Could you add a small, complete, working example that demonstrates the issue.

John

**Comment by ankithherle** [comment]
Thanks for replying. 
I will update the issue description.

**Comment by ankithherle** [comment]
@jmcnamara Updated the issue description, please check.

**Comment by jmcnamara** [comment]
@ankithherle What I really need is a small example program that demostrates the issue. Like this:

```C
#include <stdio.h>
#include "xlsxwriter.h"

int main() {

    printf("Libxlsxwriter version = %s\n", LXW_VERSION);

    // Your code here.

    return 0;
}
```

Also, let me know the version printed out from the example on your system.

See also [Report Bugs in libxlsxwriter](https://github.com/jmcnamara/libxlsxwriter/blob/master/CONTRIBUTING.md).

**Comment by ankithherle** [comment]
#### Sample code from which Error is generated
```c
#include "stdio.h"
#include "xlsxwriter.h"


void write_workbook()
{
    lxw_workbook_options workbook_options = {.constant_memory = 1, .tmpdir = "/tmp"};
    lxw_workbook  *workbook = workbook_new_opt("SAMPLE.xlsx", &workbook_options);
    lxw_worksheet *worksheet_1 = workbook_add_worksheet(workbook, "SHEET 1");
    lxw_worksheet *worksheet_2 = workbook_add_worksheet(workbook, "SHEET 2");

    lxw_format *format = workbook_add_format(workbook);
    format_set_font_color(format, LXW_COLOR_BLACK);
    format_set_align(format, LXW_ALIGN_CENTER);
    format_set_align(format, LXW_ALIGN_VERTICAL_TOP);
    format_set_border(format, LXW_BORDER_THIN);

    worksheet_set_column(worksheet_2, 0, 30, 25, NULL);

    char string[256];

    worksheet_write_blank(worksheet_2, 0, 0, format);
    worksheet_write_blank(worksheet_2, 1, 0, format);

    for (int column = 0; column < 30; column ++) {
        for (int row = 0; row < 100; row++) {
            lxw_error error_ = worksheet_write_string(worksheet_2, row, column, "SAMPLE STIRNG", format);
            if (error_) {
                printf("Error %d - %d = %s\n", row, column, lxw_strerror(error_));
            }
        }
    }

    workbook_close(workbook);
}

int main(int argc, char * argv[])
{
    write_workbook();

    return 0;
}
```

**Comment by ankithherle** [comment]
@jmcnamara 

Link to file which contains output printed on terminal:
[https://drive.google.com/open?id=0B4rT-3u4TZHkYVlHMnJraThhb00](url)

Link to Sample xlsx file genrated:
https://drive.google.com/open?id=0B4rT-3u4TZHkZG92OC1kakxjaW8


Look into this.

**Comment by jmcnamara** [comment]
@ankithherle 

Thanks for the example. In general output files aren't useful but the programs that generate them are.

The issue here is that you are using `constant_memory` option and in that mode the cell data must be written in row x column order or else the data will be ignore.

This is explained in the docs in [Constant Memory Mode](https://libxlsxwriter.github.io/working_with_memory.html) and also in the section on [`workbook_new_opt()`](https://libxlsxwriter.github.io/workbook_8h.html#a8ca9bd8c30c618b81ca6180f78b03323).

The solution is to not use constant memory mode or else structure your code so the data is written in row x column order. In your example, switching the order of the for loops will help but you will also have to move the `write_blank()` calls.

**Comment by ankithherle** [comment]
Issue is resolved after I removed `constant_memory`. Thank you @jmcnamara .
