### ISSUE TITLE
Multiple feature Requests

### ISSUE THREAD

**Issue by ankithherle** [jmcnamara/libxlsxwriter#75]
@jmcnamara 
Any updates about 

- [issue #31](https://github.com/jmcnamara/libxlsxwriter/issues/31)

- [issue #38](https://github.com/jmcnamara/libxlsxwriter/issues/38)

Are these two features not yet implemented ?

**Comment by ankithherle** [comment]
@jmcnamara 
I have asked same question through email last week

**Comment by jmcnamara** [comment]
In general if there is any update on a feature request I add it to the feature request.

So in this case there are no updates.
