### ISSUE TITLE
constant memory mode problem

### ISSUE THREAD

**Issue by xakepsoft** [jmcnamara/libxlsxwriter#76]
xlsx file created using {.constant_memory = LXW_TRUE , .tmpdir = NULL}
cannot be read by akeneo-labs xlsx php reader.

File created with 'options' contains  xl/sharedStrings.xml however file without 'options' doesn't have that. 

Is there a way to prevent creation of xl/sharedStrings.xml ??? 
I would like to disable it for a while until akeneo-labs guys fix their issue with shared strings.

LibreOffice reads both files ok.

**Comment by jmcnamara** [comment]
> File created with 'options' contains xl/sharedStrings.xml however file without 'options' doesn't have that.

Just to be clear, I think that should be the other way around. Basically it works like this:

1. In default libxlsxwriter `new()` mode the `constant_memory` mode is off and the library writes any strings to the `xl/sharedStrings.xml` file. This can be considered a "standard" xlsx file.
2. When  `constant_memory` in on the libxlsxwriter library avoids a non constant memory overhead by writing the strings "inline" in the `worksheet.xml` files and avoid using the `xl/sharedStrings.xml` file. This is a documented Excel feature that is supported by most spreadsheet applications. However, some applications don't support it, such as Apple Numbers.

If spreadsheet-parser doesn't support it then you should avoid using the `constant_memory` option in libxlsxwriter.

I hope that clears things up.

John

**Comment by jmcnamara** [comment]
P.S., This side-effect is documented: http://libxlsxwriter.github.io/working_with_memory.html#ww_mem_inline_strings

**Comment by xakepsoft** [comment]
Thanx, a lot. 

I'll try to fix the reader so it conforms to standards.
