### ISSUE TITLE
undefined reference to `workbook_new', `workbook_close', etc. when compiling code

### ISSUE THREAD

**Issue by Z3ROQL** [jmcnamara/libxlsxwriter#77]
Hello! I successfully built **LibXlsxWriter.dll** and put it inside a folder with **Zlib.dll**, all **include files** (_xlsxwriter.h_ + _xlsxwriter folder_) and a **source code** (just a standard "Hello, world" code from your examples directory, nothing special). For some reason when I try to compile the code it gives me a lot of `undefined reference to [...]` errors, each of them for every function used. What could it be? Am I doing something wrong? Did I forget to put something in the folder?

**Comment by jmcnamara** [comment]
Hi,

What compiler are you using?

If MSVC then try the following project and follow the instructions: https://github.com/jmcnamara/MSVCLibXlsxWriter

Then let me know if you have an issue.

John

**Comment by Z3ROQL** [comment]
I'm using Dev-C++.

**Comment by jmcnamara** [comment]
The error that you see is just a linker or dynamic loader issue.

I had never heard of Dev-C++ but based on the webpage (http://www.bloodshed.net/dev/) it looks like it is an IDE with Mingw GCC as the compiler.

Libxlsxwriter work with Mingw and there are instructions in the docs: https://libxlsxwriter.github.io/getting_started.html#gsg_ming

Make sure that you link against libxlsxwriter and lz.

If you still can't get it working then it is probably best to ask in the Dev-C++ community or on StackOverflow.

**Comment by Z3ROQL** [comment]
Oh, I see. Thank you for your time. I acknowledge that I did a stupid mistake and I could've avoided to ask this question but I'm still a newbie : /
