### ISSUE TITLE
IOS SWIFT integration

### ISSUE THREAD

**Issue by paoloveggi** [jmcnamara/libxlsxwriter#8]
Hi, i installed the library in my swift project using cocoapods. I just add pod instructions in my podfile and then run "pod install". Now I can see the framework in my list of files, but i don't know how to use library inside my swift files...anyone can help me? I cannot find a working example of the code inside a swift project...

I try copying the sample code from documentation, but xcode says me that workbook type is undefined, etc...

Thank you, bye!

**Comment by jmcnamara** [comment]
I don't use the library within Xcode so I can't answer.

@lrossi supplied the cocoapod so he may be able to answer.

Or else just ask the question on StackOverflow.
