### ISSUE TITLE
Normal and superscript font in one cell

### ISSUE THREAD

**Issue by milissovs** [jmcnamara/libxlsxwriter#81]
Hi!

Is it possible to achieve format displayed at [this point](https://libxlsxwriter.github.io/format_8h.html#a471ca432e429505c79982ca5aecd1db0) - normal and superscript font in particular cell? How this could be done?

Best regards!
Emo.

**Comment by jmcnamara** [comment]
No. That feature hasn't been ported yet: https://xlsxwriter.readthedocs.io/example_rich_strings.html

There is already a feature request open for this #37. 

Add a +1 there to get an update when it is implemented.
