### ISSUE TITLE
Fit image to cell

### ISSUE THREAD

**Issue by iamabhiee** [jmcnamara/libxlsxwriter#85]
Library seems really good, I am trying to fit image to cell but I couldn't find a way, whats best way to do the same?

**Comment by jmcnamara** [comment]
Hi Abhishek,

The best, and only, way is to scale the image with the `worksheet_insert_image_opt()` function to fit into a standard Excel cell size of 20x64 pixels:

```C
lxw_image_options options = {.x_offset = 30,  .y_offset = 10,
                             .x_scale  = 0.5, .y_scale  = 0.5};
worksheet_insert_image_opt(worksheet, 2, 1, "logo.png", &options);
```

See the docs for `worksheet_insert_image_opt()`:  http://libxlsxwriter.github.io/worksheet_8h.html#a0b05e75e2c2a5c3452374714cdb2b79b

John
