### ISSUE TITLE
Feature request: Chartsheets

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/libxlsxwriter#90]
Add functionality like Python XlsxWriter Worksheet Chartsheets.

See https://xlsxwriter.readthedocs.io/working_with_charts.html#chartsheets

* Difficulty: 3 (Easy 1 - 5 Hard)
* Priority: 3 (High 1 - 5 Low)

Add +1 as a comment to vote for this feature and to get an update when it is implemented.

If you would like to make a donation to accelerate this feature you can do so via [PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ATE9EFWNF7PBJ) or contact me [directly](jmcnamara@cpan.org). Currently $7 of $400.

**Comment by Wired95** [comment]
+1

This lib is gem, good job! For a school project, I need to do some graphs. And have it done in a single chartsheet might be a **big** plus! 

Good luck, here is the python work if it can help : https://github.com/jmcnamara/XlsxWriter/commit/149bbda66726935e179e26dd1c542d4db27728ea.

**Comment by LordAndreas** [comment]
+1

(I'm working with this guy, he's annoying).

**Comment by jmcnamara** [comment]
Thanks. I'll take the request on board.

> Good luck, here is the python work if it can help : jmcnamara/XlsxWriter@149bbda.

I know. I wrote that code as well. :-)

**Comment by Wired95** [comment]
Nice !

**Comment by jmcnamara** [comment]
Since I've had a few requests about this I've added a note about making donations to prioritize this feature. See the Feature Request on GitHub.

**Comment by jmcnamara** [comment]
Note, there is an initial working version with chartsheet support on the `chartsheet` branch. See the [chartsheet.c](https://github.com/jmcnamara/libxlsxwriter/blob/chartsheet/examples/chartsheet.c) example.

Which produces this output:

![chartsheet](https://user-images.githubusercontent.com/94267/45264275-e731d500-b431-11e8-85b6-c1d25601cca1.png)

**Comment by jmcnamara** [comment]
Added in version 0.8.0: http://libxlsxwriter.github.io/chartsheet_8h.html
