### ISSUE TITLE
Install on maxOS should put files to /usr/local instead of /usr

### ISSUE THREAD

**Issue by danilcha** [jmcnamara/libxlsxwriter#93]
Now macOS has some system protection and even under root I cannot write to `/usr`. 

There is, however, a special dir for installing custom libs, it is `/usr/local`.

So the `make install` on macOS should install everything to `/usr/local` instead of `/usr`. 
I.e. to `/usr/local/lib` and `/usr/local/include`.

**Comment by jmcnamara** [comment]
Hi,

Yes. Agreed. That would be better for Linux as well.

I also want to add a `INSTALL_DIR` or `DESTDIR` variable to allow the dir to be specified/overridden.

I'll add it in the next release.

Thanks for the suggestion.

John

**Comment by jmcnamara** [comment]
I've pushed a change to master so that files are installed to `/usr/local` by default. The installation dir  can be overridden by using the `INSTALL_DIR` environmental variable:

    INSTALL_DIR=/usr/third_party make install

Thanks for the suggestion.
